### ISSUE TITLE
達成基準 1.4.11 非テキストのコントラスト

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#100]
ひとつめの箇条書き (ユーザインタフェースコンポーネント) の本文

> ユーザインタフェース コンポーネント及び状態 (state) を特定するために要求される視覚的な情報。

原文の「Visual information required to ... 」が「〜するために**要求される**視覚的な情報」と訳されていますが、「要求される」は「必要な」としてはいかがでしょうか？

(改善案)
ユーザインタフェース コンポーネント及び状態 (state) を特定するのに必要な視覚的な情報。

ふたつめの箇条書き (グラフィカルオブジェクト) では、「Parts of graphics **required to** understand the content」が「コンテンツを理解するのに**必要な**グラフィック部分」と訳されていますので、それに合わせて。

**Comment by caztcha** [comment]
[PR #165](https://github.com/waic/wcag21/pull/165) にて対応しました。

**Comment by momdo** [comment]
マージされたので閉じます。
