### ISSUE TITLE
「people with disabilities」の表記揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#101]
「people with disabilities」の訳が「障害のある人」「障害を持つ人」「障害者」で揺れています。（WCAG 2.0 もそうですけど）

**Comment by bakera** [comment]
>WCAG 2.0 もそうですけど
がーん。
ということで確認しましたが、以下の通りで「障害のある人」が優勢っぽいです。
user with disabilities (障害のある利用者) という表現もあるので、「障害のある」にしていくのが良さそうな印象です。

========
(障害のある人)
>Following these guidelines will make content accessible to a wider range of people with disabilities, including blindness and low vision, deafness and hearing loss, learning disabilities, cognitive limitations, limited movement, speech disabilities, photosensitivity and combinations of these. 
>このガイドラインに従うことで、全盲又はロービジョン、ろう又は難聴、学習障害、認知障害、運動制限、発話困難、光過敏性発作及びこれらの組合せ等を含んだ、様々な障害のある人に対して、コンテンツをアクセシブルにすることができる。

>does not cost a person with a disability any more than a person without a disability and
>is as easy to find and obtain for a person with a disability as it is for a person without disabilities.
>障害のある人に障害のない人よりも時間や労力がかかるようなことはなく、かつ、
>障害のある人も障害のない人と同じくらい容易に探して入手することができる。

>Until the link is activated, all readers are unsure and the person with a disability is not at any disadvantage.
>リンクを動作させるまで、すべての利用者が確信を持てないため、障害のある人が不利な立場に置かれることはない。

(障害者)
>Web Content Accessibility Guidelines (WCAG) 2.0 defines how to make Web content more accessible to people with disabilities. 
>Web Content Accessibility Guidelines (WCAG) 2.0 は、ウェブコンテンツを障害者にとってよりアクセシブルにする方法を定義している。
