### ISSUE TITLE
ARIA11 に 2.1 で削除された箇条書き項目が残っている

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1011]
WAICレビューにて、ARIA11について以下のご指摘をいただきました。

>箇条書きの「ウェブ文書とは対照的な、ウェブアプリケーションとして宣言された領域。～」の部分が元の翻訳にはありません。
>翻訳元：
>https://w3c.github.io/wcag/techniques/aria/ARIA11

該当箇所はDescriptionの本文中の箇条書きです。
Techniques for WCAG 2.0 には箇条書きが8項目あり、最後に application: で始まる項目があります。

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/ARIA11.html
>application: A region declared as a web application, as opposed to a web document. (略

しかしTechniques for WCAG 2.1では箇条書きが7項目に減っており、application: で始まる項目は削除されています。
https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11

この削除を反映する必要があるものと思われます。

**Comment by bakera** [comment]
該当箇所を単に削除で良いと思いますが、念のため2.0→2.1の変更点が他にもないか確認したいところ。

**Comment by momdo** [comment]
> 該当箇所を単に削除で良いと思いますが、念のため2.0→2.1の変更点が他にもないか確認したいところ。

気づいた範囲で修正するようにはしていますが、今回は気づけなかったと言うことですね、、。
