### ISSUE TITLE
ARIA12 事例1の文末のwill beが適切に訳されていない

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1012]
WAIC全体レビューで以下のご指摘をいただきました。

>https://dev.waic.jp/docs/WCAG21/Techniques/aria/ARIA12
>「事例 1: 単純な見出し」の以下文章の末尾、「かもしれない」ではなく「可能性がある」などの言い方が良いのではと思いました。※英語ではwil be
>『最終的なプレゼンテーションがどうなるかの知識なしで構築できるかもしれない。』

該当箇所は以下の通り

>This example demonstrates how to implement simple headings using role="heading" when retrofitting a legacy site where scripts depend on the existing element hierarchy or the level is unknown. For example, web content which is syndicated from various sources may be constructed without knowledge of what the final presentation will be.
>この例は、スクリプトが既存の要素の階層構造に依存する、又はレベルが不明であるレガシーなサイトを改装する際に、role="heading" を使用した簡単な見出しを実装する方法を示す。たとえば、さまざまなソースからシンジケートされたウェブコンテンツを、最終的なプレゼンテーションがどうなるかの知識なしで構築できるかもしれない。

**Comment by bakera** [comment]
ご指摘は文末のwill beについてですが、文中に may be があり、日本語の「かもしれない」はこちらから来ているように思います。

**Comment by momdo** [comment]
@bakera 

> ご指摘は文末のwill beについてですが、文中に may be があり、日本語の「かもしれない」はこちらから来ているように思います。

この指摘のとおりで、will beは「かもしれない」に対応していない以上、レビューコメントをした人に聞き返さないとなんともですね…。

**Comment by momdo** [comment]
特に返信がないようですので、wontfix扱いとしてクローズします。
