### ISSUE TITLE
「supersede」の揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#103]
「supersede」の訳が「置換する」「とって代わっている」で揺れています。

**Comment by bakera** [comment]
WCAG本体ではsupersedeが登場するのは一箇所だけですね。

>Other documents may supersede this document. 
>この文書が、他の文書によって置き換えられている場合もある。

本体に合わせるなら「置き換える」のような訳になるかと。

**Comment by ishimasar** [comment]
文字列検索するとWCAG2.1本体では、supersedeは2箇所登場しています。

1箇所目
Abstract内
>  The publication of WCAG 2.1 does not deprecate or supersede WCAG 2.0. While WCAG 2.0 remains a W3C Recommendation, the W3C advises the use of WCAG 2.1 to maximize future applicability of accessibility efforts.

2箇所目
Status of This Document内
> Other documents may supersede this document.

この両方の訳文を「置き換える」とし、表記揺れをなくす方針で作業したいと思います。

**Comment by momdo** [comment]
マージされたので閉じます
