### ISSUE TITLE
WCAG 2.1 解説書: 3.1.2 のうち一部参照すべき内容が足りていないところがある

### ISSUE THREAD

**Issue by cw-moriya** [waic/wcag21#1033]
[達成基準 3.1.2: 一部分の言語を理解する](https://waic.jp/docs/WCAG21/Understanding/language-of-parts.html)のうち、【失敗例】部分で「以下に〜」と記載されているのですが、参照されていませんでした。

[Understanding Success Criterion 3.1.2: Language of Parts](https://w3c.github.io/wcag/understanding/language-of-parts)では、[SL27: Using Language/Culture Properties as Exposed by Silverlight Applications and Assistive Technologies](https://w3c.github.io/wcag/techniques/silverlight/SL27)へのリンクが張られています。

ざっと見るとSufficient TechniquesやKey Termsも不足があるようです。ご確認お願いします！

**Comment by bakera** [comment]
GitHub上では修正されているので次回リリースすると治ると思います。

https://waic.github.io/wcag21/understanding/language-of-parts.html

**Comment by bakera** [comment]
そしてリリースしたので直ったのではないかと思います。
https://waic.jp/docs/WCAG21/Understanding/language-of-parts.html

**Comment by cw-moriya** [comment]
私の方でも直っていることを確認いたしました！
ご対応ありがとうございます。
