### ISSUE TITLE
「different」の揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#104]
「different（だけではないかもしれませんが）」の訳が「様々な」「さまざまな」で揺れています。

**Comment by bakera** [comment]
本体側では「様々」という表記で統一しているようです。
ひらがなの方が読みやすいような気もしますが、本体に揃えることを優先して「さまざま」→「様々」としたいと思います。

**Comment by momdo** [comment]
原文との対応は横に置くとして、WCAG 2.1本体での日本語では、「さまざま」→「様々」と一旦しましょう。
（解説書や達成方法集に反映する必要あり？）
