### ISSUE TITLE
G161 の h1 見出しが G160 と同じ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#1043]
```
<h1>コンテンツを利用するために理解が不可欠な情報、アイデア及びプロセスの手話バージョンを提供する</h1>
```

https://waic.github.io/wcag21/techniques/general/G160 : 正
https://waic.github.io/wcag21/techniques/general/G161 : 誤

正しくは G161 が「利用者がコンテンツを見つけるのを手助けするために検索機能を提供する」と思われます。

**Comment by momdo** [comment]
@SawadaStdDesign 
あら、見出しとタイトルがG160と同じですね…どうして。
Pull Requestお待ちしております…！
