### ISSUE TITLE
目次とイントロダクションへのリンクが原文への絶対リンクになっている

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1044]
Related #1043

例えばG160について、相対リンクではなく、絶対リンクになっているので、本家英語版に飛んでしまう

https://waic.github.io/wcag21/techniques/general/G160

- 目次： <https://w3c.github.io/wcag/techniques/#techniques>
- イントロダクション:  <https://w3c.github.io/wcag/techniques/#introduction>

**Comment by bakera** [comment]
G160以外も結構そうなっているようなので、一括で修正したいですね。
