### ISSUE TITLE
Understanding 1.4.13 での脱字

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#1045]
https://waic.github.io/wcag21/understanding/content-on-hover-or-focus.html

誤：コンテンツ見ることができるようになる。
正：コンテンツ**を**見ることができるようになる。

「を」が抜けているようです。

**Comment by momdo** [comment]
@SawadaStdDesign 
脱字を確認しました。

**Comment by bakera** [comment]
「メリット」のところですね。

>拡大してコンテンツを見ているロービジョンの利用者は、望ましい倍率を減らさなくてもより上手くホバー又はフォーカスしたコンテンツ見ることができるようになる。

「を」を追加で良いと思います。
