### ISSUE TITLE
ARIA19/ARIA20: regionの訳語が「リージョン」「領域」で揺れている

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1049]
ARIAには "region", "live region" などの概念が登場しますが、その訳語が「リージョン」「領域」で揺れているように思います。以下はいずれも見出しでは「リージョン」、文中では「領域」のようです。

https://waic.jp/docs/WCAG21/Techniques/aria/ARIA19
>エラーを特定するために、ARIA role=alert 又はライブリージョン (Live Regions) を使用する

>aria-live 属性は、エラーメッセージがライブ領域のコンテナに注入された際に、AT (スクリーンリーダーなど) による通知を可能にする。

https://waic.jp/docs/WCAG21/Techniques/aria/ARIA20
>ページのリージョンを特定するために region ロールを使用する

>領域は一般的なグループ化された要素であり、かつ利用者がどの領域にいるのかを伝えるための手段が必要になるため、領域に名前を付けることは重要である。領域には、aria-labelledby や aria-label、その他の手法を使用して名前を付けることができる。そうすることで、ページ上のコンテンツと情報の関係をより良く公開する助けとなる。

**Comment by momdo** [comment]
決めの問題ですね…どっちにしましょうか？

**Comment by bakera** [comment]
MDNは、live regionについては「ライブリージョン」で統一
https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

regionは、ロール名は「リージョン(region)」、文中のregionは「領域」としているようです。
https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/Roles/Region_role

**Comment by bakera** [comment]
ロール名を指す場合、"live region" と使う場合は固有名詞であるから「リージョン」とし、文中の region は普通名詞として「領域」と訳しているのではないかという説。

**Comment by bakera** [comment]
このような基本方針でどうか: 
専門用語の region は「リージョン」とする。ロール名を指す場合や "live region" と使う場合がこれに相当する。
文中の説明などで一般用語として使われている場合は「領域」とする。
どちらなのか判断がつかない場合はカタカナにしておく。
