### ISSUE TITLE
「user」の揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#105]
「user」の訳が「利用者」「ユーザー」「ユーザ」で揺れています。

**Comment by SawadaStdDesign** [comment]
ですね。

**Comment by caztcha** [comment]
[PR #167](https://github.com/waic/wcag21/pull/167) で対応しました。

ひととおり、「ユーザー」「ユーザ」は「利用者」に置換しています。（ユーザエージェント、ユーザインタフェースなど、複合語は除く。）
ただし、以下は、「ユーザ」という表記を残すのが妥当と考え、置換していません。

- エンドユーザ体験 (原文では end-user experiences。)
- ユーザー中心の設計方法論 (原文では user-centered design methodology。「ユーザ中心設計の方法論」に修正しました。)
