### ISSUE TITLE
「達成基準 1.4.8: 視覚的提示を理解する」でマークアップのミス

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1062]
> テ<a href="#dfn-blocks-of-text" >キストブロック</a>

という箇所があり、「テ」がはみ出している。

**Comment by bakera** [comment]
https://waic.jp/docs/WCAG21/Understanding/visual-presentation.html
の冒頭部分ですね。ご指摘ありがとうございます。
