### ISSUE TITLE
長いカタカナの語句

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#107]
「ウェブアクセシビリティガイダンス」「アクセシビリティガイドラインワーキンググループ」はやや長い印象を受けます。

**Comment by bakera** [comment]
本体側にはズバリの語句はないようです。
「アクセシビリティ サポーテッド」は空けているので、その伝で行くと空けた方がよさそうではあります。
しかし「アクセシビリティガイドラインワーキンググループ」は「アクセシビリティ ガイドラインワーキンググループ」と切ると変な感じなので、「アクセシビリティガイドライン ワーキンググループ」ですかね。

**Comment by momdo** [comment]
「アクセシビリティガイドライン ワーキンググループ」はこの方針でよいとして、
「ウェブアクセシビリティガイダンス」はどうしましょうか…

**Comment by caztcha** [comment]
「ガイダンス」というカナ語が読み手にとって馴染みがあれば、敢えて半角スペースで分けなくてもよいのでは、という気がします。
// 「**ウェブ**の**アクセシビリティガイダンス**」なのか「**ウェブアクセシビリティ**の**ガイダンス**」なのか「**ウェブ**の**アクセシビリティ**の**ガイダンス**」なのか、というツッコミはあるかもしれませんが、どちらにしても、解釈としては意味が変わらない気が。

// たとえば「ガイダンス」という語が馴染み薄いものだとして、「**アクセシビリティガイ**の**ダンス**」などと読み取れてしまう可能性があるのであれば、明示的に「アクセシビリティ ガイダンス」と分ける必要があるとは思いますが。

**Comment by momdo** [comment]
問題の「ウェブアクセシビリティガイダンス」ですが、これは[0.6 アクセシビリティガイドラインの後続バージョン](https://waic.github.io/wcag21/guidelines/#requirements-for-wcag-2-1) に2箇所出現するものですね。
見出しからして、アクセシビリティガイドラインがスペースなしですし、土屋さんが言われているように半角スペースでわけなくていい気がしてきました。

**Comment by bakera** [comment]
結論としては、
「アクセシビリティガイドライン ワーキンググループ」 (半角スペース入れる)
「ウェブアクセシビリティガイダンス」 (全部くっつける)
ということになりそうです。

**Comment by momdo** [comment]
mergeされたのでcloseします。
