### ISSUE TITLE
「This version:」「Latest published version:」など

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#109]
タイトルに続く「This version:」「Latest published version:」「Latest editor's draft:」「Implementation report:」「Previous version:」「Previous Recommendation:」「Editors:」「WCAG 2.0 Editors (until December 2008):」が訳出されていません。

**Comment by momdo** [comment]
この部分、HTMLソースを見ていただくとわかるかと思いますが、生のHTMLで記述されていないことが、英語のママになっている原因です。（どう対処するかはひとまず後で考えることになるかと。）

**Comment by bakera** [comment]
あれ、この箇所HTMLじゃないんでしたっけ?
ソース見た感じではふつうにHTMLに書いてあるように見えますが、ツールで生成されているものでしょうか。

**Comment by momdo** [comment]
[ReSpec](https://github.com/w3c/respec/wiki)を使ってこの部分をレンダリングしていると思います。おそらくjsonで埋め込まれているものを、fixup.jsでごにょごにょしている感じでしょうか。

**Comment by bakera** [comment]
今リポジトリに入っているindex.htmlではその部分は展開済みの普通のHTMLになっているように見えますが、これを直してもJSの処理で上書きされるということですかね?

**Comment by momdo** [comment]
> 今リポジトリに入っているindex.htmlではその部分は展開済みの普通のHTMLになっているように見えます
 
あ、確かにそうなってますね（本家の方は展開されていないものになっていますが、どこでこんなことに）

**Comment by momdo** [comment]
基本的にWCAG 2.0にならって翻訳を行う、という方針で。
