### ISSUE TITLE
「概要」の「技術」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#112]
「概要」の「イントロダクション並びに WCAG の技術及び教育資料については、」の「技術」はWCAG 2.0 では「達成方法」と訳していました。

**Comment by bakera** [comment]
ここは文脈的に「達成方法」でよさそうですね。

**Comment by momdo** [comment]
ではそのようにしましょう（ラベルを差し替えました）

**Comment by caztcha** [comment]
[PR #171](https://github.com/waic/wcag21/pull/171) で対応しました。
