### ISSUE TITLE
「概要」の「policies」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#113]
「概要」の「WCAG 2.0 への適合を要求する指針に対して、」や「ウェブアクセシビリティ指針を改良又は更新するときに、」において「policies」が「指針」と訳されていますが、「ウェブアクセシビリティ方針」という使われ方が定着してますし（？）、「方針」の方が適当ではないかと思います。

**Comment by bakera** [comment]
本体側では「指針」ゼロ「方針」3で「方針」に統一しているようです。
「方針」で良いように思います。

**Comment by momdo** [comment]
では「指針」にしましょう（ラベルを差し替えました）

**Comment by caztcha** [comment]
「指針」ではなく「方針」ですね。
[PR #172](https://github.com/waic/wcag21/pull/172) で対応しました。
