### ISSUE TITLE
「この文書のステータス」の「will continue to track」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#114]
「この文書のステータス」の「ワーキンググループは引き続きこれらの仕様を追跡する。」の「追跡する」は「will continue to track」ですので、「追跡するだろう」でしょうか。

**Comment by momdo** [comment]
https://github.com/waic/wcag21/issues/124#issuecomment-452687742 と同じような扱いですね。

**Comment by caztcha** [comment]
#124 (comment) に合わせて、「追跡することになる。」としようと思います。
