### ISSUE TITLE
「この文書のステータス」の「提出する」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#115]
「この文書のステータス」の「W3C WCAG GitHub リポジトリにイシューを提出する。」の「提出する」は「提出していただきたい」くらいの方が読みやすい様に感じます。
　同様に「電子メールを送付されたい。」も「送付していただきたい」くらいの方が読みやすい様に感じます。

**Comment by bakera** [comment]
>To comment, file an issue in the W3C WCAG GitHub repository. 
>コメントするためには、W3C WCAG GitHub リポジトリにイシューを提出する。

シンプルな命令形なので「してください」という訳で良いのかもしれません (want 的なニュアンスはないので)。原文 file ですが、日本語ではissueは「登録してください」という方が一般的かも?

>If filing issues in GitHub is not feasible, send email to public-agwg-comments@w3.org (comment archive).
>GitHub でイシューの提出が実現できない場合、public-agwg-comments@w3.org (comment archive) へ電子メールを送付されたい。

こちらも命令形なので「送付してください」でよさそうに思います。

**Comment by momdo** [comment]
「していただきたい」にすることにしましょう（ラベルを差し替えました）
