### ISSUE TITLE
「この文書のステータス」の「Please see」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#116]
「この文書のステータス」の「Please see」が「参照されたい」と訳されていますが、「参照していただきたい」くらいの方が読みやすい様に感じます。

**Comment by momdo** [comment]
#115 とセットで、命令文の翻訳を統一すべきでしょうね。

**Comment by momdo** [comment]
「幸いである」は重いような気がするので、澤田さんの当初の提案どおり「参照していただきたい」でよいのではないかと。
