### ISSUE TITLE
「1.3.4 表示の向き」の「表示の」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#117]
「目次」の「1.3.4 表示の向き」は「Orientation」だけですので「表示の」は不要ではないでしょうか。あった方が分かりやすいことは間違いないんですけれども。

**Comment by momdo** [comment]
本文にdisplay orientationとあるので、それを反映して補っているものと思います（ので、個人的には補ったほうがよいと思います）。

ところで話はそれますが、本当にdisplayを表示と訳してよいのでしょうか。（ハードウェアのディスプレイのことを実は指しているのでは？という気がしてきました。）

**Comment by SawadaStdDesign** [comment]
あった方が分かりやすいことは間違いないと感じています。ので、良いと思います。

**Comment by bakera** [comment]
これは達成基準の名称なので、原文に忠実であることを重視したいようにも思います。
(下の文章は解説なので読みやすさ重視で良い。)

**Comment by momdo** [comment]
当初の澤田さんのコメントの通りに、また、太田さんのコメントのとおり、原文に忠実にするならば、
「向き」にするということでしょうか。見出しだけに「方向」のような漢語の方がしっくりくるのかもしれません。

**Comment by bakera** [comment]
原文に忠実ではないという問題があるとはいえ、誤解を招くといったような悪影響は今のところ想定できなそうですので、「表示の向き」のままとしたいと思います。

**Comment by momdo** [comment]
変更なし、ということなのでCloseします。
