### ISSUE TITLE
達成基準 1.4.13の条件がandなのかorなのかわかりにくい

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1194]
達成基準 1.4.13では、「以下の条件を満たす」としたあとで3つの条件が挙げられています。

https://waic.jp/docs/WCAG21/Understanding/content-on-hover-or-focus.html
> ポインタホバー又はキーボードフォーカスを受け取ってから外すことで、追加コンテンツを表示させてから非表示にさせる場合は、以下の要件を満たす:

この日本語表現の場合、3つの条件を全て満たす必要があるのか、それともいずれか一つを満たせば良いのかがわかりにくいです。なお、原文は以下のように "are true" であり、全てを満たす必要があるとわかります。

https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html
>Where receiving and then removing pointer hover or keyboard focus triggers additional content to become visible and then hidden, the following are true:

**Comment by momdo** [comment]
日本語訳で「以下の要件を全て満たす」とするとか、ですかね…？

**Comment by caztcha** [comment]
PR #1306 で対応しました。
