### ISSUE TITLE
「目次」の「2.5.6 入力メカニズム非依存」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#120]
「目次」の「2.5.6 入力メカニズム非依存」は「入力メカニズムに依存しない」のではなく制限しないという話ではないかと解釈しますので、「非依存」ではないように感じます。
「併用可能な」あるいは「併用できる」などではいかがでしょうか？

**Comment by momdo** [comment]
Concurrent を非依存とするのは、ちょっと飛んでいるような気もしますので、要検討でしょうか？

**Comment by bakera** [comment]
ちなみに 2.2.3の "No Timing" が「タイミング非依存」と訳されています (全然違う言葉なので揃える必要はない)。

**Comment by momdo** [comment]
辞書的には、Concurrent「同時に起こる」なので、「同時入力メカニズム」ですかねえ…しっくりきませんが。
#233 の解説書の翻訳を待ってから考えるのもありかもしれません。

**Comment by bakera** [comment]
タイミング的に同時ということではなくて、ひとつの入力メカニズムを複数のモダリティで使用できるようにしましょういう話ですね。concurrentは「協働」に近いニュアンスのように思います。

**Comment by bakera** [comment]
「共用入力メカニズム」「共有入力メカニズム」などはどうでしょうか。

**Comment by momdo** [comment]
Lexicoの[https://www.lexico.com/en/definition/concurrent](concurrent)ですと、Agreeing or consistent.なんていうのも見えるので、「一貫した入力メカニズム」というのもありでしょうか…？

**Comment by momdo** [comment]
See also https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/concurrent-input-mechanisms.html

**Comment by tokimari** [comment]
10/24の議題に挙がったものの、結論出ず。
- concurrentの訳語が難しい
- 共同、共通、寛容、、？
- 非依存な入力メカニズム
- 並存入力メカニズム
- そもそも「入力メカニズム非依存」だと語弊がある
- 「モダリティを特定（限定）しない入力メカニズムを採用せよ」ということが言いたい
- 「モダリティ非依存入力メカニズム」が正しそう
- 複数モダリティに対応した入力メカニズム
- 汎用入力メカニズム
- コンカレント入力メカニズム（伝わらない？）

**Comment by momdo** [comment]
10月ミーティング：このissueは開いたままとし、引き続きよい案があれば考える。
意訳も含めて検討してはどうか。

**Comment by caztcha** [comment]
> 意訳も含めて検討してはどうか。

ジャストアイデアです。
「モダリティ非制限の入力メカニズム」
「モダリティ制限なしの入力メカニズム」

**Comment by momdo** [comment]
現在の解説書：達成基準 2.5.6: 入力メカニズム非依存を理解する  
https://waic.jp/docs/WCAG21/Understanding/concurrent-input-mechanisms.html

**Comment by bakera** [comment]
同時並行、などとするとコンテンツ側が複数の手段を提供する義務があるように読める。
ここではOS等が提供する複数モダリティを制限しないことを求めている ( does not restrict use of input modalities )。

コンカレント入力メカニズム?
制限なしの入力メカニズム?

→「入力メカニズムの共存」としてはどうか。

**Comment by momdo** [comment]
（このissueって何待ちだったんでしたっけ…今井さんのPR作成待ち？）
