### ISSUE TITLE
「目次」の「規定実装要件」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#121]
「目次」の「5.1」で「Interpreting Normative Requirements」が「規定実装要件」と訳されていますが、「Interpreting」に「実装」という意味はないように思いますので「規定要件の解説」もしくは「規定要件の解釈」などではいかがでしょうか？

**Comment by bakera** [comment]
Imprement との空目 (見間違い) による単純な誤訳でしょうね。

**Comment by bakera** [comment]
解説というより解釈の仕方を述べている内容ですので、「規定要件の解釈」とか「規定の要件を解釈する」とかですかね。

**Comment by momdo** [comment]
「規定要件の解釈」でとりあえずよいのではないでしょうか。
