### ISSUE TITLE
「0.1 WCAG 2 の背景」の「human evaluation」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#122]
「0.1 WCAG 2 の背景」の「human evaluation」が「人的評価」と訳されていますが、人を評価するような印象を受けますので、WCAG 2.0 での「人間による評価」で良いのではないでしょうか。

**Comment by caztcha** [comment]
[PR #176](https://github.com/waic/wcag21/pull/176) で対応しました。
