### ISSUE TITLE
「0.1 WCAG 2 の背景」の「challenges in reaching consensus」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#123]
「0.1 WCAG 2 の背景」の「challenges in reaching consensus」が「合意形成することへのチャレンジ」と訳されていますが、もう一方の「Significant challenges」は「重大な課題」と訳されていますので、「合意形成に向けての課題」ではどうでしょうか。

**Comment by momdo** [comment]
澤田さんの提案の「合意形成に向けての課題」でいきましょう。
