### ISSUE TITLE
用語集「キャプション」の翻訳の誤り

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1234]
2.1訳 https://waic.jp/docs/WCAG21/#dfn-captions
>キャプション (captions)
そのメディアのコンテンツを理解するのに必要な、会話及び会話でない音声情報に対する、同期した視覚、又はテキストによる代替。

2.0訳 https://waic.jp/docs/WCAG20/Overview.html#captionsdef
> キャプション (captions)
> そのメディアのコンテンツを理解するのに必要な、会話及び会話でない音声情報に対する、同期した視覚、及び／又はテキストによる代替。

2.1原文 https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-captions
>captions
synchronized visual and/or text alternative for both speech and non-speech audio information needed to understand the media content

「及び／又は」ではなくなっている…

**Comment by bakera** [comment]
及び／又はに修正する方向で。
ちなみにJISの規格票は「又は」でした…

**Comment by caztcha** [comment]
PR #1308 で対応しました。

**Comment by momdo** [comment]
See also: https://github.com/waic/wcag21/issues/98#issuecomment-475856125
