### ISSUE TITLE
「0.1 WCAG 2 の背景」の「WCAG の将来のバージョンで検討が継続される。」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#124]
「0.1 WCAG 2 の背景」の「WCAG の将来のバージョンで検討が継続される。」の「継続される」は「will carry on」ですので、「継続されるだろう」もしくは「続くだろう」でしょうか。

**Comment by momdo** [comment]
あるいは、「継続されることになる」というような訳もありでしょうか。

**Comment by SawadaStdDesign** [comment]
ありだと思います！

**Comment by caztcha** [comment]
[PR #177](https://github.com/waic/wcag21/pull/177) で対応しました。
