### ISSUE TITLE
解説書1.4.3:「サイズの大きなテキスト」の日本語注釈を px 変換の注記にも適用したい

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1240]
(前提)
「サイズの大きなテキスト」は https://waic.jp/docs/WCAG21/#dfn-large-scale で以下のように説明されている
>少なくとも 18 ポイント、又は 14 ポイントの太字。あるいは、中国語、日本語、及び韓国語 (CJK) のフォントは、それと同等の文字サイズ。

日本語の場合には基準が異なる。これについて、該当箇所の下部に以下のような訳注がある。

>日本語の全角文字の場合は、拡大教科書普及推進会議 第一次報告「第2章 拡大教科書の標準的な規格について」に基づき、22 ポイント又は 18 ポイントの太字を「同等な」サイズとみなすのが妥当である。

これに基づき、解説書の1.4.3の「十分な達成方法」では、「18 ポイント (日本語は 22 ポイント) 」のような表記をしている。

https://waic.jp/docs/WCAG21/Understanding/contrast-minimum.html
>状況 A: 太字でないテキストが 18 ポイント (日本語は 22 ポイント) 未満、太字のテキストが 14 ポイント (日本語は 18 ポイント) 未満の場合:

(今回の話)
ところで、解説書の1.4.3にはポイントをpxに変換する話も出ている。

https://waic.jp/docs/WCAG21/Understanding/contrast-minimum.html に以下の注記 (原注) がある。
>ポイント数と CSS ピクセルの比は 1pt = 1.333px であり、したがって 14pt と 18pt は約 18.5px と 24px に相当する。

ここでは日本語の文字について言及されていない。px だけに注目すると日本語の文字についての基準を見落とす可能性が高い。日本語では18ptと22ptが約24pxと29pxに相当するので、その旨を訳注として入れた方が良いのではないだろうか。

※ 2021-12-14 https://github.com/waic/wcag21/issues/1240#issuecomment-993096715 をふまえて数字を訂正しました

**Comment by momdo** [comment]
JIS X 8341-3:2016あるいはそれ以前の議論は自分は承知していませんが、

> 日本語の全角文字の場合は、拡大教科書普及推進会議 第一次報告「第2章 拡大教科書の標準的な規格について」に基づき、22 ポイント又は 18 ポイントの太字を「同等な」サイズとみなすのが妥当である。

本当に妥当なのか…？が個人的には疑ってかかっていますし、

> 状況 A: 太字でないテキストが 18 ポイント (日本語は 22 ポイント) 未満、太字のテキストが 14 ポイント (日本語は 18 ポイント) 未満の場合:

とあるものの

> https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#techniques

> Situation A: text is less than 18 point if not bold and less than 14 point if bold

とあるので、そもそも原文にないものをかっこ書きしているのは若干微妙だなと思いつつ、

> ここでは日本語の文字について言及されていない。px だけに注目すると日本語の文字についての基準を見落とす可能性が高い。日本語では18ptと22ptが約18.5pxと29pxに相当するので、その旨を訳注として入れた方が良いのではないだろうか。

というのはまあ、訳注としてはありかもしれません。ただし、巷のコントラストチェッカーはCJKの事情を無視して18pt/14pt (bold)で計測すると思うので、[第2章　拡大教科書の標準的な規格について](https://www.mext.go.jp/a_menu/shotou/kyoukasho/1282361.htm)を援用してもあんまり意味がないのでは？とも思います。

**Comment by bakera** [comment]
ちなみに該当の訳注は JIS X 8341-3:2016 の規格票にもしっかり入っています……。

>注 3) 日本語の全角文字の場合は，文部科学省 拡大教科書普及推進会議 第一次報告“第2 章 拡大教科書の標準的な規格について” (http://www.mext.go.jp/a_menu/shotou/kyoukasho/1282361.htm)に基づき，22 ポイン ト又は 18 ポイントの太字を“同等な”サイズとみなすのが妥当である。

**Comment by nagano-y-20181127** [comment]
お疲れ様です。 

> 日本語では**18pt**と22ptが約**18.5px**と29pxに相当するので」

1pt = 1.333pxとすると、以下かなと思いました。細かくてすいません。

「日本語では**18pt**と22ptが約**24px**と29pxに相当するので」

WCAGは文字のサイズを色のコントラスト比の閾値の判別の条件として論じていて、「第2 章 拡大教科書の標準的な規格について」は、ちょっと読んだだけだと、文字サイズのことを言ってるだけのように思いますが、「○ 文字、図・写真等、各要素の配色、明度、コントラストについては、原則として、原本教科書と同様とする。」とあるので、「色はそのままでも、文字を大きくしてね」って解釈はできるとすると、規格票の記述になるのかなと思いました。

カラーコントラストアナライザーなんかは、「日本語では**18pt**と22ptが約**24px**と29pxに相当する」ということが表示されていないので、見落としがちなのは、確かにと思いました。

で、どうするかということだと、啓蒙活動のときに、言うようにしたりするのも1つの手かなと思いました。

お手数をおかけします。

**Comment by caztcha** [comment]
解説書 1.4.3の「十分な達成方法」の「状況 A」「状況 B」のところで、原文にはない括弧書き:

> (日本語は 22 ポイント)
> (日本語は 18 ポイント)

...があるのは、私も (@momdo さんと同様に) 微妙だなと思いました。
解説書 1.4.3 の下のほうにある「重要な用語」に、WCAG 本文の用語集にあるのと同じ訳注が以下の通り記載されているので、上記「十分な達成方法」の括弧書きは無くてよいかもしれません。

> 日本語の全角文字の場合は、拡大教科書普及推進会議 第一次報告「第2章 拡大教科書の標準的な規格について」に基づき、22 ポイント又は 18 ポイントの太字を「同等な」サイズとみなすのが妥当である。

そのうえで、以下の訳注を続けて加える、という感じでいかがでしょうか？

> ポイント数と CSS ピクセルの比は 1 pt = 1.333 px であり、したがって 18 pt と 22 pt は約 24 px と 29 px に相当する。

**Comment by caztcha** [comment]
上記の通りでOK。改めてプルリク出します。

**Comment by caztcha** [comment]
PR #1331 で対応中です。
