### ISSUE TITLE
2.5.3（ほか）「成功基準」という訳語

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1246]
https://waic.jp/docs/WCAG21/Understanding/label-in-name.html
> 名前 (name) のラベルの成功基準の目的のために、"ラベル" はそのようなプログラム的な意味で使用されないが、単にコンポーネントに視覚的に近接したテキスト文字列を指す。

は、「達成基準」とした方がよさそうです。

原文:
https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html
> For the purposes of this Label in Name **Success Criterion**, "label" is not used in such a programmatic sense but is simply referring to a text string in close visual proximity to a component. 

この2.5.3以外だと、以下に「成功基準」があるようです。
https://waic.jp/docs/WCAG21/Understanding/pointer-gestures.html
https://waic.jp/docs/WCAG21/Techniques/general/G212.html

**Comment by caztcha** [comment]
PR #1310 で対応中です。

**Comment by caztcha** [comment]
PR #1310 マージされているので、クローズします。
