### ISSUE TITLE
2.5.3 &times;記号が間違っている

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1247]
https://waic.jp/docs/WCAG21/Understanding/label-in-name.html

「数式及び式」で

> 例えば、11x3 (小文字又は大文字のX)、11*3 (アスタリスク記号をもつ)、及び 11x3（&amp;times; 記号をもつ）

の最後のxは「×（&amp;times;）」でないと意味が通らないと思います。現在は「x（小文字のエックス）」になっています。

原文:
https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html

> For instance 11x3 (with a lower or upper case letter X), 11*3 (with the asterisk symbol), and 11×3 (with the &times; symbol)

こちらは正しい文字になっています。

**Comment by caztcha** [comment]
PR #1311 で対応中です。
