### ISSUE TITLE
0.1 WCAG 2 の背景」の英文へのリンク「メタデータ」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#125]
「0.1 WCAG 2 の背景」の英文へのリンク「学習障害、認知障害、ロービジョンなど障害を持つ人々のインクルージョンを向上するための補足的なガイダンス」「メタデータ」が和訳されています。

**Comment by momdo** [comment]
「メタデータ」のリンクは、0.2節ですね。

**Comment by SawadaStdDesign** [comment]
そそそ、そーでした。失礼いたしました！

**Comment by momdo** [comment]
0.1の指摘事項ですが、
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#background-on-wcag-2

> We encourage authors to refer to our supplemental guidance on **improving inclusion for people with disabilities, including learning and cognitive disabilities, people with low-vision, and more**.

この太字部にアンカーがあるのがそもそもおかしくって、supplemental guidanceにリンクがあればすんなりいくのでは、という気がしてきました。

**Comment by momdo** [comment]
https://github.com/w3c/wcag/issues/608
軽く提案してみましたが、別にどっちでもええやん、という返答。むう。

**Comment by momdo** [comment]
PRの議論より、ママとします。
