### ISSUE TITLE
短い／簡潔な代替テキスト

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1262]
https://github.com/waic/website_qa/issues/2 を見て思い出しましたけど、
short alternative textの訳が「短い」「簡潔な」で統一されていない、みたいな話があった記憶が

**Comment by caztcha** [comment]
英語の原文 "short text alternative" に対する、「**短い**テキストによる代替」「**簡潔な**テキストによる代替」の表記ゆれ、ですかね。

WCAG 本文の Glossary の text alternative のセクションにある「short text alternative」に対する訳語が、「**短い**テキストによる代替」になっている (JIS X8341-3:2016 の規格票でも、同様に「**短い**テキストによる代替」になっている) 
https://www.w3.org/TR/WCAG21/#dfn-text-alternative
https://waic.jp/docs/WCAG21/#dfn-text-alternative
...ということを踏まえると、「短い」で統一ですかね...。(達成方法集 G94 のタイトルも含めて、影響範囲が大きいですが。)

**Comment by caztcha** [comment]
(すみません、コメント投稿時に間違えて Close にするボタンを押してしまったので Reopen しました。)

**Comment by caztcha** [comment]
「短い」にて統一します。

**Comment by caztcha** [comment]
PR #1330 で対応中です。
