### ISSUE TITLE
「0.4 WCAG 2.1 の要件」の「また、ワーキンググループがあまり形式的ではない〜」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#127]
「0.4 WCAG 2.1 の要件」の「また、ワーキンググループがあまり形式的でない受入基準セットを用いたことで、達成基準のスタイルと品質が WCAG 2.0 のそれと似通ったものとなっている。」が理解しにくい印象を受けます。
「ワーキンググループはまた、達成基準のスタイルや品質が  WCAG 2.0 のものと類似していることを確保するために、あまり正式ではない一連の適合（合格？）基準を達成基準に使用した。」ではいかがでしょうか？

**Comment by momdo** [comment]
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#requirements-for-wcag-2-1
> The Working Group also used a less formal set of acceptance criteria for success criteria, to help ensure success criteria are similar in style and quality to those in WCAG 2.0. 

原文はこの部分になりますが… acceptance criteriaをどう取るものか、ちょっと難しいところですね。

**Comment by bakera** [comment]
acceptance criteriaは達成基準の合否基準ではないか、という説が浮上しました。
たぶん、「もっと形式的に合否を決められるべきだ」という議論があったが、そこはあきらめて2.0とそろえた、という話をしているのではないかと。

**Comment by momdo** [comment]
太田さん案で前半はよいと思いますが、

> 達成基準に対し、あまり形式的ではない一連の合否基準を採用した。

ちょっと違和感がある感じがしますね…。まず、ここの[formal](https://ejje.weblio.jp/content/formal) は堅苦しいと取った方がよいのでは？と。acceptance criteriaも合否基準と取るのは、そういう基準がWCAG 2.1に存在するようにも取れるので、例えば「合格の基準」のように、漢語だけにはしないほうがよいのかな、と。

**Comment by bakera** [comment]
"acceptance criteria" は「受け入れ基準」でどうか。

>達成基準に対し、あまり形式的ではない一連の受け入れ基準を採用した。
