### ISSUE TITLE
2.1.4 文字キーのショートカットにおける脱字等

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1273]
https://waic.jp/docs/WCAG21/Understanding/character-key-shortcuts.html
「2.1.4 文字キーのショートカット」でいくつか気になるところがありました。

> このコンポーネント一つ以上の文字キー

「このコンポーネントは一つ以上の文字キー」ではないでしょうか。

> 元に戻ならば

「元に戻すならば」だとおもいます。

> メッセージ又ははスレッド

「は」が多いようです。

> 単一キーのショートカットを無効することができ

「単一キーのショートカットを無効にすることができ」くらいのほうが読みやすいように思いますが、好みかもしれません。

「再割り当て」「再マップ」は表記揺れかと思います。

「失敗例」の「F99: Failure of Success Criterion 2.1.4 due to implementing character key shortcuts that cannot be turned off or remapped」は、「F99: 達成基準 2.1.4 の失敗例－停止又は再割り当て不可能な文字キーショートカットが実装されている」が翻訳されていますし、日本語になっているとよいかと思いました。

ついでに「[F99: 達成基準 2.1.4 の失敗例－停止又は再割り当て不可能な文字キーショートカットが実装されている](https://waic.jp/docs/WCAG21/Techniques/failures/F99)」では、「装飾キー（modification keys）」「修飾キー（modifier and control keys）」の表記揺れがあるようでした。

**Comment by caztcha** [comment]
表記揺れのご指摘については、以下の通りでいかがでしょうか？

「再割り当て」「再マップ」の表記揺れについては、「再割り当て」で統一する。（達成基準本文でも、英語の「Remap」に対して「再割り当て」という訳語が当てられているため。）

「修飾キー」「装飾キー」の表記ゆれについては、「修飾キー」で統一する。（原文で用いられている「modifier」は、「修飾語」という意味で用いられることもあるため。）

**Comment by caztcha** [comment]
「再割り当て」「修飾キー」にて統一します。

**Comment by caztcha** [comment]
PR #1329 で対応中です。
