### ISSUE TITLE
「0.4 WCAG 2.1 の要件」の「dot-release」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#128]
「0.4 WCAG 2.1 の要件」の「dot-release」が「ドットリリース」という訳でいいのか（一般的な表現なのか）どうか、アイデアは持ち合わせていませんが、やや違和感があります。

**Comment by momdo** [comment]
英語版Wikipediaだと
https://en.wikipedia.org/wiki/Point_release
> A point release (also a dot release) is a minor release of a software project,

という感じですが、ポイントリリースやマイナーリリースとしたところで、印象が変化するかというと、大差ない気もします。

**Comment by SawadaStdDesign** [comment]
「ドットリリースが一般的な表現なのである！」と押し切っていただければ、それはそれで「勉強になりました」という感じなのですが、挙げていただいた候補ですと「マイナーリリース」の方が馴染める感じはあります。

**Comment by bakera** [comment]
ざっと見た感じ、日本語では「ドットリリース」という表現はあまり使われていないように思われます。

>ポイントリリースやマイナーリリースとしたところで、印象が変化するかというと、大差ない気もします。

これはそうかも。達成基準などの内容に関わる重要なポイントではないので、いったんこのままにしておくのもアリな気がしました。

**Comment by momdo** [comment]
何かコメントありますか？ @caztcha @MasaoYOMODA

**Comment by caztcha** [comment]
個人的には「マイナーアップデート」だとしっくりするのですが、意訳しすぎですかね。
悩ましいですが、上記の太田さんコメント (達成基準などの内容に関わる重要なポイントではないので、いったんこのままにしておくのもアリ) に賛同します。

**Comment by momdo** [comment]
リリースをアップデートにするのは若干飛躍する印象はありますね（ありと言えばありなのですが）

ちなみに、[0.6節](https://waic.github.io/wcag21/guidelines/#later-versions-of-accessibility-guidelines)にもドットリリースが出現してますね。現在の訳と原文をあわせて書いてみると

> WCAG 2.1 と並行して、アクセシビリティガイドラインワーキンググループは、アクセシビリティガイドラインの別の主要バージョンを開発している。この作業の結果は、WCAG 2 のドットリリースに現実的であるよりも、ウェブアクセシビリティガイダンスのより実質的な再構築になると期待されている。

> In parallel with WCAG 2.1, the Accessibility Guidelines Working Group is developing another major version of accessibility guidelines. The result of this work is expected to be a more substantial restructuring of web accessibility guidance than would be realistic for dot-releases of WCAG 2. 

dot-releasesの1つ前の文にanother major versionが見えているので、対比させるイメージを持ちつつ、例えば土屋さん提案訳を当てはめてみると：

WCAG 2.1 と並行して、アクセシビリティガイドラインワーキンググループは、アクセシビリティガイドラインの別の**メジャー**バージョンを開発している。この作業の結果は、WCAG 2 の**マイナーアップデート**に現実的であるよりも、ウェブアクセシビリティガイダンスのより実質的な再構築になると期待されている。

こんな感じでしょうか。

[0.4節](https://waic.github.io/wcag21/guidelines/#requirements-for-wcag-2-1)のほうも土屋さん提案訳をあてはめて、一通り書いてみると：

> これらの要件は、WCAG 2.1に含めることができるものを制限している。この制限は、WCAG 2 のドットリリースの性質を保持するために重要である。

> These requirements constrained what could be included in WCAG 2.1. This constraint was important to preserve its nature as a dot-release of WCAG 2.

これらの要件は、WCAG 2.1に含めることができるものを制限している。この制限は、WCAG 2 の**マイナーアップデート**の性質を保持するために重要である。

（まあ、過去形を現在形の訳としていいのかという疑問もあったりしますが）こんな感じです。

**Comment by caztcha** [comment]
@momdo ありがとうございます！

0.6節に関して

> dot-releasesの1つ前の文にanother major versionが見えているので、対比させるイメージを持ちつつ

...とのこと、私も同じことを考えていました。ですので、上記のもんどさんの訳文案は、個人的には、腹落ちします。

**Comment by momdo** [comment]
@SawadaStdDesign 今月のミーティングでママということになったみたい（私は不参加）ですが、訳注は必要そうでしょうか？

**Comment by SawadaStdDesign** [comment]
この半年間で「ドットリリース」が飛躍的に普及した感は受けておりませんので、訳注を付ける余地があるのであれば、その方が読み手の「？」を減らすことができるのではないかと思いますー


...「メジャーバージョン」がアリなら「マイナーバージョンアップ」ではいかが？（しつこい

**Comment by ishimasar** [comment]
ミーティングでは「ドットリリース」のニュアンスが焦点となり、マイナーバージョンアップと若干異なる気がするという意見が挙がりました。

https://en.wikipedia.org/wiki/Point_release
たとえば7.0から7.1、または2.4.9から2.4.10にように、小数点以下の数値が増加する「ポイント(.)」の後の数値の増加により「point release」または「dot release」と呼ばれるとのことです。

原文の意味合いを残しつつ訳すのであれば、ドットリリース（マイナーバージョンアップのこと）など、訳注かカッコ書き補足(可能なら)するのが適当かと思いました。

いきなり議論参加し、恐縮ですがよろしくお願いします。

**Comment by momdo** [comment]
dot releaseを譲ってマイナーリリースと訳すくらいですかね。マイナーアップデートはやはり飛躍しすぎな印象です。

**Comment by bakera** [comment]
訳注については、入れてもいいのですが、今のスタイルでは、訳注を入れると段落を分けて「訳注: 」という囲み記事が入ることになるのでかなり大げさな感じになります。ここは達成基準の内容を説明しているわけでもなく、ここでそこまで厳密な用語定義が必要なのか、という議論がありました。

いったんママとさせていただいて、わかりにくいという意見が多くなりそうなら対応を検討するという方向にしたいと思います。

**Comment by momdo** [comment]
ママという話なので、一旦閉じます。
