### ISSUE TITLE
「0.5 WCAG 2.0 との比較」の「clarity and impact」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#129]
「0.5 WCAG 2.0 との比較」の「clarity and impact」が「明快さとインパクト」と訳されていますが、やや違和感がありますので「明確さと影響度」ではいかがでしょうか？

**Comment by momdo** [comment]
影響度というのは、手持ちの辞書には見えないですね…影響（力）、あるいは効果というのは見えますが。

**Comment by SawadaStdDesign** [comment]
度が過ぎましたね。
英辞郎も「影響」だと申しております。

**Comment by bakera** [comment]
全体がこうなっていますが、

>WCAG 2.0 から継承された構造的な要件、勧告案の明快さとインパクト、および勧告策定までのタイムラインが、このバージョンに含まれる最終的な達成基準のセットにつながっている。
>Structural requirements inherited from WCAG 2.0, clarity and impact of proposals, and timeline led to the final set of success criteria included in this version. 

この日本語は正直よくわからない文章だなぁという印象で、全体を見直す必要があるかもしれません。

文脈的に、たくさん提案された中から収録する達成基準を選んだ基準の話をしているはずですから、ここの "proposal" は勧告案ではなく、前の文の Many ways to meet these needs were proposed を受けているものかと思います。単に「提案」とするべきものでしょう。
直訳するとこんな感じで、

>WCAG 2.0 から継承された構造的な要件、提案の明快さと影響、およびタイムラインが、このバージョンに含まれる最終的な達成基準のセットにつながった。

少し補って意訳してもよければこんな感じでしょうか。

>WCAG 2.0 の構造を引き継ぐという要件、提案の明快さと影響、およびタイムラインを考慮して、このバージョンに含まれる最終的な達成基準を選定した。

**Comment by momdo** [comment]
辞書の意味を並び立てると、あるいはこんな感じでしょうか。

WCAG 2.0 から継承された構造上の要件、提案の明確さ及び影響、並びに進行計画が、このバージョンに含まれる最終的な一式の達成基準をもたらした。

**Comment by momdo** [comment]
いろいろと私と太田さんから案が出ていますが、 @honoka-h さんに選んでいただく感じで…（酷）
