### ISSUE TITLE
達成基準 2.5.2 を理解する: 「ダウインイベント」→「ダウンイベント」の誤字

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1298]
(問い合わせフォームより)
https://waic.jp/docs/WCAG21/Understanding/pointer-cancellation.html
項目【アップイベントで反転する】内の１行目に、『別のインタラクションでは、ダウインイベントは〜』と記載されています。正しくは"ダウンイベント"かと思いましたので、ご報告いたします。

**Comment by caztcha** [comment]
PR #1312 で対応中です。
