### ISSUE TITLE
達成基準 3.3.1: エラーの特定を理解する / アンカーの範囲がおかしい

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1300]
(問合せフォームより)
https://waic.jp/docs/WCAG21/Understanding/error-identification.html
■ テキストリンクの範囲指定にズレがありました
冒頭の注記（緑背景部分）に、達成基準3.3.3へのリンクが貼られていますが、そのリンク範囲が「成基準 3.3.3（エラー修正の提案）」となっており「達」が漏れていました。軽微ですが気になってしまったので、ご報告いたします。

**Comment by caztcha** [comment]
PR #1313 で対応中です。
