### ISSUE TITLE
達成方法集の目次で、Generalのリンクが英語のままのものがある

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1304]
現時点で日本語化していないG175～G178以外は、リンクテキストが日本語になっているはずだが、
G56などが英語のまま。
https://waic.github.io/wcag21/techniques/

**Comment by caztcha** [comment]
対象は以下のとおり。

- G53 リンクテキストとそれが含まれている文中のテキストとを組み合わせて、リンクの目的を特定する
- G56 非発話音が発話音声コンテンツより少なくとも 20 デシベル低くなるように、音声ファイルを編集する
- G165 視認性の高いデフォルトのフォーカスインジケータが引き継がれるように、プラットフォームデフォルトのフォーカスインジケータを使用する
- G166 重要な映像コンテンツを説明する音声を提供する
- G167 テキストフィールドの目的をラベル付けするために隣接するボタンを用いる
- G168 選択されたアクションを続行するために確認を求める
- G169 テキストを左寄せ又は右寄せにする

**Comment by caztcha** [comment]
PR #1315 で対応中です。
