### ISSUE TITLE
「0.5 WCAG 2.0 との比較」の「注意されたい。」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#131]
「0.5 WCAG 2.0 との比較」の「注意されたい。」は「注意していただきたい」くらいの方が読みやすい様に感じます。

**Comment by SawadaStdDesign** [comment]
良いと思います！

**Comment by caztcha** [comment]
[PR #178](https://github.com/waic/wcag21/pull/178) で対応しました。
