### ISSUE TITLE
「0.5.1 WCAG 2.1 の新しい特長」の「formal obligations」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#134]
「0.5.1 WCAG 2.1 の新しい特長」の「formal obligations」が「法的義務」と訳されていますが、法的（legal）ではないと思いますので「正式な義務」ではいかがでしょうか？

**Comment by momdo** [comment]
https://eowf.alc.co.jp/search?q=formal+obligation では「公的義務」としているようですね。

**Comment by SawadaStdDesign** [comment]
良いと思います！
