### ISSUE TITLE
「0.5.1 WCAG 2.1 の新しい特長」の「これらの達成基準の多くは〜」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#135]
「0.5.1 WCAG 2.1 の新しい特長」の「これらの達成基準の多くは用語集にも追加された達成基準の規定要件の一部となっている新しい用語に言及している。」が理解しにくい印象を受けます。
「これらの達成基準の多くは、用語集にも追加されている新しい用語を参照しており、達成基準の規定要件の一部となっている。」ではいかがでしょうか？

**Comment by bakera** [comment]
ご提案の文はおそらく、

これらの達成基準の多くは、用語集にも追加されている新しい用語を参照しており、(その用語は) 達成基準の規定要件の一部となっている。

という意図だと思いますが、上記カッコ内の補足がないと「達成基準の多くは……規定要件の一部になっている」と言っているようにも読めてしまい、ちょっと誤解を招く可能性がありそうに思いました。

**Comment by bakera** [comment]
ちなみに原文これです。

>Many of these success criteria reference new terms that have also been added to the glossary and form part of the normative requirements of the success criteria.

(原文が A that B and C という形で and の後ろがどこにかかるのかわかりにくい悪文だと思いますが、末尾の  the success criteria と the がついているため、success criteria が自身の form part of ... ということはあり得ず、new terms that form... という解釈で良いはずです。)

**Comment by bakera** [comment]
単純に「その用語は」を補ったらダメですかね? (補いすぎ?)

**Comment by momdo** [comment]
「その用語は」を補った方が見通しがよいですね。

formも「～となる」で誤りではないですが、手元の辞書には「(文などを)構成する」とあるので、これを採用してみるのもよいかもしれません。

その用語は達成基準の規定要件の一部を構成している。

**Comment by momdo** [comment]
ただまあ、太田さんも悪文と言われているように、修飾関係がこんがらがってるんですよね…。

**Comment by momdo** [comment]
それか2文に切るか、ですかね。

これらの達成基準の多くは、新しい用語を参照している。その新しい用語はまた、用語集に追加されており、かつ達成基準の規定要件の一部を構成している。

**Comment by bakera** [comment]
もんどさんの2文に切る案を採用で。

**Comment by momdo** [comment]
2月ミーティングにより、2文に切る案を採用。

**Comment by caztcha** [comment]
コミット #7339d98 にて、2文に切る案を反映してみました。
