### ISSUE TITLE
「0.5.3 WCAG 2.1 への適合」の「any policies that reference WCAG 2.0」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#137]
「0.5.3 WCAG 2.1 への適合」の「any policies that reference WCAG 2.0」が「WCAG 2.0 を参照する方針や政策」と訳されていますが、政策は出てきませんので「WCAG 2.0 を参照する方針」ではいかがでしょうか？

**Comment by momdo** [comment]
コメントには賛成しますが、それはさておき、

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#conformance-to-wcag-2-1
> It is intended that sites that conform to WCAG 2.1 also conform to WCAG 2.0, which means they meet the requirements of any policies that reference WCAG 2.0, while also better meeting the needs of users on the current Web.

現行訳は
> WCAG 2.1 に適合するサイトは WCAG 2.0 にも適合することになる。つまり、 WCAG 2.0 を参照する方針や政策の要件を満たし、ウェブ上の利用者のニーズをよりよく満たすことができる。

「つまり」とするのがよくわからないのですが…。あとwhileも訳出できていないような。（1つ前の文が体言止めになっているのも気になりますね。）

**Comment by bakera** [comment]
which means を「つまり」と訳しているのは、そこまで変ではないように思います。
あと気になった点として、

- intend をもうちょっとしっかり訳したほうがいいかも (たまたま適合するのではなく、意図してそのようにしたというニュアンス)。
- the current Web は「現在のWeb」という意味でしょう (2008年当時のWebではないということ)。

こんな感じ??

>WCAG 2.1 に適合するサイトは、WCAG 2.0 にも適合するようにしている。すなわち、WCAG 2.0 が参照する全ての方針の要求を満たした上で、さらに、現在のウェブを使う利用者のニーズをよりよく満たすことができるということになる。

**Comment by momdo** [comment]
> which means を「つまり」と訳しているのは、そこまで変ではないように思います。

これは私の勉強不足でした。 https://eowf.alc.co.jp/search?q=which+means
あるいはこんな感じでしょうか。

WCAG 2.1 に適合するサイトは WCAG 2.0 にも適合することを目的としている。つまり、 WCAG 2.0 を参照する全ての方針の要求を満たしつつ、現在のウェブについて利用者のニーズもより多く満たすことができる。

**Comment by momdo** [comment]
これも @honoka-h さんに選んでいただく感じで（酷）
