### ISSUE TITLE
解説書 2.5.4 括弧の位置がおかしい?

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1373]
問い合わせフォームより: 
https://waic.jp/docs/WCAG21/Understanding/motion-actuation.html

>>この達成基準の目的は、(カメラのようなセンサーがジェスチャを取得して解釈できるように) デバイスを動かすこと (例えば、振ることや傾けること) によって、又はデバイスに向かってジェスチャをすることによって

>となっていますが、1つ目の()の位置がおかしいため文章のどこにかかっている内容なのかわかりませんでした。
>この達成基準の目的は、デバイスを動かすこと (例えば、振ることや傾けること) によって、又はデバイスに向かってジェスチャをする(カメラのようなセンサーがジェスチャを取得して解釈できるようにする)ことによって
>が正しいかと思います。

**Comment by bakera** [comment]
該当箇所:

>この達成基準の目的は、(カメラのようなセンサーがジェスチャを取得して解釈できるように) デバイスを動かすこと (例えば、振ることや傾けること) によって、又はデバイスに向かってジェスチャをすることによって引き起こされる機能を確実にすることである。動きが機能にとって不可欠であるか、又は動きもしくはジェスチャを使用しないことが活動を無効にしない限り、より従来型のユーザインターフェースコンポーネントによって操作される。

原文:
>The intent of this success criterion is to ensure that functions triggered by moving a device (for example, shaking or tilting) or by gesturing towards the device (so that sensors like a camera can pick up and interpret the gesturing), can also be operated by more conventional user interface components.

**Comment by momdo** [comment]
> 1つ目の()の位置がおかしい

なるほど確かに…

**Comment by bakera** [comment]
語順を変えて訳されていて、日本語の最初のカッコは原文の2つめのカッコに対応しているもの。
ご指摘のように修正すれば良いものと思われる。
