### ISSUE TITLE
用語集：一般閃光閾値及び赤色閃光閾値の翻訳が揃っていない

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1390]
少なくとも、以下の箇所の原文は同じであるにもかかわらず、翻訳は異なる訳出となっている。（JIS X 8341-3:2016も同様）

> 赤色閃光とは、<mark>彩度の高い赤色を含んだ交互の遷移<mark>のことである。

> A red flash is defined as any <mark>pair of opposing transitions involving a saturated red</mark>

注記：

> 「彩度の高い赤色を含む相反する遷移の組合せ」の現時点での定義は

> The current working definition in the field for "pair of opposing transitions involving a saturated red" is

- https://waic.jp/docs/WCAG21/#dfn-general-flash-and-red-flash-thresholds
- https://www.w3.org/TR/WCAG21/#dfn-general-flash-and-red-flash-thresholds

**Comment by bakera** [comment]
ここでの opposing は「赤とは正反対の色」というようなニュアンスのはずで、どちらもやや怪しいかも
とりあえず「彩度の高い赤色を含む相反する遷移の組合せ」のほうが近い気がするのでそちらに揃えてはどうか。
