### ISSUE TITLE
解説書：達成基準 2.3.1が更新されている

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1391]
原文にある以下の注記が存在しない…と思ったら、どうやらそれ以外も更新されている模様

> The specification cannot account for the actual viewing distance that a person chooses. Users that are closer to their screens than the idealized viewing distance will be affected by flashing areas that normatively pass. The same problem applies to users who rely on zoom or screen magnification. Conversely, users who are further away from the screen than the idealized distance should be able to tolerate flashing areas that are larger than the threshold.

- https://waic.jp/docs/WCAG21/Understanding/three-flashes-or-below-threshold.html
- https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold

参考2.0：
- https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html
- https://waic.jp/docs/UNDERSTANDING-WCAG20/seizure-does-not-violate.html

**Comment by bakera** [comment]
ここだけ直しても良いが、表紙に表記されている日付とずれるのは気になる。
(現在、原文の表紙の日付は2022年9月2日、日本語訳の表紙は2020年12月2日)

とはいえ翻訳の各ページの末尾にも訳注で日付の表記があるので、ここだけ最新に追従して末尾の訳注を変更すれば問題ない。

**Comment by momdo** [comment]
SC 2.3.1
- 原文
  - https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold
- 差分
  - https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-4c4e05e62e35d7a327fc58f79c29657dc0c13a75a2c6aeb210df062e7ab3c2e6
