### ISSUE TITLE
解説書：達成基準 2.4.の意図の第1段落について

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1397]
https://waic.jp/docs/WCAG21/Understanding/focus-order.html

> 例えば、テーブルのある行又は列にある構成要素内を一度に移動する際には、行を移動する際も列を移動する際もコンテンツにおける関係性を反映した順序になる。

https://www.w3.org/WAI/WCAG21/Understanding/focus-order

> For example, moving through components in a table one row at a time or one column at a time both reflect the logical relationships in the content.

例えば、テーブル内のコンポーネントを1行ずつ、または1列ずつ移動するとき、どちらもコンテンツの論理的な関係を反映する。

というのが素直な訳かと思うがどうか。

**Comment by caztcha** [comment]
@momdo さん訳の案に賛成です。
PR #1404 で対応します。

**Comment by bakera** [comment]
関連して一つ前の文を見直したいです。

>There may be different orders that reflect logical relationships in the content.

>コンテンツの論理的な関係性を反映した異なる順序になることもある。

これは英文としては要するに there are (different) orders と言っていて、「コンテンツの論理的な関係性を反映した順序が複数存在することもある」というくらいかなと思います。

**Comment by bakera** [comment]
問題の文については、
「コンポーネントを移動する」
と読めるのですが、moving through components なので「コンポーネント群の中を移動する」という感じですね。
こうでしょうか?

例えば、テーブル内のコンポーネント群の中を1行ずつ、または1列ずつ移動することは、どちらもコンテンツの論理的な関係を反映している。
