### ISSUE TITLE
解説書・達成方法集：PEATのリンクが切れている

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1398]
以下の解説書、達成方法集でリンク切れが起きている：

- https://waic.jp/docs/WCAG21/Techniques/general/G15
- https://waic.jp/docs/WCAG21/Techniques/general/G19
- https://waic.jp/docs/WCAG21/Techniques/general/G176
- https://waic.jp/docs/WCAG21/Understanding/three-flashes-or-below-threshold
- https://waic.jp/docs/WCAG21/Understanding/three-flashes.html

http://trace.wisc.edu/peat/
↓
https://trace.umd.edu/peat/

**Comment by caztcha** [comment]
PR #1400 で対応中です。
