### ISSUE TITLE
用語集「役割 (role)」について

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1407]
https://waic.jp/docs/WCAG21/#dfn-role

> 役割 (role)
> ウェブコンテンツに含まれるコンポーネントの機能を、ソフトウェアが識別するために用いることができるテキストや数字。
> 
> 画像の機能が、ハイパーリンク、コマンドボタン、又はチェックボックスのどれなのかを示している数字。

微妙な翻訳ではないだろうか…？

https://www.w3.org/TR/WCAG21/#dfn-role

> role
> text or number by which software can identify the function of a component within Web content
> 
> A number that indicates whether an image functions as a hyperlink, command button, or check box.

以下の訳はどうか…？

ソフトウェアがウェブコンテンツ内のコンポーネントの機能の識別を可能にするためのテキスト又は番号。

画像がハイパーリンク、コマンドボタン、又はチェックボックスとしての機能を果たすかどうかを示す番号。

**Comment by caztcha** [comment]
もんどさん訳で問題ないと思いますので、プルリク出します。

**Comment by caztcha** [comment]
PR #1409 で対応中です。
