### ISSUE TITLE
「達成基準 1.4.13 ホバー又はフォーカスで表示されるコンテンツ」の英文へのリンク「title 属性」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#141]
「達成基準 1.4.13 ホバー又はフォーカスで表示されるコンテンツ」の英文へのリンク「title 属性」が和訳されています。

**Comment by momdo** [comment]
難しいところですが、翻訳されている方が読みやすい気もします。

**Comment by SawadaStdDesign** [comment]
当方もそう思うのですが...
柔軟性のない堅物なコメントだと思っていただければ。
判断はお任せいたします。

**Comment by bakera** [comment]
リンク先文書の英文タイトルは訳さないというルールなのですが、これは微妙なところですね。
このテキスト (title attribute) はリンク先の文書のタイトル (HTML 5.2: 3. Semantics, structure, and APIs of HTML documents) とは異なりますし、セクションのタイトル (3.2.5.1. The title attribute) とも完全には一致していません。よって、このテキストは文書名ではなく、一般的な用語であり、それにたまたま文中リンクが設定されたものと考えられます。

ですので、これは訳しておいて良いと思います。ママにしたいと思います。

**Comment by momdo** [comment]
ママとすると言うことなので、Closeします。
