### ISSUE TITLE
解説書 3.3.6 原文にない言葉が補われている

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1410]
https://waic.jp/docs/WCAG21/Understanding/error-prevention-all.html の「意図」の2段落目に以下の文があります。

>障害のある利用者は、ミスをしてしまう可能性が高く、フォームでのエラーに気づく又は修正するのにも困難を伴うことが多い。

「フォームでのエラー」と言っていますが、対応する原文はこれです。

https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-all.html
>Users with disabilities may be more likely to make mistakes and may have more difficulty detecting or recovering from mistakes. 

原文には form も error もありません。「フォームでのエラー」に対応する箇所は mistakes であり、単に「ミス」とすべきもののように思いますがどうでしょうか。また、more difficulty の more のニュアンスがなくなっているように思います。

たとえばこんな感じ?

障害のある利用者はミスをしてしまう可能性が高く、ミスに気づいたり、修正したりすることも、より困難であることが多い。

**Comment by momdo** [comment]
> 原文には form も error もありません。「フォームでのエラー」に対応する箇所は mistakes であり、単に「ミス」とすべきもののように思いますがどうでしょうか。

なるほど確かに。

> また、more difficulty の more のニュアンスがなくなっているように思います。

それでいくと、may be more likely toのmoreもニュアンスを出す必要がありそうな？

**Comment by bakera** [comment]
最初訳す時fromとformを見間違えていた説

**Comment by bakera** [comment]
may be more likely to は「かもしれない」的に訳す?

障害のある利用者はミスをしてしまう可能性が高く、ミスに気づいたり、修正したりすることも、より困難かもしれない。

**Comment by caztcha** [comment]
PR #1420 で対応中です。
