### ISSUE TITLE
ガイドライン 3.1：「を」が2回出現する

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1411]
https://waic.jp/docs/WCAG21/Understanding/readable.html

> このガイドラインの意図は、利用者及び支援技術がテキストのコンテンツを読み取りを可能にし、理解するために必要な情報が利用可能であることを保証することである。

「を読み取りを可能にし」と、文が壊れているので修正する必要がある。

https://www.w3.org/WAI/WCAG21/Understanding/readable

> The intent of this guideline is to allow text content to be read by users and by assistive technology, and to ensure that information necessary for understanding it is available.

**Comment by bakera** [comment]
こんな感じ?

このガイドラインの意図は、利用者及び支援技術によるテキストコンテンツの読み取りを可能にし、理解するために必要な情報が利用可能であることを保証することである。

**Comment by caztcha** [comment]
PR #1419 で対応中です。
