### ISSUE TITLE
解説書：andの訳語が「及び」と「かつ」で揺れている

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1414]
Derived #98

下記のように、とくに「AND」と大文字で記述される箇所について「かつ」「及び」で揺れているので、どちらかに統一したい

達成基準 1.1.1
https://waic.jp/docs/WCAG21/Understanding/non-text-content.html#techniques

> 状況 A: 短い説明が非テキストコンテンツと同じ目的を果たし、かつ同じ情報を提示できる場合:
>
> 状況 E: 非テキストコンテンツが CAPTCHA である場合:
> 1. G143: CAPTCHA の目的を説明するために、テキストによる代替を提供する、かつ、G144: 異なるモダリティを用いて同じ目的を果たす、もう一つの CAPTCHA がウェブページに含まれていることを確認する

SC 1.1.1
https://www.w3.org/WAI/WCAG21/Understanding/non-text-content#techniques

> Situation A: If a short description can serve the same purpose and present the same information as the non-text content:
>
> Situation E: If non-text content is a CAPTCHA:
1. G143: Providing a text alternative that describes the purpose of the CAPTCHA AND G144: Ensuring that the Web Page contains another CAPTCHA serving the same purpose using a different modality

達成動機 1.3.1
https://waic.jp/docs/WCAG21/Understanding/info-and-relationships.html#techniques

> 状況 A: ウェブコンテンツ技術が、表現によって伝えている情報及び関係性をプログラムによる解釈が可能になるセマンテックな構造を提供している場合:
> 7. G115: 構造をマークアップするために、セマンティックな要素を使用する、及び、H49: 強調又は特別なテキストをマークアップするために、セマンティックなマークアップを使用する

SC 1.3.1
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships#techniques

> Situation A: The technology provides semantic structure to make information and relationships conveyed through presentation programmatically determinable:
> G115: Using semantic elements to mark up structure AND H49: Using semantic markup to mark emphasized or special text

**Comment by bakera** [comment]
硬いけれども「及び」に統一の方向でしょうか。

**Comment by Koide-Junko** [comment]
「及び」も「かつ」も並列を表しますが、語として「ある事柄に他の事柄が加わる」のがより明確なのは「かつ」かな、と思いますので、「及び」でよいのではないかと思いました。（https://dictionary.goo.ne.jp/word/%E4%B8%94%E3%81%A4/）

**Comment by caztcha** [comment]
Understanding WCAG 2.1 の原文で該当箇所 (ALL CAPS の「AND」表記) を洗い出すの、どうやったらいいですかね...。
Google で「site:」検索しても、AND/and の区別はできないですし。

**Comment by momdo** [comment]
> Understanding WCAG 2.1 の原文で該当箇所 (ALL CAPS の「AND」表記) を洗い出すの、どうやったらいいですかね...。

とても面倒ですが、ローカルにダウンロードしてgrepで探す、ですかね…

**Comment by caztcha** [comment]
ひととおり、調べました。解説書の「十分な達成方法」で、複数の達成方法が (ALL CAPS の)「AND」で併記されているもののうち、下記のとおり「及び」と「かつ」の表記ゆれが確認できました。

## 「及び」と表記されているもの：
https://waic.jp/docs/WCAG21/Understanding/bypass-blocks#techniques
https://waic.jp/docs/WCAG21/Understanding/info-and-relationships.html#techniques
https://waic.jp/docs/WCAG21/Understanding/keyboard.html#techniques
https://waic.jp/docs/WCAG21/Understanding/link-purpose-in-context.html#techniques
https://waic.jp/docs/WCAG21/Understanding/parsing.html#techniques
https://waic.jp/docs/WCAG21/Understanding/timing-adjustable.html#techniques
https://waic.jp/docs/WCAG21/Understanding/identify-purpose.html#techniques

## 「かつ」と表記されているもの：
https://waic.jp/docs/WCAG21/Understanding/captions-live#techniques
https://waic.jp/docs/WCAG21/Understanding/consistent-identification.html#techniques
https://waic.jp/docs/WCAG21/Understanding/labels-or-instructions.html#techniques
https://waic.jp/docs/WCAG21/Understanding/meaningful-sequence.html#techniques
https://waic.jp/docs/WCAG21/Understanding/page-titled.html#techniques
https://waic.jp/docs/WCAG21/Understanding/resize-text.html#techniques
https://waic.jp/docs/WCAG21/Understanding/visual-presentation.html#techniques (これだけ `em` でマークアップされている)

## 揺れているもの
https://waic.jp/docs/WCAG21/Understanding/non-text-content.html#techniques
...状況 E が「かつ」になっていて、ほかが「及び」になっている。

---

ところで、
https://waic.jp/docs/WCAG21/Understanding/understanding-techniques.html#numbered-lists-%22and%22
を見ると、実は「かつ」で統一すべきなのかも？？？と思ったりします。

**Comment by bakera** [comment]
「十分な達成方法」に限って言えば、「かつ」のほうがわかりやすく意味が明確になると思われるので、「かつ」で統一したい。

**Comment by caztcha** [comment]
PR #1432 で対応中です。

**Comment by momdo** [comment]
マージしたのでClose
