### ISSUE TITLE
重要な用語：コンテキストの変化

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1417]
コンテキストの変化 (changes of context)において、

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-change-of-context

> ウェブページのコンテンツにおける大きな変化で、利用者が気づかないと、ウェブページ全体を一度に見ることのできない利用者を混乱させる恐れのあるもの。
>
> 状況の変化には次に挙げるものの変化が含まれる:

https://waic.jp/docs/WCAG21/#dfn-change-of-context

> changes of context
major changes in the content of the Web page that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously
>
> Changes in context include changes of:

原文ではなぜか「Changes in context」になっているがそれはさておき、ここでのcontextは「状況」ではなく「コンテキスト」と訳すべきではないだろうか。

**Comment by caztcha** [comment]
用語集なので、解説書も、影響範囲に含まれるかも。マルチファイル検索で対応する必要あり。

**Comment by caztcha** [comment]
PR #1422 で対応中です。
