### ISSUE TITLE
「達成基準 2.2.6 タイムアウト」の「jurisdictions」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#142]
「達成基準 2.2.6 タイムアウト」の「jurisdictions」が「裁判管轄」と訳されていますが、「管轄区域」ではいかがでしょうか？

**Comment by momdo** [comment]
「管轄区域」とすると何の管轄なのか、という疑問がわきます。少なくとも、
https://en.wikipedia.org/wiki/Jurisdiction からの日本語版のリンクが裁判管轄になっています。

**Comment by SawadaStdDesign** [comment]
承知いたしました。
お任せいたします。

**Comment by bakera** [comment]
たしかにこの文脈で裁判管轄はちょっと違和感がありますね。
「司法管轄」とすると違和感が低減されたりしますかね?

>ユーザーが未成年の場合、ほとんどの司法管轄、国又は地域で、ユーザーからの明示的な同意を要請することができない。

**Comment by momdo** [comment]
@bakera さんの社内に詳しいそうな人がいそうな気がするので、聞いて頂ければと（？）

**Comment by bakera** [comment]
司法管轄で違和感なければそれでお願いできればと。

**Comment by momdo** [comment]
マージされたので閉じます。
