### ISSUE TITLE
達成基準 3.3.4, 3.3.6：エラー回避は意訳過ぎないか

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1425]
達成基準 3.3.4 エラー回避 (法的、金融、データ) 
https://waic.jp/docs/WCAG21/Understanding/error-prevention-legal-financial-data.html

>利用者にとって法律行為もしくは金融取引が生じる、利用者が制御可能なデータストレージシステム上のデータを変更もしくは削除する、又は利用者が試験の解答を送信するウェブページでは、次に挙げる事項のうち、少なくとも一つを満たしている
>
>取消
送信を取り消すことができる。
チェック
利用者が入力したデータの入力エラーがチェックされ、利用者には修正する機会が提供される。
確認
送信を完了する前に、利用者が情報の見直し、確認及び修正をするメカニズムが利用できる。

Success Criterion 3.3.4: Error Prevention (Legal, Financial, Data)
https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-legal-financial-data

> For Web pages that cause legal commitments or financial transactions for the user to occur, that modify or delete user-controllable data in data storage systems, or that submit user test responses, at least one of the following is true:
>
> Reversible
Submissions are reversible.
Checked
Data entered by the user is checked for input errors and the user is provided an opportunity to correct them.
Confirmed
A mechanism is available for reviewing, confirming, and correcting information before finalizing the submission.

---

prevention  | Oxford Advanced Learner's Dictionary at OxfordLearnersDictionaries.com
https://www.oxfordlearnersdictionaries.com/definition/english/prevention?q=prevention

> the act of stopping something bad from happening

「止める」ことであって、「避ける」ことではないので、訳として見直してはどうか。

**Comment by caztcha** [comment]
「エラー防止」ですかね。

**Comment by bakera** [comment]
カタカナ「エラー」がシステムエラーっぽい感じがするが、ここではヒューマンエラーを指すので、カタカナにしない方が良いのではないか。
誤り防止?
