### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：WCAG 達成基準の達成方法を理解する

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1428]
差分を確認して、解説書を2022年9月2日版に更新します

原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/understanding-techniques
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-63f708014761cea99fc26363d9aecde5b552b89642140a06027a0dc5e475acb4
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/understanding-techniques.html

必要な作業内容については、[過去の2020年12月2日付けに更新したPull Request](https://github.com/waic/wcag21/pulls?q=is%3Apr+is%3Aclosed+%E6%9B%B4%E6%96%B0+label%3A%E8%A7%A3%E8%AA%AC%E6%9B%B8-v2)が参考になります。

**Comment by caztcha** [comment]
PR #1550 で対応中です。
