### ISSUE TITLE
「達成基準2.5.2ポインタの解除」の「Up Reversal」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#143]
「達成基準2.5.2ポインタの解除」の「Up Reversal」が「アップイベントで戻すことができる」と訳されていますが、「アップで逆転」ではいかがでしょうか？（これもどうかとは思いますが）

**Comment by momdo** [comment]
- ダウンイベントの対としてのアップイベントですから、ここで訳語を補うのは適当かと思います。
- 「逆転」とするのはしっくりきませんが、「戻すことができる」とするのが適当かどうかは議論の余地がありそうです。

**Comment by SawadaStdDesign** [comment]
「解除」とかの方がわかりやすいですかね？
と思ったら、節のタイトルが「キャンセル」に変更されましたね？

**Comment by bakera** [comment]
「戻すことができる」は「戻る」ですね
すぐ上で Undo が「元に戻す」と訳されているので、それとは訳し分けた方が良いと思います。「戻す」とするのは避けたい気持ちです。
「反転」「反対の動作」などでしょうか。

>アップイベントで反転:  アップイベントによって、先のダウンイベントのすべての結果が反転する。

**Comment by momdo** [comment]
太田さんコメントの最後の行のもので行ってみましょう。
