### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.1: テキストによる代替

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1430]
差分を確認して、解説書を2022年9月2日版に更新します

原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/text-alternatives
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-739077d5f6acdf1da1ba482a068ae8833f546b92168a554d39f6b1259e231ad8
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/text-alternatives.html

必要な作業内容については、[過去の2020年12月2日付けに更新したPull Request](https://github.com/waic/wcag21/pulls?q=is%3Apr+is%3Aclosed+%E6%9B%B4%E6%96%B0+label%3A%E8%A7%A3%E8%AA%AC%E6%9B%B8-v2)が参考になります。

**Comment by caztcha** [comment]
PR #1552 にて対応中です。
