### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2: 時間依存メディア

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1436]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/time-based-media
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-96d41cd405c972e2846f2e0cff7606528d72d792000b92c90846934c3c75e1ef
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/time-based-media.html

**Comment by caztcha** [comment]
PR #1555 にて対応中です。
