### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2.1: 音声のみ及び映像のみ (収録済)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1437]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/audio-only-and-video-only-prerecorded
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-3260a2e43666a38f97b5678eec3565d73f616e7c432869eade82434c24fca2ca
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/audio-only-and-video-only-prerecorded.html

**Comment by caztcha** [comment]
PR #1556 にて対応中です。
