### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2.3: 音声解説、又はメディアに対する代替 (収録済)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1439]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/audio-description-or-media-alternative-prerecorded
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-1744b6806fe00310a22ab73ce3902f0203b90a369b6bab6fc09394b116b14726
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/audio-description-or-media-alternative-prerecorded.html

**Comment by caztcha** [comment]
PR #1558 にて対応中です。
