### ISSUE TITLE
「6. 用語集」の「スタイルプロパティ (style properties)」の「several origins:」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#144]
「6. 用語集」の「スタイルプロパティ (style properties)」の「several origins:」が「起源」と訳されていますが、「元となるスタイル」ではいかがでしょうか？（意訳ですが）

**Comment by momdo** [comment]
仕様で言うところの [Cascading Origins](https://www.w3.org/TR/css-cascade-4/#cascading-origins) をどう訳出するか、という問題ですね。

**Comment by SawadaStdDesign** [comment]
そそそ、そーですね。

**Comment by bakera** [comment]
ここでは「出自」になっていますね。
https://triple-underscore.github.io/css-cascade-ja.html#cascading-origins

**Comment by bakera** [comment]
エンジニアには「オリジン」のままでも通じるような気もしています。

**Comment by momdo** [comment]
結論が出ていませんが、どれかにえいやで決めてしまってもよいのかなあと。
