### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2.4: キャプション (ライブ)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1440]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/captions-live
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-24d9b85e2b172dfdaf6beffe9b5510bf20301bc8d2368b004cb238293992c0ec
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/captions-live.html

**Comment by caztcha** [comment]
PR #1559 にて対応中です。
