### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2.5: 音声解説 (収録済)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1441]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/audio-description-prerecorded
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-861746398ad96301a3a78f0823668ba5ed69e2224f4fbc1d9311c00089ccf7a1
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/audio-description-prerecorded.html

**Comment by caztcha** [comment]
PR #1560 で対応中です。
