### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2.6: 手話 (収録済)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1442]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/sign-language-prerecorded
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-c51548b81b6176b07410cb9b66ff7eab50e3373e0821e475e8ca2ec9c216dcff
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/sign-language-prerecorded.html

**Comment by caztcha** [comment]
PR #1561 にて対応中です。
