### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2.7: 拡張音声解説 (収録済)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1443]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/extended-audio-description-prerecorded
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-853261eccfefe359312b862905a1d89b2148b8f5b3a6ae346a1fa18712e679b1
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/extended-audio-description-prerecorded.html

**Comment by caztcha** [comment]
PR #1562 にて対応中です。
