### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.2.9: 音声のみ (ライブ)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1445]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/audio-only-live
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-d6416aeb509f39998bdb0a249b73704d85a89894c0769781d4ad443804d44c79
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/audio-only-live.html

**Comment by caztcha** [comment]
PR #1564 にて対応中です。
