### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.3: 適応可能

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1446]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/adaptable
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-c014044b05463615faa5e31a33cfff14f3c5f2693f8a11ce8a884c44a53dabae
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/adaptable.html

**Comment by caztcha** [comment]
PR #1565 にて対応中です。
