### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.3.1: 情報及び関係性

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1447]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-178c7cd07d04846e509848dad529391a1312307b057c9099ab078f227781d569
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/info-and-relationships.html

**Comment by caztcha** [comment]
PR #1566 にて対応中です。
