### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.3.2: 意味のある順序

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1448]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-391037cc0dbebd20ee5897534e264681f3230511c6ceae92650fd281c5016331
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/meaningful-sequence.html

**Comment by caztcha** [comment]
PR #1567 にて対応中です。
