### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.3.3: 感覚的な特徴

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1449]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-8f6c58a5ac2ab748e75d3fc33c0b383c1b87ad140b4be739cf8a6623ee638236
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/sensory-characteristics.html

**Comment by caztcha** [comment]
PR #1568 にて対応中です。
