### ISSUE TITLE
「6. 用語集」の「アップイベント (up-event)」の「trigger stimulus」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#145]
「6. 用語集」の「アップイベント (up-event)」の「trigger stimulus」が「トリガ刺激」と訳されていますが、「トリガ」だけでもいいのではないのでしょうか？（ダウンイベントがそうなので）

**Comment by momdo** [comment]
訳出を省く積極的な理由になっているかどうか、いまいちしっくりこないので、個人的には消極的ですね。

**Comment by momdo** [comment]
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-up-event
>platform event that occurs when the trigger stimulus of a pointer is released

「要因」がそれほど魅力的に個人的には映りませんが、いずれにせよどう訳出するとしっくりくるのかは議論してよいと思います。

**Comment by SawadaStdDesign** [comment]
よろしくお願いいたします！

**Comment by bakera** [comment]
なお、down-eventの方ではスルーされて訳されている模様。

>platform event that occurs when the trigger stimulus of a pointer is depressed
>ポインタのトリガが押された時に生じるプラットフォームイベント。

**Comment by bakera** [comment]
- 「刺激」よりは「要因」のほうが良いように思える
- "trigger stimulus" を「トリガ」として訳しても良いのではないか
- down-eventの方の訳は現状で特に違和感がない

ということで、いったん単に「トリガ」としてみたいと思います。

**Comment by momdo** [comment]
カタカナでよいと思いますが、長音は省きますか？

**Comment by bakera** [comment]
いったん「トリガ」で。
違和感があるという声が多いようでしたらまた検討します。
