### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.3.4: 表示の向き

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1450]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/orientation
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-420aedda6d70122feb0eeefaa0b50268840d6f5dbb69a30496ba20f82979eb21
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/orientation.html

**Comment by caztcha** [comment]
PR #1569 にて対応中です。
