### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.3.5: 入力目的の特定

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1451]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-091494d1cf46b10c79795ed5af2e0693c1cd1e8de175647a6523e78cd189684d
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/identify-input-purpose.html

**Comment by caztcha** [comment]
PR #1570 にて対応中です。
