### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.3.6: 目的の特定

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1452]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/identify-purpose
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-7834f25749a1f86bc05cc58f63b1396963fb8f145dbf706a188b6b21c480ccc3
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/identify-purpose.html

**Comment by caztcha** [comment]
PR #1571 にて対応中です。
