### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4: 判別可能

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1453]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/distinguishable
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-1b01e3eec99d2c2cd51a84f574896411b35df4575f224b20f6cf86daf7b8e03f
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/distinguishable.html

**Comment by caztcha** [comment]
PR #1573 にて対応中です。
