### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.1: 色の使用

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1454]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/use-of-color
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-c307dbba84394e30c08faeb64f1ffba671d5624ac2f5f12e2270e894ce8d5f90
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/use-of-color.html

**Comment by caztcha** [comment]
PR #1574 にて対応中です。

**Comment by momdo** [comment]
マージ済みなのでCloseします
