### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.3: コントラスト (最低限)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1456]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-f73d2dd0e528ae27d3e518d6b0c21d6ad1f3c0be9179391a871c5e3c620477da
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/contrast-minimum.html

**Comment by caztcha** [comment]
PR #1638 にて対応中です。
