### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.4: テキストのサイズ変更

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1457]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/resize-text
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-940deb0bbfca6ca791cf386b8a4af6a446a39340ee8237e7cff0dd8740edb29d
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/resize-text.html

**Comment by caztcha** [comment]
PR #1640 で対応中です。
