### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.5: 文字画像

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1458]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/images-of-text
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-e07b8a1fcc5db58de6710aa5196c580498cef7c7c6d700deaf8dac0ed30187da
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/images-of-text.html

**Comment by caztcha** [comment]
PR #1641 にて対応中です。
