### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「とらえねばならない」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#146]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「ウェブページに適用される分類法でとらえねばならない目的を表す。」が理解しにくい印象を受けます。
「ウェブページで採用されている分類で捉えるべき目的を表す。」ではいかがでしょうか？

**Comment by momdo** [comment]
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#input-purposes
>The terms below are not keywords that must be used, but instead represent purposes that must be captured in the taxonomy adopted by a webpage.

must be capturedなので、提案されている訳は適切ではないですね。

むしろウェブページで採用されているタクソノミーで取り込まれ **なければならない** 目的を表す。

ぐらいでしょうか。（セマンティックウェブっぽいことを言っている段落なので、taxonomyをカナで訳出してみましたが、これはこれで議論の余地はあり。ただし https://www.ibm.com/developerworks/jp/xml/library/x-skostaxonomy/index.html のようなIBMの記事では、カナで訳出されます。）

**Comment by bakera** [comment]
ちょっと何度読み返してもよくわからない日本語だと思いましたが、原文もよくわからないですね。

>The terms below are not keywords that must be used, but instead represent purposes that must be captured in the taxonomy adopted by a webpage. 

あるいはこの capture は「取り込む」というより、「とらえる」、特定の観点で意味をとらえる、というような意味かもなぁと思ったりはしました。
たとえばこう?:

以下の用語は、キーワードとして使わなければならないものではなく、ウェブページで採用されている分類法の観点でとらえた目的を表すものである。

**Comment by bakera** [comment]
以下のようなことか?
- このキーワードを使わなければならないわけではない、
- ただし、このキーワードを使う以上は正しい分類で使わなければならない

**Comment by bakera** [comment]
こういうこと?:
以下の用語は、キーワードとして使わなければならないものではないが、(これらの用語を使ったならば)ウェブページで採用されている分類法の観点でとらえなければならない目的を表現することになる。

**Comment by bakera** [comment]
原文はたぶんこういう意図?
The terms below are not keywords that must be used.
But ,the terms below are keywords that represent purposes that must be captured in the taxonomy adopted by a webpage.

**Comment by bakera** [comment]
2文にするとこう?:
以下の用語は、使わなければならないキーワードというわけではない。そのかわり、これらのキーワードは目的を表現するものとなり、ウェブページで採用されている分類法の観点でとらえなければならないことになる。

**Comment by bakera** [comment]
ベストではない感じがするものの、いったん上記の2文にする案でいこうと思います。
