### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.7: 小さな背景音、又は背景音なし

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1460]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/low-or-no-background-audio
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-407edf054813f72213b3271c8ef74c5a7fb9df4a8c2dba0a2be9ea30089956d5
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/low-or-no-background-audio.html

**Comment by caztcha** [comment]
PR #1662 で対応中です。
