### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.8: 視覚的提示

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1461]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-5c8eba4a1f7d68a7d4e0a91b87177b7fcc8be226f55062abc8cad85a533ca672
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/visual-presentation.html

**Comment by caztcha** [comment]
PR #1663 で対応中です。
