### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.9: 文字画像 (例外なし)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1462]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/images-of-text-no-exception
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-db3e64e66599a6c64ae9d340b800779821953ec4a5bcc5a4b6d6c85fc8e8ff3b
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/images-of-text-no-exception.html

**Comment by caztcha** [comment]
PR #1664 で対応中です。
