### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.10: リフロー

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1463]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/reflow
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-6e4cc9ff06d4845c30b1021d3848882bae57f42641719ab18b26c0c8c51bdc2e
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/reflow.html

**Comment by caztcha** [comment]
PR #1665 で対応中です。
