### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.11: 非テキストのコントラスト

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1464]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-3d710d0b596da668f85c347fe03d927830e376f997c4a93216b07c78ac16e9df
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/non-text-contrast.html

**Comment by caztcha** [comment]
PR #1666 で対応中です。
