### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：1.4.13: ホバー又はフォーカスで表示されるコンテンツ

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1466]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-3f371deb9c28d398ca7450d7225f657d2e45d66e91d627d93fb9029bfbc267d4
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/content-on-hover-or-focus.html

**Comment by caztcha** [comment]
PR #1670 で対応中です。
