### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.1: キーボード操作可能

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1467]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/keyboard-accessible
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-459c862fe999249878b9397691f9d8244c7a58e4eede0f0c6ba43f2cc6e341c2
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/keyboard-accessible.html

**Comment by caztcha** [comment]
PR #1671 で対応中です。
