### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.1.1: キーボード

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1468]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/keyboard
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-39399e9410f6fd45b7d0b71081e11c5903e26284a32d3490b1e34653c2ab7874
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/keyboard.html

**Comment by caztcha** [comment]
28cc3d5

**Comment by momdo** [comment]
@caztcha 
コミット確認しました。Closeします。
