### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.1.2: キーボードトラップなし

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1469]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/no-keyboard-trap
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-9c8a93304957968e1520fd7f8be25cf8088233b3700d652c2d9666b068694cd7
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/no-keyboard-trap.html

**Comment by caztcha** [comment]
PR #1672 で対応中です。
