### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「personalized」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#147]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「personalized」が「個別化された」と訳されていますが、理解しにくい印象を受けますので「パーソナライズされた」ではいかがでしょうか？

**Comment by momdo** [comment]
ニュアンスとしては+1です。あえて日本語訳するなら、「個人の好みに合わせた」と言ったところでしょうか。

**Comment by SawadaStdDesign** [comment]
なるほどですね。
