### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.1.3: キーボード (例外なし)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1470]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/keyboard-no-exception
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-b31e41332a9b43e61cbc4fc1e906a9a35438d5cbb3830e39093d4d32a1ae90af
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/keyboard-no-exception.html

**Comment by caztcha** [comment]
PR #1673 で対応中です。
