### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.1.4: 文字キーのショートカット

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1471]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-0b3d0acec64cd190f5400b17403199c2ff71fe24c8836dd4061d8536513bba16
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/character-key-shortcuts.html

**Comment by caztcha** [comment]
PR #1674 で対応中です。
