### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.2: 十分な時間

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1472]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/enough-time
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-a0451a05092ab00036e1170685992b0ede3693160a4afb5b9fc976ec0f840299
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/enough-time.html

**Comment by caztcha** [comment]
PR #1675 で対応中です。
