### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.2.1: タイミング調整可能

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1473]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-fab88ef815fb339bc2bfb650cbb143de53aa4a8e80bf3f8c9c1a10646c289c57
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/timing-adjustable.html

**Comment by caztcha** [comment]
PR #1687 で対応中です。
