### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.2.2: 一時停止、停止、非表示

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1474]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-ceaf7042677062e750470d87a996c9c4188e88839ba8cc0cab43a13934ce4d2a
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/pause-stop-hide.html

**Comment by caztcha** [comment]
PR #1688 で対応中です。
