### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.2.3: タイミング非依存

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1475]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/no-timing
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-a08c869008f285804080cd1d419fc4730f78f46ba260d0e99446e2d5b61e07ce
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/no-timing.html

**Comment by caztcha** [comment]
PR #1689 で対応中です。
