### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.2.4: 割り込み

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1476]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/interruptions
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-31cac4ed6657f1900e9e8cc4028f7ff04117d79b736ee0e6d116ef96377daaa5
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/interruptions.html

**Comment by caztcha** [comment]
PR #1690 で対応中です。
