### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.2.5: 再認証

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1477]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/re-authenticating
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-54d933ffa23aa1a079363b14f36e25aac54cabb9c6de3a782bb77d7020513e27
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/re-authenticating.html

**Comment by caztcha** [comment]
PR #1691 で対応中です。
