### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.2.6: タイムアウト

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1478]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/timeouts
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-8b702f2a5040b92622729b40e1453d847ca81b29cbe68376bcfd6f926a914dc4
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/timeouts.html

**Comment by caztcha** [comment]
PR #1692 で対応中です。
