### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の英文へのリンク「HTML 5.2 オートフィル の節」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#148]
「7. ユーザインタフェース コンポーネントにおける入力目的」の注記にある英文へのリンク「HTML 5.2 オートフィル の節」が和訳されています。

**Comment by bakera** [comment]
原文では "HTML 5.2 Autofill field section" がリンクテキストですが、リンク先のセクションタイトルは "4.10.18.7. Autofill" です。

**Comment by bakera** [comment]
「HTML 5.2 Autofill field のセクション」とするといちおう成立しそうですが field という単語がどこから来たのか謎です。

**Comment by momdo** [comment]
訳文については太田さん案でよいと思います。
ところで本題からそれますが、HTML 5.2が廃止予定であることは訳注に記しますか？

**Comment by momdo** [comment]
マージされたので閉じます。
