### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.3.1: 3 回の閃光、又は閾値以下

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1480]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-741ee9918670fc4582c3d4b2e5a2c22acce8214d8eaad6e874566f82ea7b1ffd
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/three-flashes-or-below-threshold.html

**Comment by caztcha** [comment]
PR #1694 で対応中です。
