### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.3.3: インタラクションによるアニメーション

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1482]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-27c5a6c7c20287b5770c181457f823502aff0b11b2a8c897be4c09ae70f6ee71
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/animation-from-interactions.html

**Comment by caztcha** [comment]
PR #1696 で対応中です。
