### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4: ナビゲーション可能

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1483]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/navigable
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-bdd352a7be04c31fa0d73f65c4cff0058aa77e2f7df7de5b599814b6c60d8cac
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/navigable.html

**Comment by caztcha** [comment]
PR #1697 で対応中です。
