### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4.2: ページタイトル

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1485]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/page-titled
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-da10733b9ea44e060fcdadb19f19cd09af4c60093e4c712eb6e5a759e05db8af
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/page-titled.html

**Comment by caztcha** [comment]
PR #1713 で対応中です。
