### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4.3: フォーカス順序

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1486]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/focus-order
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-23682f8e7832f819d9fe4bb1df4f471306882eb8fd137cb0edba4627bdf6fe52
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/focus-order.html

**Comment by caztcha** [comment]
PR #1714 で対応中です。
