### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4.4: リンクの目的 (コンテキスト内)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1487]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-781b647b777d844d599cdf442cafc3f704ec1fc4efab5e678791cfdd07f0b023
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/link-purpose-in-context.html

**Comment by caztcha** [comment]
PR #1715 で対応中です。
