### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4.5: 複数の手段

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1488]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways.html
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-6ad2bf2fe92f2385ec25fdb9f765b99bb75a0cc5e234e79d1e711654de80e659
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/multiple-ways.html

**Comment by caztcha** [comment]
達成基準 2.4.5 は、navigable.html ではなく、multiple-ways.html ですね。

**Comment by caztcha** [comment]
PR #1730 で対応中です。
