### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4.6: 見出し及びラベル

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1489]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-8fd24d02e412945a68c3bcb2fb5b4c3ac076ef62f2b4c6d5e518bff8d9f6d37b
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/headings-and-labels.html

**Comment by caztcha** [comment]
PR #1731 で対応中です。

**Comment by momdo** [comment]
マージ済みなのでClose
