### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の注記にある「異なる技術でもその仕様に〜」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#149]
「7. ユーザインタフェース コンポーネントにおける入力目的」の注記にある「異なる技術でもその仕様に定義されている同じ概念の一部または全部を有することができ、概念は以下の意味にマッピングされていることのみが必要である、ということを理解することは重要である。」が理解しにくい印象を受けます。
「異なる技術では、その仕様に定義されている同じ概念の一部または全部が用いられている可能性があり、以下の意味に対応付けられている概念のみが必要であることを理解することが重要である。」ではいかがでしょうか？（あまり代わり映えしませんね）

**Comment by momdo** [comment]
原文は長い1文で
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#input-purposes
> The list of input type purposes is based on the control purposes defined in the HTML 5.2 Autofill field section, but it is important to understand that a different technology may have some or all of the same concepts defined in its specification and only the concepts that are mapped to the meanings below are required.

異なる技術→異なるウェブコンテンツ技術
その仕様→HTML仕様

と若干膨らませつつ、明確化すると…

異なるウェブコンテンツ技術は、HTML仕様で定義されているものと同じ概念の一部又は全部を持ってもよく、以下で示される意味に対応付けられているその概念のみが要求されることを理解することが重要である。

という感じでしょうか。
