### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4.7: フォーカスの可視化

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1490]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding//focus-visible
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-cbd651d6e7c709bc311edf19b4825f12b6ff785d8b2aca717fe0e25cbfba46be
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/focus-visible.html

**Comment by caztcha** [comment]
PR #1732 で対応中です。
