### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.4.10: セクション見出し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1493]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/section-headings
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-943160f29664b38cb452afe1292d1ca4575782376aa5a9825605eec5e34b7b6d
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/section-headings.html

**Comment by caztcha** [comment]
PR #1735 で対応中です。
