### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.5: 入力モダリティ

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1494]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/input-modalities
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-6baf0be943c2deeb0428757589fb5ba15319dcffa924e30e1c2472c97195c841
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/input-modalities.html

**Comment by caztcha** [comment]
PR #1736 で対応中です。
