### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.5.1: ポインタのジェスチャ

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1495]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-677b18933c2b9e763fb79dd0e5cba6a6dfcef613e99ed5666499dc826e5b1757
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/pointer-gestures.html

**Comment by caztcha** [comment]
PR #1737 で対応中です。
