### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.5.3: ラベルを含む名前 (name)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1497]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/label-in-name
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-b6c495791968f399fd29bbaa2615783092b144a02314744a49a4972eec41c71e
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/label-in-name.html

**Comment by caztcha** [comment]
Label in Name は「名前 (name) のラベル」から「ラベルを含む名前 (name)」に変更されているので、issue のタイトルを変更しました。

https://github.com/waic/wcag21/issues/1536

**Comment by caztcha** [comment]
PR #1740 で対応中です。
