### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「以下の入力コントロールの目的は、〜」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#150]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「以下の入力コントロールの目的は、コンテンツのユーザに関連することを意図しており、その個人に関連する情報のみにふさわしいものである。」が理解しにくい印象を受けます。
「以下の入力コントロールの目的は、コンテンツの利用者と関係付け、その個人に関係付けられた情報のみと結びつけることである。」ではいかがでしょうか？（これでも意味不明ですが）

**Comment by momdo** [comment]
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#input-purposes
>The following input control purposes are intended to relate to the user of the content and pertain only to information related to that individual.

以下の入力コントロールの目的は、コンテンツの利用者と関連付けることを意図し、かつその個人に関連付けられた情報のみに適切なものとなる。

ぐらいでしょうか。これでも変わらない気もしますが。

**Comment by bakera** [comment]
原文が悪文すぎてあれですが、多分構造的にはこうです。

The following input control purposes:
 They are intended to relate to the user of the content, and 
 They are intended to pertain only to information related to that individual.

そして前半はおそらくtheのニュアンスが出せないと難しいやつです。

以下に示す入力コントロールの目的は、(特定の)コンテンツの(そのコンテンツに実際にアクセスしている)ユーザーに関連づけること、その個人に関連する情報にのみ適用することを意図している。

というような感じでしょうか……?

**Comment by bakera** [comment]
いったん上記案のカッコトリで、

以下に示す入力コントロールの目的は、コンテンツの利用者に関連づけること、その個人に関連する情報にのみ適用することを意図している。

だとどうでしょうか?

**Comment by momdo** [comment]
マージされたので閉じます。
