### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：2.5.6: 入力メカニズム非依存

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1500]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/concurrent-input-mechanisms
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-c091f3fa9d7c0044dd69b4e2b0053a93f2dc369e5ad1997fdbda9ee60f00c8ab
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/concurrent-input-mechanisms.html

**Comment by caztcha** [comment]
PR #1746 で対応中です。
