### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.1: 読み取り可能

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1501]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/readable
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-cefbe2e286dc5838b8cb43637910b4639b2ec218dcd14f392e6a55a4640675f3
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/readable.html

**Comment by caztcha** [comment]
PR #1747 で対応中です。
