### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.1.1: ページの言語

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1502]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/language-of-page
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-55854c860fe91c671904c6a5e9edb93491c93c8b1ed29ab0f927b38f077feef2
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/language-of-page.html

**Comment by caztcha** [comment]
PR #1748 で対応中です。
