### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.1.2: 一部分の言語

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1503]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-73ec2581daf8794d6d73bc4085ec5613565747bf03b3b9a8655f20ce3958bac2
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/language-of-parts.html

**Comment by caztcha** [comment]
PR #1749 で対応中です。
