### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.1.3: 一般的ではない用語

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1504]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/abbreviations
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-75450759ea7fb91a92f880c8cf8ef6b0b7e90d7d64cf05bc87c41f12ccaa7e1b
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/abbreviations.html

**Comment by caztcha** [comment]
PR #1752 で対応中です。
