### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.1.5: 読解レベル

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1506]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/reading-level
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-bf0f779d15494a3c5a0ed9230ef2bc0ec8a498b2c3b61d5a3ce6e04165fe6322
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/reading-level.html

**Comment by caztcha** [comment]
PR #1754 で対応中です。
