### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.1.6: 発音

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1507]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/pronunciation
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-852af7382ccc08c9151fb9efb7ef8f6cd4632b2f3ea1a144f69d2e468441a20d
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/pronunciation.html

**Comment by caztcha** [comment]
PR #1755 で対応中です。
