### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.2: 予測可能

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1508]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/predictable
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-66324f1f4de8c1201bc77c3a59a1d8f546157f9ae0ddf9992e612da1551767ae
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/predictable.html

**Comment by caztcha** [comment]
PR #1756 で対応中です。
