### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.2.1: フォーカス時

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1509]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/on-focus
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-2a61480b3c22837c46f5264c4373604fd943bdf53739a46af01a8e64a7a3509c
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/on-focus.html

**Comment by caztcha** [comment]
PR #1757 で対応中です。
