### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.2.2: 入力時

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1510]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/on-input
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-267fcbb04bbbec7015268839a04910b302759ea88c51e741469da68c7e64becc
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/on-input.html

**Comment by caztcha** [comment]
PR #1758  で対応中です。
