### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.2.3: 一貫したナビゲーション

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1511]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-e7211d0a5c2a5a184f2bcbacfeecbcd61be8b508732255e07f9179073f2900a9
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/consistent-navigation.html

**Comment by caztcha** [comment]
PR #1760 で対応中です。
