### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.2.4: 一貫した識別性

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1512]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-727e82d386f258149722bd9dc2856fd7deb38cdcfa38bb5a3da8960796e59e9c
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/consistent-identification.html

**Comment by caztcha** [comment]
PR #1761 で対応中です。
