### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.2.5: 要求による変化

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1513]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/change-on-request
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-0478e14ba74a0f2feb463180a59c9528695e9c39dab1dae9d6ef9bd403d6f019
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/change-on-request.html

**Comment by caztcha** [comment]
PR #1762 で対応中です。
