### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.3.1: エラーの特定

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1515]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/error-identification
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-5b10be3d4a198d669cbc7ba7c07699411a55a584e1a9ff6c1ca097a6ed89b906
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/error-identification.html

**Comment by caztcha** [comment]
PR #1775 で対応中です。
