### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.3.2: ラベル又は説明

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1516]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-f17ee971c960fde29411334163a6ad1f3e60b17454b3d40a3f6e730f149e7ce2
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/labels-or-instructions.html

**Comment by caztcha** [comment]
PR #1776 で対応中です。
