### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.3.3: エラー修正の提案

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1517]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-e92c50442e200c791e6a673bbac02ec8344cac872dce2f3f795c51bc442105d1
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/error-suggestion.html

**Comment by caztcha** [comment]
PR #1777 で対応中です。
