### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：3.3.5: ヘルプ

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1519]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/help
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-17773c19f73c9603bb8c246c523a5e44f75df8585ae10d9de377f9ae2c005c20
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/help.html

**Comment by caztcha** [comment]
PR #1782 で対応中です。
