### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Given name」「first name」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#152]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Given name」「first name」が訳出されていません。

**Comment by momdo** [comment]
名字と名前の名前に当たると思いますが、単に名前と訳していいものなのか、というあたりでしょうか。

**Comment by bakera** [comment]
現地での呼び名を示している個所なので、このままで成立しているように思います。あえて言うなら「ファーストネーム」「ミドルネーム」「ラストネーム」をカタカナにするかくらいですが、このままでいいかなと。

>given-name - Given name (一部の西洋文化において、first name として知られる)
>additional-name - 決済手段に与えられるような Additional names (一部の西洋文化において、middle names として知られる)
>family-name - 決済手段に与えられるような Family name (一部の西洋文化において、last name 又は surname として知られる)

**Comment by ishimasar** [comment]
> このままでいいかなと。
に対しもんどさんからOK出ているようなのでCloseしたいと思います。
