### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：4.1: 互換性

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1521]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/compatible
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-bbf80a6fe5e12794cc56525721bf585ee44db3aac89f7ac0854a92d92bd0f5fd
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/compatible.html

**Comment by caztcha** [comment]
PR #1784 で対応中です。
