### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：4.1.2: 名前 (name) ・役割 (role) 及び値 (value)

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1523]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/name-role-value
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-079473a69ad3c0fe6a87101bfd34a5adbbe7a296d04e0801ce4654313806ab58
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/name-role-value.html

**Comment by caztcha** [comment]
PR #1785 で対応中です。
