### ISSUE TITLE
WCAG 2.1解説書（2022年9月版更新）：4.1.3: ステータスメッセージ

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1524]

**Comment by momdo** [comment]
原文（w3.org）
https://www.w3.org/WAI/WCAG21/Understanding/status-messages
原文の差分
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-2a531b4f20e564ed7a730503cabbf6a4b8d108699302db85a5eaf3690a9e57e9
現在の日本語訳（waic.jp）
https://waic.jp/docs/WCAG21/Understanding/status-messages.html

重要な用語の差分あり

**Comment by caztcha** [comment]
PR #1786 で対応中です。
