### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Additional names〜」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#153]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Additional names (in some Western cultures, also known as middle names , forenames other than the first name)」が「決済手段に与えられるような Additional names (一部の西洋文化において、middle names として知られる)」と訳されていますが、「決済手段に与えられるような」に該当する単語が見当たりません。「forenames other than the first name」が訳出されていません。

**Comment by momdo** [comment]
ミドルネームにあたるものですが、どう訳すのが適当でしょうね。

**Comment by bakera** [comment]
「決済手段に与えられるような」は下の方の cc-additional-name からのコピペミコスっぽいですね。これは単に削除で良いと思います。

**Comment by bakera** [comment]
Additional names とかはもうそのままで良いのではないでしょうか。

**Comment by ishimasar** [comment]
> 「forenames other than the first name」が訳出されていません。
の部分ですが、
> Additional names とかはもうそのままで良いのではないでしょうか。
ということと、訳出しなくてもほぼ自明と思いますので、特に作業していません。

**Comment by momdo** [comment]
マージされたので閉じます。
