### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「family-name - Family name 」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#154]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「family-name - Family name 」が「決済手段に与えられるような Family name (一部の西洋文化において、last name 又は surname として知られる)」と訳されていますが、「決済手段に与えられるような」に該当する単語が見当たりません。
「Family name」「last name」「surname」が訳出されていません。

**Comment by momdo** [comment]
名字にあたる箇所ですが、これもどう訳すのが適当でしょうか。

**Comment by bakera** [comment]
「決済手段」は下のほうのcc-nameのほうにあり、そこからのコピペミスと思われるので削除で。
additional nameについて、訳出漏れがあるという指摘がありました。

>additional-name - Additional names (in some Western cultures, also known as middle names, forenames other than the first name)
>Additional names (一部の西洋文化において、middle names として知られる)

forenames other than the first nameが訳されていません。

Additional names (一部の西洋文化においてmiddle names として知られる、姓の前にあるファーストネームではない名前)

でしょうか。

**Comment by ishimasar** [comment]
> 「決済手段」は下のほうのcc-nameのほうにあり、そこからのコピペミスと思われるので削除で。

この作業は #153 からのブランチ上で行いました。

また、

> forenames other than the first nameが訳されていません。
> Additional names (一部の西洋文化においてmiddle names として知られる、姓の前にあるファーストネームではない名前)

上記訳出も #153 とほぼ同じ箇所であるため、この#154 の作業は #153 へ統合します。

**Comment by momdo** [comment]
マージされたので閉じます。
