### ISSUE TITLE
ガイドライン 1.1：「拡大印刷」でよいか

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1548]
ガイドライン 1.1 テキストによる代替
> すべての非テキストコンテンツには、拡大印刷、点字、音声、シンボル、平易な言葉などの利用者が必要とする形式に変換できるように、テキストによる代替を提供すること。

https://waic.jp/docs/WCAG21/Understanding/text-alternatives.html

> Provide text alternatives for any non-text content so that it can be changed into other forms people need, such as large print, braille, speech, symbols or simpler language.

https://www.w3.org/WAI/WCAG21/Understanding/text-alternatives

large printに「拡大印刷」が当てられているが、これは大活字（本）のことを指しているという理解であり、この訳でよいのかどうかを確認したい。

**Comment by bakera** [comment]
単なる拡大印刷であればテキストによる代替は必ずしも必要ないはずなので、大活字を指しているはずという指摘は正しいとおもわれる。
ただし「大活字」と言われて通じるかどうかという点が問題となる
「大活字」として訳注で補う?
いい感じの訳注が用意できれば。

**Comment by momdo** [comment]
国会図書館を訳注にしてはどうか

障害者向け資料の紹介｜国立国会図書館―National Diet Library https://www.ndl.go.jp/jp/library/supportvisual/geppo201501/article05.html

以下をアレンジして訳注にすればよさそう

> 大活字本・拡大写本
> 大活字本・拡大写本は、弱視の方が読みやすいよう、文字を拡大した資料です。通常の出版物より大きな活字で出版社から出版された資料を大活字本、読者一人一人のニーズに合わせた形でボランティア等が文字を拡大して作成した資料を拡大写本と呼んでいます。これらの資料は、加齢で文字を読みづらくなった方にも喜ばれます。

以下はどうか。

大活字とは、通常の出版物より大きな活字のことを指す。[障害者向け資料の紹介｜国立国会図書館―National Diet Library ](https://www.ndl.go.jp/jp/library/supportvisual/geppo201501/article05.html)も参照。
