### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「(one line per field, line 1)」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#156]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「(one line per field, line 1)」が「(フィールドごとに 1 行)」と訳されていますが、「 line 1」が訳出されていません。 （2,3行目も同様）

**Comment by bakera** [comment]
(フィールドごとに 1 行、1 行目) ですかね。

**Comment by bakera** [comment]
>address-line1 - 所在地住所 (フィールドごとに 1 行)
>address-line1 - 所在地住所 (フィールドごとに 2 行)
>address-line1 - 所在地住所 (フィールドごとに 3 行)

これを以下のように。

address-line1 - 所在地住所 (フィールドごとに 1 行、1行目)
address-line2 - 所在地住所 (フィールドごとに 1 行、2行目)
address-line3 - 所在地住所 (フィールドごとに 1 行、3行目)

**Comment by momdo** [comment]
マージされたので閉じます。
