### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Month component」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#157]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Month component」が「月コンポーネント」と訳されていますが、「月の部分」ではいかがでしょうか？（その他の「〜コンポーネント」も同様）

**Comment by bakera** [comment]
これは「ユーザインタフェース コンポーネント」の「コンポーネント」なのではないかという指摘がありました。
「の」を入れて、「誕生日の月のコンポーネント」のようにしてはどうでしょうか。
(「の」の連続がみられるのがやや気持ち悪いですが、許容範囲ということで)

**Comment by momdo** [comment]
bday-monthはまあそれでよいとして、cc-exp-monthはどうしましょうか。「決済手段の有効期限の月のコンポーネント」となって、3回「の」が出現するのは避けたいなあと。

**Comment by bakera** [comment]
>tel-local-prefix - 二つのコンポーネントに分割される場合、市外局番に続く電話番号のコンポーネントの最初の部分
>tel-local-prefix - First part of the component of the telephone number that follows the area code, when that component is split into two components

原文にcomponentが3つあるのに訳文にはコンポーネントが2つしかない。

コンポーネントが二つのコンポーネントに分割される場合の、市外局番に続く電話番号のコンポーネントの最初の部分

**Comment by bakera** [comment]
若干の意訳になるが

市外局番に続く電話番号のコンポーネントが二つに分割される場合の最初の部分

のほうが分かりやすいかもしれない。

**Comment by bakera** [comment]
結論としては:

- コンポーネントはコンポーネントのまま
- 「の」の連続はいったん気にしない
- コンポーネントが一つ足りないのは補って数を合わせる
