### ISSUE TITLE
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Home page or other Web page 〜」

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#158]
「7. ユーザインタフェース コンポーネントにおける入力目的」の「Home page or other Web page corresponding to the company, person, address, or contact information in the other fields associated with this field」が「ホームページや会社に対応する他のウェブページ、人、アドレス、又はこのフィールドに関連付けられる他のフィールドでの連絡先情報」と訳されていますが、「このフィールドに関連する他のフィールドの会社、個人、住所、または連絡先情報に対応するホームページまたはその他のウェブページ」ではいかがでしょうか？（photoも同様）

**Comment by bakera** [comment]
>Home page or other Web page corresponding to the company, person, address, or contact information in the other fields associated with this field

orとかtoとかinとかが非常にわかりにくいですが、以下のようなまとまりと思われます。

(Home page or other Web page)
 corresponding to the
(company, person, address or contact information)
 in the other fields associated with this field

**Comment by bakera** [comment]
澤田さん案で良いと思うのですが、「他のフィールドの」を「他のフィールドに入力された」とすると少しわかりやすくなりそうです。

このフィールドに関連する他のフィールドに入力された会社、個人、住所、または連絡先情報に対応するホームページまたはその他のウェブページ

これでどうでしょうか。

**Comment by momdo** [comment]
または→又は　としてもらえればそれでよいと思います。

**Comment by momdo** [comment]
マージされたので閉じます。
