### ISSUE TITLE
用語集：閃光の修正

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1580]
Derived from https://github.com/waic/wcag21/issues/1390, related to https://github.com/waic/wcag21/issues/98

閃光について、

> 閃光 (flash)
> 相対輝度の交互の変化で、ある程度の面積と特定の頻度によって、一部の人の発作を誘発する恐れがあるもの。

https://waic.jp/docs/WCAG21/#dfn-flashes

> flash
> a pair of opposing changes in relative luminance that can cause seizures in some people if it is large enough and in the right frequency range

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-flashes

https://github.com/waic/wcag21/issues/1390 では、
a pair of opposing changesを「相反する変化の組合せ」としたので、以下はどうか。

相対輝度の相反する変化の組合せで、十分に大きく、かつ適当な頻度の範囲にある場合に、一部の人に発作を誘発する恐れがあるもの。

**Comment by momdo** [comment]
Derived #98

**Comment by bakera** [comment]
以下のようにしてはどうか。

相対輝度の相反する変化の組合せで、十分な広さを持ち、かつ特定の頻度の場合に、一部の人に発作を誘発する恐れがあるもの。
