### ISSUE TITLE
F104 「囲む要素の oveflow プロパティを非表示に設定する」

### ISSUE THREAD

**Issue by chuff-chuff** [waic/wcag21#1589]
[達成基準 1.4.12 の失敗例 － テキストの間隔を調整したときにコンテンツが切り取られたり重なったりする](https://waic.jp/docs/WCAG21/Techniques/failures/F104)
> 囲む要素の oveflow プロパティを非表示に設定する

とありますが、この箇所は[原文](https://www.w3.org/WAI/WCAG21/Techniques/failures/F104)だと
> Setting the overflow property of the enclosing element to hidden

となっています。これは CSS の overflow プロパティにおける hidden という値を指していると思われるので、
訳さずに
> 囲む要素の oveflow プロパティを hidden に設定する

とするのがよいのではと思います（全体的にもっとよい訳出がありそうでもありますが）

**Comment by momdo** [comment]
本当に非表示にしているわけでもないので、hiddenがよさそうですね

> 全体的にもっとよい訳出がありそうでもありますが

enclosing を「囲んでいる」とすると、少しは変わりそうでしょうか…？

案：
囲んでいる要素の oveflow プロパティを hidden に設定する

---

話はそれますが、F104と達成方法集の表紙とで、達成方法の名称が異なりますね…

F104 https://waic.jp/docs/WCAG21/Techniques/failures/F104
> 達成基準 1.4.12 の失敗例 － テキストの間隔を調整したときにコンテンツが切り取られたり重なったりする

表紙 https://waic.jp/docs/WCAG21/Techniques/
> F104: 達成基準 1.4.12 の失敗例 － テキストの間隔を調整したときにコンテンツが切り取られる又は重なる

**Comment by chuff-chuff** [comment]
> 案：
囲んでいる要素の oveflow プロパティを hidden に設定する

「囲む要素の」よりよいのではと思います！

---
名称の揺れ、気づきませんでしたね…
