### ISSUE TITLE
単語jargon/technical termsについて（3.1.2/3.1.3）

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#159]
少しばかり2.0関連文書の話も混じっているのですが。

[達成基準 3.1.2](https://waic.github.io/wcag21/guidelines/#language-of-parts)では
> コンテンツの一節、又は語句それぞれの自然言語がどの言語であるか、プログラムによる解釈が可能である。ただし、固有名詞、技術用語、言語が不明な語句、及びすぐ前後にあるテキストの言語の一部になっている単語又は語句は除く。

[Success Criterion 3.1.2](https://www.w3.org/TR/2018/REC-WCAG21-20180605/#language-of-parts)
> The human language of each passage or phrase in the content can be programmatically determined except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text.

[達成基準 3.1.3](https://waic.github.io/wcag21/guidelines/#unusual-words)
> 慣用句及び専門用語を含めて、一般的ではない、又は限定された用法で使われている単語、又は語句の、明確な定義を特定するメカニズムが利用できる。

[Success Criterion 3.1.3](https://www.w3.org/TR/2018/REC-WCAG21-20180605/#unusual-words)
> A mechanism is available for identifying specific definitions of words or phrases used in an unusual or restricted way, including idioms and jargon.

一方で2.0解説書3.1.2の訳ですが…
http://waic.github.io/wcag20/Understanding/meaning-other-lang-id.html

>ほとんどの専門的な職業では、外国語からきた技術用語を頻繁に使うことを必要とする。そのような用語は、通常すべての言語に翻訳されていない。技術用語の広く共通な性質は、専門家の間でのコミュニケーションも促進する。
>
> 技術用語のよくある例としては、次のようなものがある: ホモ サピエンス (Homo sapiens)、アルファケンタウリ (Alpha Centauri)、ヘルツ (hertz)、ヘイビアス コーパス (habeas corpus) など。

技術用語と取ると、エンジニアリングに関係する用語のように見え、上記引用部での例と若干噛み合わないように思えます。ここは専門用語としてはどうでしょうか。

2.0/2.1解説書の原文
https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html
https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/meaning-other-lang-id.html

>Most professions require frequent use of technical terms which may originate from a foreign language. Such terms are usually not translated to all languages. The universal nature of technical terms also facilitate communication between professionals.
>
>Some common examples of technical terms include: Homo sapiens, Alpha Centauri, hertz, and habeas corpus.

ただし、technical termsを専門用語とすると、[用語集のjargonを専門用語としている](https://waic.github.io/wcag21/guidelines/#dfn-jargon)ので、混同してしまう恐れがあります。jargonは若干の"アレゲ"な感じのある言葉なので、これを業界用語としてはどうでしょうか？

**Comment by bakera** [comment]
「業界用語」にしたいというのが私の意見です。
ひとまず、2.1だけしれっと「業界用語」にしてしまいたいです。

**Comment by momdo** [comment]
私の提案通りなので特に補足コメントはないです。
しれっとJIS改訂で直したいですね。

**Comment by bakera** [comment]
JISになるかどうかはいったん気にせず、ひとまず2.1のほうは直してしまう方向にしたいと思います。
