### ISSUE TITLE
解説書 1.4.4 リンクテキストは英語だがリンク先が日本語のリンクがある

### ISSUE THREAD

**Issue by chuff-chuff** [waic/wcag21#1590]
[達成基準 1.4.4: テキストのサイズ変更を理解する](https://waic.jp/docs/WCAG21/Understanding/resize-text.html)

失敗例に 

> [F94: Failure of Success Criterion 1.4.4 due to text sized in viewport units](https://waic.jp/docs/WCAG21/Techniques/failures/F94)

というリンクがありますが、リンク先は日本語の失敗例 https://waic.jp/docs/WCAG21/Techniques/failures/F94 なので、

> F94: 達成基準 1.4.4 の失敗例 － サイズ変更のためのビューポート単位を誤って使用している

にリンクテキストを修正するのがよいのではと思います。

**Comment by momdo** [comment]
新しく追加された達成方法の翻訳が反映されていないパターンですね…

**Comment by chuff-chuff** [comment]
あーなるほど、そういうパターンがあるわけですね…

**Comment by momdo** [comment]
これ、GitHub上では直っているので、WAICのページを更新する必要がありますね。
https://waic.github.io/wcag21/understanding/resize-text.html#techniques

@bakera どこかのタイミングで一度更新する必要があるかと。

**Comment by chuff-chuff** [comment]
> これ、GitHub上では直っているので、WAICのページを更新する必要がありますね。

そうか、そういうパターンがあるわけですね、なるほど。次からはGitHubも確認してからissue立てるようにします（もしくはプルリクにするか）

**Comment by momdo** [comment]
https://github.com/waic/wcag21/pull/1408 でコミット済みなのでこのissueはcloseします。
WAICサーバーへは、#1591 で反映予定です。
