### ISSUE TITLE
WCAG 2.1 本体: ステータスメッセージの用語定義の説明文を調整したい

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1603]
https://github.com/waic/wcag21/pull/1597#discussion_r1108024079 より

「ステータスメッセージ」の用語説明は以下のようになっています。

>ステータスメッセージ (status message)
>[コンテキストの変化](https://waic.jp/docs/WCAG21/#dfn-change-of-context)ではなく、コンテンツにおける変化で、アクションの成否又は結果、アプリケーションの処理待ち状態、プロセスの進捗、又はエラーの存在に関する情報を利用者に提供する。

「提供する」で終わっていて、「ステータスメッセージ」の説明としてはおかしい感じがします。原文はこうです。

>status message
>change in content that is not a [change of context](https://www.w3.org/WAI/WCAG21/Understanding/status-messages#dfn-changes-of-context), and that provides information to the user on the success or results of an action, on the waiting state of an application, on the progress of a process, or on the existence of errors

文末は「提供する」ではなく「提供するもの」とするのがよさそうに思います。また、定義のメインは "change in content" ですが、これは「コンテンツにおける変化」というより、単にコンテンツ内の変化 (コンテキストの変化を伴わない、現在のコンテンツ内の変化) というニュアンスであるように思います。
以下のようにしてはどうでしょうか。

ステータスメッセージ (status message)
コンテンツ内の変化であり、コンテキストの変化ではなく、かつ、アクションの成否又は結果、アプリケーションの処理待ち状態、プロセスの進捗、又はエラーの存在に関する情報を利用者に提供するもの。

**Comment by momdo** [comment]
文書の構造としては（書き方がこれで通じるのかどうかはさておき）こういうことですね…
```
{
  {コンテキストの変化ではない}
  かつ
  {
    {アクションの成否　もしくは　結果}
    {アプリケーションの処理待ち状態}
    {プロセスの進捗}
    または
    {エラーの存在}
  }
  に関する情報を利用者に提供する
}
コンテンツ内の変化。
```

**Comment by bakera** [comment]
そうですね。以下のようにするのもアリかと思います。

コンテキストの変化ではなく、かつ、アクションの成否又は結果、アプリケーションの処理待ち状態、プロセスの進捗、又はエラーの存在に関する情報を利用者に提供するコンテンツ内の変化。

**Comment by momdo** [comment]
太田さんのものを手直しすると、こういうのもありでしょうか。

コンテンツ内の変化。これは、コンテキストの変化ではなく、かつ、アクションの成否もしくは結果、アプリケーションの処理待ち状態、プロセスの進捗、又はエラーの存在に関する情報を利用者に提供するものである。

**Comment by bakera** [comment]
以下にしてはどうか:

コンテンツ内の変化であって、コンテキストの変化ではなく、かつ、アクションの成否又は結果、アプリケーションの処理待ち状態、プロセスの進捗、又はエラーの存在に関する情報を利用者に提供するもの。
