### ISSUE TITLE
WAICサイトのURL変更に伴う修正

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1610]
WAICサイト上の翻訳文書のURLをdocs→translationsに変更しました。

https://waic.jp/news/20230224/

これに伴い、文書間で絶対URLでリンクしている箇所も変更が必要になります。リダイレクトは設定されているので、現状で致命的な問題があるわけではありませんが、リダイレクトが挟まらないようにリンクを修正することが望ましいです。

特にWCAG解説書→達成方法集は相互にリンクしていて、絶対URLが使われている箇所が多数あります。たとえば解説書の「十分な達成方法」のリンク、

https://waic.jp/translations/WCAG21/Understanding/non-text-content.html

達成方法の「適用 (対象)」のリンク、

https://waic.jp/translations/WCAG21/Techniques/aria/ARIA1

などが該当します。URLの`https://waic.jp/docs/`を`https://waic.jp/translations/`に機械的に置換すれば良いはずです。

**Comment by momdo** [comment]
PRを作るのは難しくないですが、https://github.com/waic/wcag21/pull/1595 とコンフリクトしそうな気がしており…というところでしょうか。
