### ISSUE TITLE
用語集：手話 の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1614]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/docs/WCAG21/#dfn-sign-language
> 手話 (sign language)
> 意味を伝えるために、手と腕の動き、顔の表情又は身振りなどの組み合わせを用いる言語。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-sign-language
> a language using combinations of movements of the hands and arms, facial expressions, or body positions to convey meaning

body positionsが「身振り」としているのに違和感が。
そもそも「手と腕の動き」は「身振り」のことを指していると思っており、同じことを2回言ってしまっているのでは…？

意味を伝えるために、手と腕の動き、顔の表情又は身体の位置の組み合わせを用いる言語。

とするのはどうか？

**Comment by bakera** [comment]
「身体の姿勢」くらいでも良いかもしれません。
