### ISSUE TITLE
レビュー：「非テキストのコントラストを理解する」のリンク先と見出しの構造

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1618]
[達成基準 1.4.11: 非テキストのコントラストを理解する](https://dev.waic.jp/translations/WCAG21/Understanding/non-text-contrast.html)で、「十分な達成方法」において、

- 「状況 B」がh4であるのに対して、「状況 A」はh5になっている（[本家](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)はh4になっている）。「状況 A」もh4にしたいです
- [G195](https://www.w3.org/WAI/WCAG21/Techniques/general/G195)と[G175](https://www.w3.org/WAI/WCAG21/Techniques/general/G174)は、それぞれ日本語（[G195](https://waic.jp/translations/WCAG21/Techniques/general/G195), [G175](https://waic.jp/translations/WCAG21/Techniques/general/G174)）にリンクした方がいいのではないでしょうか

**Comment by momdo** [comment]
なんで状況Aが`<h5>`になってるんでしょうねぇ…（しろめ
リンクも修正します。
