### ISSUE TITLE
レビュー：docsとtranslationsのリンク

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1619]
今回の見直しで、docsディレクトリがtranslationsディレクトリに変わったことについて、リンク先の見直しはしない感じでしょうか？

**Comment by momdo** [comment]
@jidaikobo-shibata 
コメントの趣旨としては、https://github.com/waic/wcag21/issues/1610 と同一内容ということでよいでしょうか…？

**Comment by jidaikobo-shibata** [comment]
おっと、すみません。issue検索を失念していました。close pls.

**Comment by momdo** [comment]
#1610 と重複しているのでCloseします。
