### ISSUE TITLE
レビュー：「達成基準 1.4.12: テキストの間隔を理解する」の「十分に可能にすることができる」

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1621]
https://dev.waic.jp/translations/WCAG21/Understanding/text-spacing.html

原文:
>  For instance Cascading Style Sheet/HTML technologies are quite able to allow for the specified spacing metrics.

現状:
> 例えば、Cascading Style Sheet / HTML 技術は、規定の間隔基準を十分に可能にすることができる。

気になるところ:
「quite able to allow」は、「十分に可能にすることができる」となっていますが、「十分に満たすことができる」とか「十分に許容できる」という感じがします。

**Comment by momdo** [comment]
https://eow.alc.co.jp/search?q=allow+for

十分に考慮できる　はどうか。

例えば、Cascading Style Sheet / HTML 技術は、規定の間隔基準を十分に考慮できる。

**Comment by jidaikobo-shibata** [comment]
いいと思います。そもそも「CSS/HTMLは、規定の間隔を実現できる」というニュアンスですよね。たしかに、考慮できますね。

**Comment by bakera** [comment]
うーん、このへんいろいろ怪しいですね……
The specified metrics は上の方では「指定されたメトリクス」と訳されているのですが、ここのmetricsは「規定の間隔基準」になっていたりするという。

**Comment by bakera** [comment]
この達成基準はちょっとややこしいので、そもそものところをすこしメモしておきます。

この達成基準では、ユーザーが任意に文字間隔を変更した場合に、コンテンツが読めなくならないようにすることを求めていて、ユーザーが設定する文字間隔について規定しています。一方で、コンテンツ制作者も文字間隔を設定できます。つまり、ここでは2種類の metrics が存在していて、それぞれを以下のように呼んでいます。

- The specified metrics : この達成基準が規定している、ユーザーが設定する文字間隔
- the author's metrics: コンテンツ制作者が設定する文字間隔

ここで問題になっている文に出てくる the specified spacing metrics は前者、ユーザー指定の文字間隔です。つまりここでは、CSS/HTMLで作られたコンテンツはユーザーによる文字間隔変更ができるのでこの達成基準の対象になる (そしてPDFはそれができないので対象にならない) という話をしています。少し前から原文を引用すると、こんな感じです。

https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html
>If the markup-based technologies being used are capable of overriding text to the Success Criterion's metrics, then this SC is applicable. For instance Cascading Style Sheet/HTML technologies are quite able to allow for the specified spacing metrics.

allowという言葉が使われているのは、コンテンツ制作者が間隔を指定できるという話ではなく、ユーザーに間隔変更を許すというニュアンスになります。

**Comment by jidaikobo-shibata** [comment]
> allowという言葉が使われているのは、コンテンツ制作者が間隔を指定できるという話ではなく、ユーザーに間隔変更を許すというニュアンスになります。

むちゃくちゃわかりやすしです。

**Comment by bakera** [comment]
「メトリクス」をカタカナ書きすることにして直訳するならこういう感じですかね?
quite → まさに、くらいでどうですか?

使用されているマークアップベースの技術が、テキストをこの達成基準のメトリクスで上書きできるものである場合、この達成基準は適用可能である。例えば Cascading Style Sheet / HTML 技術は、まさに指定された間隔のメトリクスを許すことが可能である。

**Comment by bakera** [comment]
metrics をどうするかという問題があるのですが、「基準」とするとと「達成基準」(criterion) と紛らわしくて、「この基準」というのが metrics を指すのか criterion を指すのかわからなくなる問題があるんですよね。

**Comment by momdo** [comment]
metricsを「評価基準」とか「測定基準」とかにしてみる、とかですかね…？

**Comment by bakera** [comment]
「尺度」「指標」みたいな訳も考えられそうですね。

**Comment by momdo** [comment]
metricsは「指標」でいきましょうか。

ところで、これから作業する解説書の更新（#1465）で、差分が本文部分に少しあるのですが、
https://github.com/waic/w3c-wcag/compare/ca623d4..9f53597#diff-4c4e05e62e35d7a327fc58f79c29657dc0c13a75a2c6aeb210df062e7ab3c2e6

#1465 で更新するバージョンと、
https://github.com/waic/w3c-wcag/blob/master/wcag21/understanding/text-spacing.html

現在W3CにあるUnderstandingの内容は、
https://www.w3.org/WAI/WCAG21/Understanding/text-spacing 

同一です。
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fwaic%2Fw3c-wcag%2Fmaster%2Fwcag21%2Funderstanding%2Ftext-spacing.html&doc2=https%3A%2F%2Fwww.w3.org%2FWAI%2FWCAG21%2FUnderstanding%2Ftext-spacing

ここで、W3CのUnderstanding（<https://www.w3.org/WAI/WCAG21/Understanding/text-spacing>）を見ると、「metrics」で検索すると14箇所ヒットするのに対して、
<https://dev.waic.jp/translations/WCAG21/Understanding/text-spacing.html>で「メトリクス」を検索すると、4箇所しかヒットしません。

https://github.com/waic/wcag21/issues/1621#issuecomment-1457579616 でも

> うーん、このへんいろいろ怪しいですね……

と示唆されてますが、差分を脇においても明らかに「metrics」と「メトリクス」の数が合わないので、全般的に訳を見直したよい気がしてきました…。
