### ISSUE TITLE
レビュー：「フォーカス又はホバー時のコンテンツをホバー可能、非表示可能及び表示が継続されるようにする」に「検証」以降がない

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1623]
https://waic.jp/translations/WCAG21/Techniques/client-side-script/SCR39

Test（検証）以降が翻訳されていない（[原文](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR39)には存在する）。

**Comment by momdo** [comment]
これは当時の原文にはそのセクションが存在しなかったためです。
https://rawcdn.githack.com/waic/w3c-wcag/9f53597ee424516adcfa060ff47a5dc7f43a99e4/wcag21/techniques/client-side-script/SCR39.html

**Comment by momdo** [comment]
2.2テクニック集のissueで注意喚起する方向で

**Comment by momdo** [comment]
Dupe https://github.com/waic/wcag21/issues/1375
