### ISSUE TITLE
レビュー：「利用者が文字キーのショートカットを再割り当て又は無効にできるメカニズムを提供する」の達成方法の翻訳

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1625]
https://waic.jp/translations/WCAG21/Techniques/general/G217

現状:
> テスト手順については、F99: Failure of Success Criterion 2.1.4 due to implementing character key shortcuts that cannot be turned off or remapped を確認。

修正案:
> テスト手順については、F99: 達成基準 2.1.4 の失敗例－停止又は再割り当て不可能な文字キーショートカットが実装されている を確認。

リンク先は正しい（日本語なので）リンク文字列も日本語にするといいと思います。

**Comment by momdo** [comment]
https://waic.github.io/wcag21/techniques/general/G217 では翻訳済みなのでCloseとさせてください。

**Comment by jidaikobo-shibata** [comment]
あ、すみませんでした。これ、devをみてなかったようです。closeしてください。
