### ISSUE TITLE
レビュー：「達成基準 2.5.1: ポインタのジェスチャを理解する」の画像のalt

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1626]
https://dev.waic.jp/translations/WCAG21/Understanding/pointer-gestures.html

現状:
> &lt;img src="img/path-based-gesture-2.png" width="400" alt="タッチの開始を示す手、1。2 番目のポイントに移動する、2。非常にランダムな軌跡をたどる。">

修正案:
> &lt;img src="img/path-based-gesture-2.png" width="400" alt="タッチの開始を示す手。1. 2 番目のポイントに移動する、2. 非常にランダムな軌跡をたどる。">

としたほうが自然だと思います。

**Comment by momdo** [comment]
修正案が自然ではないのですが…。

**Comment by jidaikobo-shibata** [comment]
すみません。句読点を直した方がいいんでは、という指摘のつもりで、日本語は見ていませんでした。
でも、それを指摘するなら、他のaltも箇条書きのピリオドが句点になっているのは、同じページ内にもありましたね。
NVDAで読み上げてみたところ、句点のままでも、そんなにヘンでもなかったんですが、ヘンかな、とは思います。

**Comment by momdo** [comment]
```
<img src="img/path-based-gesture-2.png" width="400" 
alt="Hand showing a starting touch, 1. Going to a second point, 2. It follows a very random path.">
```
（現行訳が良し悪しはさておき、）
そもそも修正案は構造を取り違えてます。

1. Hand showing a starting touch
2. Going to a second point

It follows a very random path.

**Comment by jidaikobo-shibata** [comment]
え、マジで？ ……は〜、なるほど……。じゃあ、句点もあってるのか。

**Comment by bakera** [comment]
日本語だと番号が先の方が違和感がなさそうですね。

1、タッチの開始を示す手。2、2 番目のポイントに移動する。非常にランダムな軌跡をたどる

のようにしておきますか?
