### ISSUE TITLE
レビュー：「組み込み」「ビルトイン」「内蔵」の揺れ

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1627]
https://waic.jp/translations/WCAG21/Techniques/general/G215
この達成方法だけ、「組み込み（built-in）」を「ビルトイン」としているっぽい？

というか、
https://waic.jp/translations/WCAG21/Techniques/general/G216
では、

> when an OS level Assistive Technology (AT) like a built-in screenreader
> 内蔵のスクリーンリーダーのような OS レベルの支援技術 (AT) がオンになっている場合、

となっている箇所が

> when OS level assistive technologies (AT) like a built-in screenreader
> ビルトインのスクリーンリーダーなど OS レベルの支援技術が有効になっている場合、

となっていて、内臓だか、ビルトインだか、組み込みだか不統一みたいです。

あと、些末ですが、G215では、「assistive technologies」が初出の際の「 (AT) 」もないみたいです。

**Comment by momdo** [comment]
これはG215と216を比較して、buit-in全体に対してコメントしているのか

これはG215にフォーカスを当てて、G216と少なくとも違う、そして「（AT）」もおかしい、といっているのかどっちですか？

---

built-in
https://github.com/waic/w3c-wcag/search?q=built-in
built in
https://github.com/waic/w3c-wcag/search?p=6&q=built+in
build in
https://github.com/waic/w3c-wcag/search?p=3&q=build+in

**Comment by jidaikobo-shibata** [comment]
> これはG215にフォーカスを当てて、G216と少なくとも違う、そして「（AT）」もおかしい、といっている

こちらのつもりです。

**Comment by momdo** [comment]
原文を読み直したところ、
https://www.w3.org/WAI/WCAG21/Techniques/general/G215
https://www.w3.org/WAI/WCAG21/Techniques/general/G216

noteが
> On touch screen devices, author-supplied path-based gestures usually do not work when OS level assistive technologies (AT) like a built-in screenreader are turned on. This is because AT generally consumes a path-based gestures so they would not reach the authored content.

と途中まで同一の文言にもかかわらず、

G215の日本語訳
> タッチスクリーンデバイスでは、ビルトインのスクリーンリーダーなど OS レベルの支援技術が有効になっている場合、通常は、コンテンツ制作者が提供する軌跡ベースのジェスチャは機能しない。これは、支援技術が一般に軌跡ベースのジェスチャを使い切っており、制作されたコンテンツまでジェスチャが及ばないためである。

G216の日本語訳
> タッチスクリーンデバイスでは、内蔵のスクリーンリーダーのような OS レベルの支援技術 (AT) がオンになっている場合、コンテンツ制作者が提供する軌跡ベースのジェスチャは通常機能しない。これは、AT が一般的に軌跡ベースのジェスチャを使い尽くすため、軌跡ベースのジェスチャが作られたコンテンツに到達しないためである。

が同一の訳になっていないところが問題、と捉えました。

翻訳を見直して、以下の訳とするのはどうでしょう…？

タッチスクリーンデバイスでは、内臓のスクリーンリーダーのような OS レベルの支援技術 (AT) がオンになっている場合、通常、コンテンツ制作者が提供する軌跡ベースのジェスチャは機能しない。これは、一般的に、支援技術が軌跡ベースのジェスチャを使い尽くすことにより、ジェスチャが制作されたコンテンツに届かないためである。

**Comment by bakera** [comment]
最後の文の「使い尽くす」はわかりにくいような。とはいえconsumeをどう訳すかは難しいですね。「消化する」とか「奪う」とか?

This is because AT generally consumes a path-based gestures so they would not reach the authored content.

これは、一般的に、軌跡ベースのジェスチャを支援技術が消化してしまい、制作されたコンテンツにまで届かないためである。

とか……?

**Comment by momdo** [comment]
> 最後の文の「使い尽くす」はわかりにくいような。とはいえconsumeをどう訳すかは難しいですね。「消化する」とか「奪う」とか?

これは、ジェスチャのパターンを使い切ってしまう、言いかえるとキーボードでいえば、ショートカットキーの組み合わせを使い切ってしまうことを指していると思ったのですけど、この解釈が誤りでしょうか…？

**Comment by bakera** [comment]
続く文に例が書いてあるのですが、

>For example, a horizontal swipe gesture over the content slider will not work as intended by the author, but move the screen reader focus to the next or previous element. 

>例えば、コンテンツスライダー上で水平方向にスワイプするジェスチャは、コンテンツ制作者が意図したようには機能せず、スクリーンリーダーのフォーカスを次又は前の要素に移動させるものである。

VoiceOverが有効だと、上下スワイプはフォーカス移動の操作になります。コンテンツ側で上下スワイプによる操作を想定していても、VoiceOverがスワイプのイベントを拾ってしまうので、コンテンツ側のスワイプ操作ができないという話ですね。

**Comment by momdo** [comment]
であれば頭をひねらずに、単純に消費するでよい気がしますね…。

**Comment by bakera** [comment]
消費だとこうですかね?

これは、一般的に、軌跡ベースのジェスチャを支援技術が消費してしまい、制作されたコンテンツにまで届かないためである。
