### ISSUE TITLE
レビュー：ペルソナの心の声の約物の後にスペースが欲しい

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1628]
https://waic.jp/translations/WCAG21/Understanding/animation-from-interactions.html

些末ですが！

原文:
> Persona Quote: "Stop that extra movement! You are making me so dizzy I cannot concentrate. Now I have to turn off my computer and go lie down."

現状:
> ペルソナの心の声:「余計な動きはやめて！めまいがして集中できないわ。もうパソコンを切って横にならないと。」

こうなってほしいな:
> ペルソナの心の声:「余計な動きはやめて！　めまいがして集中できないわ。もうパソコンを切って横にならないと。」

**Comment by momdo** [comment]
@bakera 
どちらどうしましょう…？感嘆符の後にスペースを入れますか？

**Comment by jidaikobo-shibata** [comment]
根拠を明示してなかったと思って、JIS X 4051（日本語組版規則）に言及があったような気がして探したんですが、横組の根拠としては弱いですかね。

https://www.w3.org/TR/2012/NOTE-jlreq-20120403/ja/#positioning_of_dividing_punctuation_marks

**Comment by momdo** [comment]
なにがどうというわけでもないですが、jlreqはこちらが最新です
https://www.w3.org/TR/jlreq/#positioning_of_dividing_punctuation_marks

**Comment by jidaikobo-shibata** [comment]
https://waic.jp/translations/WCAG21/Techniques/general/G211
こういうのを見つけちゃうと、約物にまつわる指摘をしてるとキリがないのかもとおもいました。
> がそうだろうか？もしくは、

**Comment by momdo** [comment]
JTF日本語標準スタイルガイド第3.0版
https://www.jtf.jp/pdf/jtf_style_guide.pdf#page=27

> 3.2.1 感嘆符（！）
>
> 使用する場合は「全角」で表記します。文末に感嘆符を使用し、後に別の文が続く場合は、直後に全角スペースを挿入します。文中に感嘆符を使用する場合はスペースを挿入しません。

疑問符（？）についても同様

**Comment by bakera** [comment]
JTF日本語標準スタイルガイドによると、この場合はスペースが入るということのようですね。
ちなみに例文がこれなんですが、

>驚きの速さ！ これが新製品のキャッチコピーでした。
>おおっ！という声が上がりました。

これわかりにくいですけど基本は前者のようにスペースが入る、後者は「おおっという声」という一続きの文中なのでスペースなし、ということだと思います。ここでは文が切れているのでスペース有りかと。

ということでスペースを入れる方が良いように思いました。

**Comment by bakera** [comment]
日本語がなぜか女性っぽい訳担っているのに違和感がある、という指摘あり。
以下にしてはどうか:
「余計な動きはやめてください！　めまいがして集中できません。もうパソコンを切って横にならないと。」
