### ISSUE TITLE
レビュー：「達成基準 2.5.2: ポインタのキャンセルを理解する」の「スキートを射撃するプログラム」

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1629]
https://dev.waic.jp/translations/WCAG21/Understanding/pointer-cancellation.html

原文:
> A program for shooting skeets where waiting for the "up" event would invalidate the precise timing necessary for the activation.

現状:
> 「アップ」イベントを待つスキートを射撃するプログラムは、動作に必要な正確なタイミングを無効にするだろう。

提案:
> 「アップ」イベントを待機すると、動作に必要な正確なタイミングが無効になる、スキート射撃のプログラム。

あと、「スキート」が何なのかわからない人は多いと思うので、訳註を入れてはどうでしょうか？

ぼく自身、調べてみてもピンと来なかったのですが、「射的競技」ですかね。ゲームですよね？

https://en.wikipedia.org/wiki/Skeet_shooting

**Comment by momdo** [comment]
スキート射撃は、クレー射撃の一種らしいです。
クレー射撃 - Wikipedia 
https://ja.wikipedia.org/wiki/%E3%82%AF%E3%83%AC%E3%83%BC%E5%B0%84%E6%92%83

**Comment by jidaikobo-shibata** [comment]
シューティング（ゲーム）だと分かれば、読む人にも「アップイベントなしで動作するのが妥当」ということがわかりやすいと思います。

**Comment by bakera** [comment]
「スキート射撃のプログラム」という表現にすれば、訳注なしでもそれなりに伝わりそうな感じはしますね。

**Comment by momdo** [comment]
この訳はどうでしょう：
スキート射撃のプログラム。ここで「アップ」イベントを待ち受けると、動作に必要な正確なタイミングが無効になる。

**Comment by bakera** [comment]
なるほど2文にすると。ここでは2つの例が列挙されていて、該当の箇所は2例目なのですが、ひとつ前の例が2文で書かれているので、こちらも2文にした方が揃って読みやすい感じがしますね。
原文がこれで、

>Other examples where the timing of an activation is essential and requires the down-event would be:
>An activity that emulates a physical on-press trigger, such as when playing an on-screen piano keyboard. Activation on the up-event would significantly alter the desired behaviour.
>A program for shooting skeets where waiting for the "up" event would invalidate the precise timing necessary for the activation.

もんどさん案をはめてみると:

ある動作のタイミングが必要不可欠であり、かつダウンイベントを必要とする別の例としては、以下が挙げられる:
オンスクリーンのピアノ鍵盤の演奏時など、物理的な押下トリガーをエミュレートするアクティビティ。アップイベントでの動作は、望ましい動作を大幅に変更するだろう。
スキート射撃のプログラム。ここで「アップ」イベントを待ち受けると、動作に必要な正確なタイミングが無効になる。

文末の「だろう」の有無が異なる (どちらの文にもwouldはある) ので、そこは揃えた方が良いかもしれません。
