### ISSUE TITLE
レビュー：「ドラッグ＆ドロップ」「ドラッグ アンド ドロップ」の表記揺れ

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1630]
https://waic.jp/translations/WCAG21/Techniques/general/G210

には、「ドラッグ＆ドロップ」とある。原文は「drag-and-drop」。

他の使用状況。まあまあ、混在していますね。どうでもいいのかも。

- [site:https://waic.jp/translations/ "ドラッグ アンド ドロップ" - Google 検索](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fwaic.jp%2Ftranslations%2F+%22%E3%83%89%E3%83%A9%E3%83%83%E3%82%B0+%E3%82%A2%E3%83%B3%E3%83%89+%E3%83%89%E3%83%AD%E3%83%83%E3%83%97%22&sxsrf=AJOqlzWN8inNUCUZQxY5e3M_3HGEreELcA%3A1678006354682&ei=UlgEZMymKZGL-AaZ7pioAg&ved=0ahUKEwjMl87ltMT9AhWRBd4KHRk3BiUQ4dUDCA8&uact=5&oq=site%3Ahttps%3A%2F%2Fwaic.jp%2Ftranslations%2F+%22%E3%83%89%E3%83%A9%E3%83%83%E3%82%B0+%E3%82%A2%E3%83%B3%E3%83%89+%E3%83%89%E3%83%AD%E3%83%83%E3%83%97%22&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAVDKBFjJD2ChEmgCcAB4AIABoAGIAbsCkgEDMC4ymAEAoAEBwAEB&sclient=gws-wiz-serp): 8件
- [site:https://waic.jp/translations/ "ドラッグ＆ドロップ" - Google 検索](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fwaic.jp%2Ftranslations%2F+%22%E3%83%89%E3%83%A9%E3%83%83%E3%82%B0%EF%BC%86%E3%83%89%E3%83%AD%E3%83%83%E3%83%97%22&sxsrf=AJOqlzV4dM_EL9yeEdIXvAWsCpO3YRweXQ%3A1678006359538&ei=V1gEZJu6IImD-Aakw5mwBw&ved=0ahUKEwjbwfbntMT9AhWJAd4KHaRhBnYQ4dUDCA8&uact=5&oq=site%3Ahttps%3A%2F%2Fwaic.jp%2Ftranslations%2F+%22%E3%83%89%E3%83%A9%E3%83%83%E3%82%B0%EF%BC%86%E3%83%89%E3%83%AD%E3%83%83%E3%83%97%22&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAVC8FFi8FGCsGWgBcAB4AIABqQGIAakBkgEDMC4xmAEAoAEBwAEB&sclient=gws-wiz-serp): 20件

**Comment by momdo** [comment]
そういえば以前にも同じコメントをもらってましたね…
https://github.com/waic/wcag20/issues/186
