### ISSUE TITLE
レビュー：「達成基準 2.5.4: 動きによる起動を理解する」の「意図」の冒頭

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#1645]
https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation
原文:

> The intent of this success criterion is to ensure that functions triggered by moving a device (for example, shaking or tilting) or by gesturing towards the device (so that sensors like a camera can pick up and interpret the gesturing), can also be operated by more conventional user interface components.

https://dev.waic.jp/translations/WCAG21/Understanding/motion-actuation.html
現状:

> この達成基準の目的は、デバイスを動かすこと (例えば、振ることや傾けること) によって、又はデバイスに向かってジェスチャをする (それにより、カメラのようなセンサーがジェスチャを取得して解釈できるようになる) ことによって引き起こされる機能を確実にすることである。動きが機能にとって不可欠であるか、又は動きもしくはジェスチャを使用しないことが活動を無効にしない限り、より従来型のユーザインターフェースコンポーネントによって操作される。

翻訳が長いようです。

@momdo によると、
https://github.com/waic/w3c-wcag/commit/1a05939b6da3c9605b93d99df7249867e1a50082#diff-6e4d3220cc4934c77a4564252f410a51eb11d60d739a59ea423c27253c155edc
をみたら減ってることがわかるそうです。

**Comment by momdo** [comment]
https://github.com/waic/wcag21/issues/1498 のdiffで出ていない？箇所のようです

**Comment by momdo** [comment]
ほかにも更新箇所が出ているので、達成基準 2.5.4の更新時であわせて作業とさせてください。
