### ISSUE TITLE
解説書2.4.4 事例 原文にない括弧が補われている

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1647]
解説書の2.4.4の事例の2番目に以下のようにあります。

https://waic.jp/translations/WCAG21/Understanding/link-purpose-in-context

>あるページに、「アイルランド政府の電子選挙委員会に関する詳細を『投票に行こう！』で見る」という文がある。ここで、「投票に行こう！」がリンクである。

ここでは最初の文の「『投票に行こう！』」が二重鉤括弧で括られていますが、原文は以下の通りで、

https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context
>A page contains the sentence "Learn more about the Government of Ireland's Commission on Electronic Voting at Go Vote!" where "Go Vote!" is a link.

原文では文中の"Go Vote!"は引用符で括られていません。この有無は重要で、括弧があればそれだけでリンク先のサイトのタイトルであることがわかります。そのため、日本語版の事例の文は原文と比べて、必要以上にわかりやすくなってしまっています。
二重鉤括弧を取る必要があろうかと思います。

**Comment by momdo** [comment]
軽微な内容ですし、レビュー期間内なので、レビューコメントとして扱いましょう。。
