### ISSUE TITLE
解説書 1.4.10 文中の「参考達成方法」が日本語になっていない & 誤訳がある

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1652]
解説書 1.4.10 に以下のような文があります。

https://waic.jp/translations/WCAG21/Understanding/reflow.html
>ただし、ズームレベルを 400 ％にすると、これらの要素をビューポートの境界内に収めることができる。(Advisory Techniquesを参照)。

原文は以下です。

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html
>However, it is possible to have these elements stay within the bounds of viewport at zoom levels to 400% (see advisory techniques).

ここのadvisory techniquesというのは、同一ページ内の下の方にある "Advisory Techniques" という見出し (に属する達成方法) を指しています。日本語版では「参考達成方法」としているので、「参考達成方法」と訳す必要があります。

あと、そもそもこの文が誤訳っぽいですね。ズームレベルを400%に*すると*収めることができるのではないはずです (そもそもズームするのはユーザーであって、コンテンツ制作者ではない)。ズームレベルを400%に*しても*収めることができるという話だと思います。"stay within" なので「収めたままにする」というくらいでしょうか (はみ出していたものを収めるのではなく、収まっている状態を維持するニュアンス)。

こんな感じでしょうか……?

ただし、ズームレベルが 400 ％になっても、これらの要素をビューポートの境界内に収めたままにすることはできる (参考達成方法を参照)。

**Comment by momdo** [comment]
related #1463

**Comment by momdo** [comment]
提案いただいた修正案でよさそうです。
