### ISSUE TITLE
解説書 2.5.1 interactionの訳が「相互作用」「インタラクション」で揺れている

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1653]
https://waic.jp/translations/WCAG21/Understanding/pointer-gestures.html
>軌跡ベースのジェスチャには、終点だけでなく、相互作用も含まれる。

https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html
>A path-based gesture involves an interaction where not just the endpoints matter.  

ここではinteractionを相互作用としているのですが、下の方ではそのまま「インタラクション」としている箇所があります。

>軌跡ベースのジェスチャの例には、インタラクションの方向に応じたスワイプ、スライダー、カルーセル、及び特定の形状の描画などの指定された軌跡をトレースするその他のジェスチャが含まれる。

>Examples of path-based gestures include swiping, sliders and carousels dependent on the direction of interaction, and other gestures which trace a prescribed path such as drawing a specific shape. 

全体を見ないとなんとも言えませんが、ここに限って言えば「インタラクション」で良いように思います。

また、「終点だけでなく、相互作用も含まれる」というのは誤訳で、「終点だけではないインタラクションを含む」というのが正しいのではないでしょうか。ここでは能動的に用語を定義している文脈なので、「含まれる」ではなく「含むものである」とする方が良いように思います。matter をどう訳すかという難問もあるのですが、そこは一旦気にしないとするならこんな感じでしょうか。

軌跡ベースのジェスチャは、終点だけではないインタラクションを含むものである。

**Comment by bakera** [comment]
ちょっとまずいことに気づいてしまったような……
実はこの "not just the endpoints" というのは達成基準 2.1.1 の説明本文に出てくるやつでした。

>ただし、その根本的な機能が利用者の動作による始点から終点まで続く一連の軌跡に依存して実現されている場合は除く。
>except where the underlying function requires input that depends on the path of the user's movement and not just the endpoints.

"the path of the user's movement and not just the endpoints" を「利用者の動作による始点から終点まで続く一連の軌跡」と訳しているわけですが、原文の "not just the endpoints" では始点については触れていないわけで、これを「始点から終点まで続く」としているのは、ちょっと意訳になりすぎているかもしれません。

**Comment by bakera** [comment]
勇気を持って訳を修正する方向で。
"not just the endpoints" の訳は「終点だけではない」とする。

**Comment by momdo** [comment]
PRがマージされましたので、Closeします
