### ISSUE TITLE
用語集：シングルポインタの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1678]
Related #1653, Derived #98

https://waic.jp/translations/WCAG21/#dfn-single-pointer
> シングルポインタ (single pointer)
> シングルタップやクリック、ダブルタップやクリック、長押し及びパスを基点としたジェスチャを含む、画面と 一つの接点で動作するポインタ入力

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-single-pointer
> pointer input that operates with one point of contact with the screen, including single taps and clicks, double-taps and clicks, long presses, and path-based gestures

まず、path-basedが「パスを基点とした」という訳になっているのがおかしいですね…

### そもそも"-*based"をそのまま「ベース」としてよいのか？

https://eow.alc.co.jp/search?q=*-based
> ～に基づく、～を基盤とした、～を基礎に踏まえた、～を根拠とした、～中心の［となる］

日本語にするなら、「軌跡に基づくジェスチャ」か？

### point of contactをどう訳すか

https://eow.alc.co.jp/search?q=point+of+contact
https://ejje.weblio.jp/content/point+of+contact
「接点」というのと「接触点」というのがある。「接点」だと数学の用語を想起させると思っており、「接触点」の方がよいか？

### single taps and clicks 

中点を使うのはありか。また、includingをどう扱うべきか？「など」とするなら、「及び」「又は」は使えないことになる…

## 上記を踏まえた案

1\)
シングルタップ、シングルクリック、ダブルタップ、ダブルクリック、長押し、軌跡に基づくジェスチャなど、画面と一つの接触点で動作するポインタ入力

2\)
シングルタップ・クリック、ダブルタップ・クリック、長押し、軌跡ベースのジェスチャなど、画面と一つの接触点で動作するポインタ入力

**Comment by bakera** [comment]
「軌跡に基づくジェスチャ」「接点」「シングルタップ・クリック」のほうでいきましょう。
