### ISSUE TITLE
用語集：特定の感覚的な体験の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1679]
https://waic.jp/translations/WCAG21/#dfn-specific-sensory-experience
> 特定の感覚的な体験 (specific sensory experience)
> 純粋な装飾ではなく、かつ重要な情報の伝達、又は機能の提供を主目的としない感覚的な体験。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-specific-sensory-experience
> a sensory experience that is not purely decorative and does not primarily convey important information or perform a function

より忠実に訳すならこうか？

純粋な装飾ではなく、かつ主として重要な情報を伝達しない、又は機能を果たさない感覚的な体験。

**Comment by momdo** [comment]
Derived #98

**Comment by tsmd** [comment]
DeepL先生いわく
「純粋な装飾ではなく、重要な情報を伝えたり、機能を果たしたりすることを主としない感覚的な体験。」
「かつ」が省略されて、primarilyは両方にかかってますね

**Comment by bakera** [comment]
andは訳出しておきたいので、
「純粋な装飾ではなく、かつ重要な情報を伝えたり、機能を果たしたりすることを主としない感覚的な体験」
とする?

**Comment by caztcha** [comment]
読点を調整してみました。
「純粋な装飾ではなく、かつ、重要な情報を伝えたり機能を果たしたりすることを主としない、感覚的な体験。」

**Comment by momdo** [comment]
いろいろまとめて、これはどうか…？
純粋な装飾ではなく、かつ、重要な情報を伝える、又は機能を果たすことを主としない、感覚的な体験。
