### ISSUE TITLE
用語集：状態の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1680]
Derived #98

https://waic.jp/translations/WCAG21/#dfn-states
> 状態 (state)
例えば、フォーカス、ホバー、選択、プレス、チェック、訪問済/未訪問、展開/折りたたみなどがある。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-states

> Examples include focus, hover, select, press, check, visited/unvisited, and expand/collapse.

https://webdesk.jsa.or.jp/pdf/dev/md_5652.pdf#page=19 に従えば「/」は中点が適当に思えるけども、これに忠実に従うと、

例えば、フォーカス、ホバー、選択、プレス、チェック、訪問済、未訪問、展開、折りたたみなどがある。

「/」のままのほうがよい気もしてきた…

**Comment by bakera** [comment]
「例えば、フォーカス、ホバー、選択、プレス、チェック、訪問済・未訪問、展開・折りたたみなどがある。」でどうか?
