### ISSUE TITLE
用語集：ユーザエージェントの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1681]
Derived #98

https://waic.jp/translations/WCAG21#dfn-user-agents
> ユーザエージェント (user agent)
ウェブコンテンツを取得して利用者に提示するあらゆるソフトウェア。
ウェブブラウザ、メディアプレーヤ、プラグイン、及びその他のプログラム。その他のプログラムには、ウェブコンテンツの取得、レンダリング、やり取りを支援する支援技術を含む。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-user-agents
> any software that retrieves and presents Web content for users
Web browsers, media players, plug-ins, and other programs — including assistive technologies — that help in retrieving, rendering, and interacting with Web content.

「— including」以下の翻訳がこれでいいのか…？とくにthat以下は、「ウェブブラウザ～その他のプログラム」に係っているのでは…？つまり構造的にこうかもしれない？

ウェブコンテンツの取得、レンダリング及びやり取りを支援する、ウェブブラウザ、メディアプレーヤ、プラグイン、及び支援技術などその他のプログラム。

**Comment by bakera** [comment]
including assistive technologies が "other programs" だけにかかっているのか、"Web browsers, media players, plug-ins, and other programs" 全体にかかっているのかも謎ですね……

**Comment by bakera** [comment]
interacting はユーザーの操作をイメージしていると思うのですが、単に「やり取り」とすると誰とやり取りするのか分からず、分かりにくいように感じます。「インタラクション」というカタカナ表記の訳語が採用されている箇所もあるので、語形には目を瞑って「インタラクション」としてしまうのもアリなのではないかと思いました。

 — xxx — はカッコ書きにしてしまっても良いのではないでしょうか。たとえば:

ウェブコンテンツの取得、レンダリング及びインタラクションを支援する、ウェブブラウザ、メディアプレーヤ、プラグイン、及びその他のプログラム (支援技術も含む)。
