### ISSUE TITLE
用語集：利用者が制御可能の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1682]
Derived #98

https://waic.jp/translations/WCAG21/#dfn-user-controllable
> 利用者が制御可能 (user-controllable)
これは、インターネットのログや検索エンジンの監視データのようなものは指していない。
利用者のアカウントのための氏名と住所のフィールド。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-user-controllable
> This does not refer to such things as Internet logs and search engine monitoring data.
Name and address fields for a user's account.

こうか？

これは、インターネットのログ、検索エンジンの監視データなどを指すものではない。
利用者のアカウントのための氏名及び住所のフィールド。

**Comment by bakera** [comment]
"Name and address fields for a user's account." とだけ書いているのは何なのかと思ったら、WCAG 2.0では

https://www.w3.org/TR/WCAG20/#user-controllabledef
>Example: Name and address fields for a user's account.

となっていたのに2.1で"Example:"が抜けてしまったみたいですね。

**Comment by momdo** [comment]
> それはそれとして "search engine monitoring data" というのは何なのでしょうか……?

言われてみると謎ですね…。
