### ISSUE TITLE
用語集：映像しか含まないの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1683]
Derived #98

https://waic.jp/translations/WCAG21/#dfn-video-only
> 映像しか含まない (video-only)
映像のみを含んだ、時間に依存する提示 (音声やインタラクションを含まない)。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-video-only
> a time-based presentation that contains only video (no audio and no interaction)

修正案：
映像のみを含んだ、時間に依存する提示 (音声及びインタラクションを含まない)。

**Comment by bakera** [comment]
原文は no and no なのでどちらも含まないと分かりますが、「音声及びインタラクションを含まない」だと片方は含んでも良いように思えそうな……?
原文のカッコ書きは "only video" にくっついているので、日本語訳でもそこにくっつけた方が良いように思います。こんな感じでどうでしょうか?

映像のみを含んだ (音声もインタラクションも含まない)、時間に依存する提示
