### ISSUE TITLE
用語集：ウェブページの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1684]
Derived #98

https://waic.jp/translations/WCAG21/#dfn-web-page-s
> ウェブページ (Web page)
すべての埋め込まれている画像とメディアを含んだウェブリソース。
>
> リンク又はボタンがあり、それを押すと受信箱、アドレス帳やカレンダーを表示するが、ページのURI は全体を通して変わらない。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-web-page-s
> A Web resource including all embedded images and media.
>
> Links or buttons are provided that cause the inbox, contacts, or calendar to display, but do not change the URI of the page as a whole.

修正案：

埋め込まれているすべての画像及びメディアを含んだウェブリソース。

受信トレイ、連絡先、又はカレンダーを表示するリンク又はボタンが提供されているが、全体としてページの URI は変更されない。

**Comment by bakera** [comment]
文脈がややわかりにくいですが、用語Web pageの下の方に例として挙げられている (p[class=example]でマークアップされている) もののうち2点ですね。

>A Web resource including all embedded images and media.

>埋め込まれているすべての画像及びメディアを含んだウェブリソース。

これですが、この表現だと「埋め込まれている画像やメディアもまたWeb Pageである」とも読めてしまうように思います。
原文だと、冒頭に "A" が存在して指しているものが単体であるとわかり、「埋め込まれている画像やメディアもひっくるめて1つ」というニュアンスを出せています。
とはいえ訳し方は難しいです……たとえばですが、単数であることを強く訳出して以下のようにしてみるのはどうでしょうか……?

単体のウェブリソースであり、埋め込まれている画像及びメディアをすべて含んだもの

>Links or buttons are provided that cause the inbox, contacts, or calendar to display, but do not change the URI of the page as a whole.

>受信トレイ、連絡先、又はカレンダーを表示するリンク又はボタンが提供されているが、全体としてページの URI は変更されない。

原文末尾の  as a whole は文全体にかかるのか、page だけにかかるのか、どちらともとれますね……。文全体にかかると読むならご提案のようになるでしょうし、pageだけにかかると読むなら「ページ全体のURIは変更されない」となりそうです。どちらでも意味は通じますし、例なのでどちらでも良いとも言え、ご提案のままで良いかと思います。
