### ISSUE TITLE
用語集：アクセシビリティ サポーテッドの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1685]
Derived #98

アクセシビリティ サポーテッド (accessibility supported)について、全体的に見直してみました。
> 現在のWCAG 2.1
> 原文

提案訳

の順番です。

https://waic.jp/translations/WCAG21/#dfn-accessibility-supported
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-accessibility-supported

アクセシビリティ サポーテッド (accessibility supported)

> 利用者の支援技術と、ブラウザ及びその他のユーザエージェントにあるアクセシビリティ機能でサポートされていること。
supported by users' assistive technologies as well as the accessibility features in browsers and other user agents

利用者の支援技術だけでなく、ブラウザ及びその他のユーザエージェントにあるアクセシビリティ機能でサポートされていること。 

> あるウェブコンテンツ技術 (あるいは、ある技術の機能) の使用方法がアクセシビリティ サポーテッドであると認められるためには、そのウェブコンテンツ技術 (あるいは、機能) について、次の 1.と 2.の両方が満たされていなければならない:
To qualify as an accessibility-supported use of a Web content technology (or feature of a technology), both 1 and 2 must be satisfied for a Web content technology (or feature):

あるウェブコンテンツ技術 (又は、ある技術の機能) のアクセシビリティ サポーテッドな使用方法とみなされるためには、そのウェブコンテンツ技術 (又は機能) について、次の 1.と 2.の両方が満たされていなければならない:

> そのウェブコンテンツ技術の使用方法が、利用者の支援技術によりサポートされていなければならない。これは、その技術の使用方法が、そのコンテンツの自然言語における利用者の支援技術との相互運用性について検証されていることを意味する。
The way that the Web content technology is used must be supported by users' assistive technology (AT). This means that the way that the technology is used has been tested for interoperability with users' assistive technology in the human language(s) of the content,

（ママ）

> そのウェブコンテンツ技術には、アクセシビリティ サポーテッドで、利用者が利用できるユーザエージェントがなければならない。これは、少なくとも次の四つのうち一つを満たしていることを意味する:
The Web content technology must have accessibility-supported user agents that are available to users. This means that at least one of the following four statements is true:

そのウェブコンテンツ技術には、利用者が入手できるアクセシビリティ サポーテッドなユーザエージェントがなければならない。これは、次の四つのうち少なくとも一つを満たしていることを意味する:

> その技術が (HTML や CSS のように)、広く配布されているアクセシビリティ サポーテッドなユーザエージェントに標準でサポートされている。
The technology is supported natively in widely-distributed user agents that are also accessibility supported (such as HTML and CSS);

その技術が (HTML、CSS のような) アクセシビリティ サポーテッドであり、広く配布されているアクセシビリティ サポーテッドなユーザエージェントに標準でサポートされている。

> その技術が、広く配布されているアクセシビリティ サポーテッドなプラグインでサポートされている。
The technology is supported in a widely-distributed plug-in that is also accessibility supported;

（ママ）

> そのコンテンツが、大学あるいは企業内ネットワークのような閉じた環境で利用できるものであり、その技術に必要とされていて、その組織で使用されているユーザエージェントがアクセシビリティ サポーテッドである。
The content is available in a closed environment, such as a university or corporate network, where the user agent required by the technology and used by the organization is also accessibility supported;

そのコンテンツが、大学、企業内ネットワークのような閉じた環境で利用できるものである。この環境で、その技術に必要とされていて、その組織で使用されているユーザエージェントがアクセシビリティ サポーテッドである。

> その技術をサポートするユーザエージェントが、アクセシビリティ サポーテッドであって、次のようにダウンロードあるいは購入できる:
The user agent(s) that support the technology are accessibility supported and are available for download or purchase in a way that:

その技術をサポートするユーザエージェントが、アクセシビリティ サポーテッドであって、次の方法でダウンロード又は購入できる:

> 障害のある人に障害のない人よりも時間や労力がかかるようなことはなく、かつ、
障害のある人も障害のない人と同じくらい容易に探して入手することができ
does not cost a person with a disability any more than a person without a disability and
is as easy to find and obtain for a person with a disability as it is for a person without disabilities.

障害のある人の費用が、障害のない人の費用と同程度であり、かつ、
障害のある人も、障害のない人と同程度に容易に探して入手できる。

> WCAG Working Group ならびに W3C は、あるウェブ技術のある特定の使用方法がアクセシビリティ サポーテッドであると分類するために、そのウェブ技術の特定の使用方法に対して、どの支援技術によるどれだけのサポートが必要なのかを定めない(Level of Assistive Technology Support Needed for "Accessibility Support"を参照)。
The WCAG Working group and the W3C do not specify which or how much support by assistive technologies there must be for a particular use of a Web technology in order for it to be classified as accessibility supported. (See Level of Assistive Technology Support Needed for "Accessibility Support".)

WCAG Working Group 及び W3C は、あるウェブ技術の特定の使用方法がアクセシビリティ サポーテッドであると分類するために、どの支援技術によるどれだけのサポートが必要なのかを定めない (Level of Assistive Technology Support Needed for "Accessibility Support"を参照)。

> コンテンツ制作者が技術のアクセシビリティ サポーテッドな使用方法を見つける方法の一つは、アクセシビリティ サポーテッドであることが文書化されている使用方法の資料を参考にすることである(Understanding Accessibility-Supported Web Technology Uses を参照)。コンテンツ制作者、企業、技術ベンダー、あるいはその他の者が、ウェブコンテンツ技術のアクセシビリティ サポーテッドな使用方法を文書化してもよい。しかし、文書中の技術の使用方法すべては、前述のアクセシビリティ サポーテッドなウェブコンテンツ技術の定義を満たしている必要がある。
One way for authors to locate uses of a technology that are accessibility supported would be to consult compilations of uses that are documented to be accessibility supported. (See Understanding Accessibility-Supported Web Technology Uses.) Authors, companies, technology vendors, or others may document accessibility-supported ways of using Web content technologies. However, all ways of using technologies in the documentation would need to meet the definition of accessibility-supported Web content technologies above.

コンテンツ制作者が技術のアクセシビリティ サポーテッドな使用方法を見つける方法の一つは、アクセシビリティ サポーテッドであることが文書化されている使用方法の資料を参照することである (Understanding Accessibility-Supported Web Technology Uses を参照)。コンテンツ制作者、企業、技術ベンダー、又はその他の者が、ウェブコンテンツ技術のアクセシビリティ サポーテッドな使用方法を文書化してもよい。しかし、文書中の技術の使用方法はすべて、上記のアクセシビリティ サポーテッドなウェブコンテンツ技術の定義を満たしている必要がある。

**Comment by bakera** [comment]
>The technology is supported natively in widely-distributed user agents that are also accessibility supported (such as HTML and CSS);
>その技術が (HTML、CSS のような) アクセシビリティ サポーテッドであり、広く配布されているアクセシビリティ サポーテッドなユーザエージェントに標準でサポートされている。

ここのカッコ書きは "accessibility supported" だけにくっついているのではなく、文全体を修飾しているように思います (この文全体の言っていることに当てはまる例としてHTMLとCSSを挙げている)。こうでしょうか。

その技術がアクセシビリティ サポーテッドであり、広く配布されているアクセシビリティ サポーテッドなユーザエージェントに標準でサポートされている (HTML、CSS のように)。

**Comment by momdo** [comment]
@bakera 

コメントありがとうございます。いただいた箇所は後ほど確認しますが、他にコメント箇所はありますか？

**Comment by bakera** [comment]
他だいたいOKです、と思っていたのですが1つ追加で。

>does not cost a person with a disability any more than a person without a disability and
>is as easy to find and obtain for a person with a disability as it is for a person without disabilities.

>障害のある人の費用が、障害のない人の費用と同程度であり、かつ、
>障害のある人も、障害のない人と同程度に容易に探して入手できる。

does not cost ... any more than を「同程度」としていますが、上回らなければ良い (障害のある人の方がコストが低い場合はOK) ということかと思います。「障害のない人の費用と同程度かそれ以下」もしくは「障害のない人の費用を上回ることがなく」くらいでしょうか。 
(後半の as easy as は「同程度に容易に」で問題ないと思います)

他は問題ないかと思います。

**Comment by bakera** [comment]
「翻訳に関するコメント (Google フォーム)」に統一する方向で。
