### ISSUE TITLE
解説書3.2.2 「利用者のために留まる」とは?

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1710]
解説書3.2.2の事例の箇所に以下のようにあります。

https://waic.jp/translations/WCAG21/Understanding/on-input.html
>エントリーの部分だけが変化し、全体の構造は同じままなので、基本的なコンテキストは利用者のために留まる。

「利用者のために留まる」というのはちょっと意味が不明な文になっているように思います。
原文は以下のとおりです。

https://www.w3.org/WAI/WCAG21/Understanding/on-input.html
> Because only parts of the entry change and the overall structure remains the same the basic context remains for the user.

原文がだいぶ読みにくいですが、おそらく以下のように切れています。

(理由) Because only parts of the entry change and the overall structure remains the same 
(結論) the basic context remains for the user.

こんな感じでしょうか?

エントリーの一部だけが変化し、全体の構造は同じままであるため、その利用者にとっての基本的なコンテキストは残っている。

remainの訳が悩ましいです。"remains the same" は同じまま、変わらないという慣用句的な言い回しなので、ここと後ろの remains の訳は違っていても良いとは思いますが、あえて同じにしても良いのかもれません。

**Comment by momdo** [comment]
「変化しない」と取るのはどうでしょう？

エントリーの一部だけが変化し、全体の構造は変化しないため、その利用者に基本的なコンテキストは残っている。
