### ISSUE TITLE
解説書1.3.3 「下記」「下」と表記が揺れている

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#1711]
解説書の1.3.3の解説に以下のような記述があります。

https://waic.jp/translations/WCAG21/Understanding/sensory-characteristics.html
>ある言語においては、「上記」はコンテンツのその地点よりも前にあるコンテンツを指し、「下記」はその地点よりも後にあるコンテンツを指すことが共通理解となっている。そのような言語では、参照されているコンテンツが読み上げ順序の中で適切な位置にあり、かつ参照が明確ならば、「下のリンクのいずれかを選択する」または「上記のすべてを選択する」などの文はこの達成基準に適合するだろう。

先の文では「下記」と言っていますが、続く文の例では「下のリンク」と言っていて表現が揺れています。原文を見るとどちらも "below" であるようです。

https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics.html

>In some languages, it is commonly understood that "above" refers to the content previous to that point in the content and "below" refers to the content after that point. In such languages, if the content being referenced is in the appropriate place in the reading order and the references are unambiguous, statements such as "choose one of the links below" or "all of the above" would conform to this Success Criterion.

すべてを「上記」「下記」とするか、「上」「下」とするか、もしくは「以上」「以下」などとするか、いろいろ択はあると思いますが、いずれにせよ統一した方が良いかと思います。

**Comment by momdo** [comment]
「下記」で統一でよいかと思います。
