### ISSUE TITLE
用語集：支援技術の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1720]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-assistive-technologies
> (この文書で用いられている) 支援技術 (assistive technology (as used in this document))
ユーザエージェントとしてふるまうか、もしくは主流のユーザエージェントと共に用いられ、障害のある利用者が必要とする、主流のユーザエージェントが提供する以上の機能を提供するためのハードウェア及び／又はソフトウェア。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-assistive-technologies
> hardware and/or software that acts as a user agent, or along with a mainstream user agent, to provide functionality to meet the requirements of users with disabilities that go beyond those offered by mainstream user agents

案：
ユーザエージェントとして、又は主流のユーザエージェントと共に動作し、主流のユーザエージェントによって提供されるものを超える、障害のある利用者の要件を満たす機能を提供するハードウェア及び／又はソフトウェア。

>スクリーンリーダー。全盲の人がテキスト情報を合成音声あるいは点字で読み取るために使用している。
>
> screen readers, which are used by people who are blind to read textual information through synthesized speech or braille;

案：
スクリーンリーダー。全盲の人がテキスト情報を合成音声又は点字で読み取るために使用している。

**Comment by bakera** [comment]
>hardware and/or software that acts as a user agent, or along with a mainstream user agent, to provide functionality to meet the requirements of users with disabilities that go beyond those offered by mainstream user agents

>ユーザエージェントとして、又は主流のユーザエージェントと共に動作し、主流のユーザエージェントによって提供されるものを超える、障害のある利用者の要件を満たす機能を提供するハードウェア及び／又はソフトウェア。

「動作し」がどこにかかるのかわかりにくく、意味が取りにくいように感じました (「動作し…提供される」とも「動作し…提超える」とも「動作し…提供する」ともとれる)。原文からして意味が取りにくいので仕方ないとは思うんですが……

ちょっと語順を変えてこんな感じにすると多少わかりやすくなりますでしょうか……?

ハードウェア及び／又はソフトウェアであり、障害のある利用者に必要とされる、主流のユーザエージェントが提供する以上の機能を提供するために、ユーザエージェントとして動作するか、又は主流のユーザエージェントと共に動作するもの

**Comment by momdo** [comment]
もう少し練って、こういうのはどうでしょうか。。

障害のある利用者の要件を満たすために、主流のユーザエージェントが提供する機能を超えた機能を提供するような、ユーザエージェントとして動作する、又は主流のユーザエージェントと共に動作するハードウェア及び／又はソフトウェア。

あるいは、単純に「ハードウェア及び／又はソフトウェア」を先頭に持ってくるならばこうでしょうか。

ハードウェア及び／又はソフトウェアであって、障害のある利用者の要件を満たすために、主流のユーザエージェントが提供する機能を超えた機能を提供するような、ユーザエージェントとして動作する、又は主流のユーザエージェントと共に動作するもの。

**Comment by bakera** [comment]
もんどさん案の前者の方がよさそうに思いました!
(正直、読めば読むほどゲシュタルト崩壊して訳がわからなくなってきますね……)
