### ISSUE TITLE
用語集：適合の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1721]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-conform
> 適合 (conformance)
与えられた規格、ガイドライン、あるいは仕様のすべての要件を満たすこと

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-conform
> satisfying all the requirements of a given standard, guideline or specification

案：
与えられた規格、ガイドライン、又は仕様のすべての要件を満たすこと。

**Comment by bakera** [comment]
よろしいかと思います!
