### ISSUE TITLE
用語集：コンテンツ (ウェブコンテンツ)の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1723]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-content
> コンテンツ (ウェブコンテンツ) (content (Web content))
> ユーザエージェントによって利用者に伝達される情報及び感覚的な体験。コンテンツの構造、提示、及びインタラクションを定義するコードやマークアップを含む。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-content
> information and sensory experience to be communicated to the user by means of a user agent, including code or markup that defines the content's structure, presentation, and interactions

案：
コンテンツの構造、提示、及びインタラクションを定義するコード又はマークアップを含めた、ユーザエージェントによって利用者に伝達される情報及び感覚的な体験。

**Comment by momdo** [comment]
あるいは

コンテンツの構造、提示、及びインタラクションを定義するコード又はマークアップも含めて、ユーザエージェントによって利用者に伝達される情報及び感覚的な体験。

とするとか？

**Comment by momdo** [comment]
もしくは読点の位置を変えてこうか？

コンテンツの構造、提示、及びインタラクションを定義するコード又はマークアップを含めたユーザエージェントによって、利用者に伝達される情報及び感覚的な体験。

**Comment by bakera** [comment]
>コンテンツの構造、提示、及びインタラクションを定義するコード又はマークアップも含めて、ユーザエージェントによって利用者に伝達される情報及び感覚的な体験。

これがよさそうに思いました。
