### ISSUE TITLE
用語集：正しく読む順序の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1724]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-correct-reading-sequence
>正しく読む順序 (correct reading sequence)
コンテンツの意味を変更せずに、単語や段落が提示される順序。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-correct-reading-sequence
>any sequence where words and paragraphs are presented in an order that does not change the meaning of the content

案（「や」だけ修正したもの）：
コンテンツの意味を変更せずに、単語及び段落が提示される順序。

https://github.com/waic/wcag21/issues/1535に出てきた、sequenceの案で置き換えてみる

案1「連なり」
正しく読む連なり
コンテンツの意味を変更せずに、単語及び段落が提示される連なり。

案2「連続」
正しく読む連続
コンテンツの意味を変更せずに、単語及び段落が提示される連続。

案3「シーケンス」
正しく読むシーケンス
コンテンツの意味を変更せずに、単語及び段落が提示されるシーケンス。

案4「流れ」
正しく読む流れ
コンテンツの意味を変更せずに、単語及び段落が提示される流れ。

案5「一続き」
正しく読む一続き
コンテンツの意味を変更せずに、単語及び段落が提示される一続き。

案6「順番」
正しく読む順番
コンテンツの意味を変更せずに、単語及び段落が提示される順番。

**Comment by momdo** [comment]
漢語はあまりしっくりこないかもしれませんね。。

**Comment by bakera** [comment]
「連なり」「シーケンス」のどちらかが有力か

「シーケンス」がどこまで一般的な用語なのか。コンピュータに詳しい人はわかるだろうが……
とはいえ他の用語はどれもしっくりこないので、いったん「シーケンス」としてみてはどうか。
