### ISSUE TITLE
用語集：ダウンイベントの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1725]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-down-event

> ダウンイベント (down-event)
> ポインタのトリガが押された時に生じるプラットフォームイベント。
> ダウンイベントは、プラットフォームによっては「タッチスタート」や「マウスダウン」などの異なる名称で呼ばれる場合がある。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-down-event
> platform event that occurs when the trigger stimulus of a pointer is depressed
> The down-event may have different names on different platforms, such as "touchstart" or "mousedown".

案：
ポインタのトリガ刺激が押された時に発生するプラットフォームのイベント。
ダウンイベントは、「touchstart」「mousedown」など、プラットフォームによって異なる名前を持つ場合がある。

イベント名を英語に戻してみたがどうか…？

**Comment by bakera** [comment]
これですが、

>ポインタのトリガ刺激が押された時に発生するプラットフォームのイベント。

the trigger stimulus of a pointer is depressed を `(the trigger stimulus of a pointer) is depressed` と解釈していると思うのですが (元の訳も)、 `the trigger stimulus of (a pointer is depressed)` ではないでしょうか。

ポインタが押されたというトリガ刺激の際に発生するプラットフォームのイベント。

であるように思います。
後半のイベント名を英語にするのはそれでOKかと。

**Comment by bakera** [comment]
いやこれ文法的には元の解釈で正しいような気がしてきました。「トリガ刺激が"depressed"というステータスになった時」という意味ですね。「トリガ刺激が押された時」というのは少し変なので、

ポインタのトリガ刺激がdepressed(押された)となった際に発生するプラットフォームのイベント。

というくらいでどうでしょう……?

**Comment by jidaikobo-shibata** [comment]
https://github.com/waic/wcag22/issues/1449 で決着しています。

> ポインタが押し下げられたというトリガー刺激の際に発生するプラットフォームのイベント。
