### ISSUE TITLE
用語集：緊急の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1726]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-emergency

> 緊急 (emergency)
> 健康、安全や財産を守るために直ちに行動をとる必要のある、突然で予期されなかった状況あるいは出来事。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-emergency
> a sudden, unexpected situation or occurrence that requires immediate action to preserve health, safety, or property

A案 ：これまでの訳を活かす
健康、安全又は財産を守るために直ちに行動をとる必要のある、突然で予期されなかった状況又は出来事。
B案：少し変更
健康、安全、又は財産を守るために即座の行動を必要とする、突然で予期しない状況又は出来事。

**Comment by bakera** [comment]
A,Bどちらでも良いと思いますがB案の方が日本語としては違和感なくこなれているように思いますので、Bに1票で。
