### ISSUE TITLE
用語集：自然言語 の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1727]
Derived https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-human-language-s
> 自然言語 (human language)
> 人間とコミュニケーションをとるための言語で、話される、書かれる、又は (視覚的あるいは触覚的な手段で) 手話にされるもの。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-human-language-s
> language that is spoken, written or signed (through visual or tactile means) to communicate with humans

案：
人間と意思の疎通をするために言語で、話される、書かれる、又は (視覚的もしくは触覚的な手段で) 手話にされるもの。

コミュニケーションを訳してみたがどうか。

**Comment by bakera** [comment]
「コミュニケーション」はARIA8, G54, G81, H69などで使われていますが、「疎通」という語はどこにも使われていないようで、他と揃えるという観点で言えば「コミュニケーション」のほうが優勢であるように思います。

訳全体としてみると、ここは用語説明であり「言語である」というのが結論になるところです。「……であるような言語」とか「言語であり、……であるようなもの」という訳し方にするのが良いように思います。以下のような感じでどうでしょうか。

人間とコミュニケーションをとるために話される、書かれる、又は (視覚的もしくは触覚的な手段で) 手話にされる言語。
