### ISSUE TITLE
用語集：モーションアニメーションの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1763]
related #98

https://waic.jp/translations/WCAG21/#dfn-motion-animation
> モーションアニメーション (motion animation)
動いているような錯覚やスムーズに移動しているように感じさせるために作る、状態と状態の間にステップを加えること。
例えば、別の場所に移動したりサイズが変わる要素はアニメーションしていると考えられる。推移せずに即座に表示される要素は、アニメーションを用いていない。モーションアニメーションには、色、ぼかし又は不透明度の変更は含まれない。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-motion-animation
> addition of steps between conditions to create the illusion of movement or to give a sense of a smooth transition
For example, an element which moves into place or changes size while appearing is considered to be animated. An element which appears instantly without transitioning is not using animation. Motion animation does not include changes of color, blurring or opacity.

案：
動きの錯覚を作り出すため、又は滑らかに変化する感覚を与えるための状態間のステップを追加すること。
例えば、表示中に所定の位置に移動する、又はサイズを変更する要素は、アニメーション化されていると見なされる。遷移せずに即座に表示される要素は、アニメーションを用いていない。モーションアニメーションには、色、ぼかし、又は不透明度の変更は含まれない。

**Comment by bakera** [comment]
(とりあえずの感想)
動詞animateを「アニメーション化する」と訳すのは違和感がありますね……。
かとといってここだけ「動かす」「操る」のようにすると、それはそれでアニメーションとの関係がわかりにくい。
「アニメーションする」もよくよく考えると違和感がある、というのもそれはそれでわかるのですが、なんだかんだ日常で「アニメーションする」と表現することはあると思うので、「アニメーション化する」よりは良いような気がしています。

transitioning → 遷移、というのもわかりにくいかも。CSSを触っている人ならtransitionでそのまま通じると思うのですが、とはいえ、うーんという感じ。これはどうするか難しいですね。

**Comment by momdo** [comment]
<https://www.w3.org/TR/2023/REC-WCAG21-20230921/#dfn-motion-animation>では例が少し追記されています。

> addition of steps between conditions to create the illusion of movement or to give a sense of a smooth transition
> 
> EXAMPLE 14
> For example, an element which moves into place or changes size while appearing is considered to be animated. An element which appears instantly without transitioning is not using animation. Motion animation does not include changes of color, blurring, or opacity which do not change the perceived size, shape, or position of the element.

<https://waic.jp/translations/WCAG21/Understanding/animation-from-interactions.html#key-terms>では次のようにしています。

> 動いているような錯覚やスムーズに移動しているように感じさせるために作る、状態と状態の間にステップを加えること。
>
> 例えば、別の場所に移動したりサイズが変わる要素はアニメーションしていると考えられる。推移せずに即座に表示される要素は、アニメーションを用いていない。モーションアニメーションには、知覚される要素のサイズ、形状、もしくは位置を変えないような、色、ぼかし又は不透明度の変更は含まれない。

**Comment by momdo** [comment]
ということで、以下はどうか。

状態間のステップを追加することで、動きの錯覚を作り出す、又は滑らかな変化の感覚を与えるもの。
例えば、出現中に特定の位置に移動する、又はサイズを変更する要素は、アニメーションにされているとみなされる。変化せずに即座に出現する要素は、アニメーションを用いていない。モーションアニメーションには、要素の知覚されるサイズ、形状、又は位置を変更しない、色、ぼかし、又は不透明度の変更は含まれない。

**Comment by bakera** [comment]
細かいところですが……

1文目の主語は "addition" で、「追加」「追加すること」「追加する行為」というような言い方になるべきかもしれません。WCAG本文側では2.3.3 Animation from Interactionsで使われていて、

>Motion animation triggered by interaction can be disabled, unless the animation is essential to the functionality or the information being conveyed.

モーションアニメーションをdisabled にできることが達成基準の要求になっています。これをdisabledにすると、スムーズなアニメーションなしでぱっと切り替わることになります。ここではステップ間にコマを追加する行為をモーションアニメーションと呼んでいるのだと思います。


"the illusion of movement" は the がついているので専門用語と思われます。動いていないのに動いているように見えるタイプの錯視をそう呼ぶようです ("the illusion of movement" で画像検索するといっぱい出てくる )。日本語では「動的錯視」と訳されたりするようです。「動きの錯覚」でダメということではないのですが、ニュアンスとしては「動いていないのに動いているかのように見える錯視」という感じのようです。


appears ですが、日本語で「出現中」とすると「出現した後、出現している状態になっている」というニュアンスにも読めて悩ましいところです。また、続く文では appears を「出現する」としています。ここでは「出現しながら」というくらいでしょうか。


transitioning を「変化」としていますが、ここは「ぱっと変化する」と「徐々に変化する」の違いが重要になる文脈で、transitioning は後者なので「変化」ではない言葉の方がいいかもしれません。「遷移」とするか、あるいは「徐々に変化」のようにするか。


最後の文は「変更しない、……含まれない」となっていて、少し読みにくいように感じます。これはまあ原文がそうなんですが……。このあたりは語順を変えると多少読みやすくになるかもしれません。語順の話で言うと、「……や……の要素は、」のように頭に長い修飾句がついているものも読みにくく、「要素が……や……の場合」とすると読みやすくなるように思います。


そんなわけでたとえばこんな感じではどうでしょうか?

動いているような錯視を作り出す、又は滑らかに変化しているような感覚を与えるために、状態間にステップを追加すること。
例えば、要素が出現しながら特定の位置に移動する、又はサイズを変更する場合、アニメーションされているとみなされる。要素が遷移せずに即座に出現する場合は、アニメーションを用いていない。色、ぼかし、又は不透明度の変更で、要素の見た目のサイズ、形状、又は位置を変更しないものは、モーションアニメーションには含まれない。

**Comment by momdo** [comment]
コメントありがとうございます。

illusionについては、あとで「感覚」という語が出てきますので、「錯視」と取るよりかは「錯覚」としたほうが釣り合いが取れるかと思います。
ただ、モーションアニメーションは、「こと」というよりかは「もの」だとは思います。

EXAMPLE 14については、結局のところ何が（モーション）アニメーションなのかの例示だと理解しています。
それをふまえて、For example,で始まる文については、「アニメーションだとみなされる」というように取るのではどうでしょうか。
また、「要素」を文頭に置くなら不定冠詞をあえて訳した方がよさそうです。

2文目は、「要素が…アニメーションを用いていない。」だとすわりが悪い気はしますね…
「要素は、アニメーションを用いていない。」のほうがよい気はしますが…「場合」で対比させるならばママになりますか。

最終の文は、WCAG 2.1 (2018)が

> Motion animation does not include changes of color, blurring or opacity.

という文だったのを長々と付け加えて

> Motion animation does not include changes of color, blurring, or opacity which do not change the perceived size, shape, or position of the element.

にしたわけですから、which以下はchanges of color, blurring, or opacityの説明になるはずです。ですから、おおまかな意味としては、

（要素の見た目のサイズ、形状、又は位置の変化ではない）色、ぼかし、又は不透明度の変化は、モーションアニメーションではない。

というようになるはずです。

…ということで、以下だとどうでしょうか。

A案：
動いているような錯覚を作り出す、又は滑らかに遷移しているような感覚を与えるために、状態間にステップを追加するもの。
例えば、ある要素が出現しながら特定の位置に移動する、又はサイズが変化する場合、アニメーションであるとみなされる。要素が遷移せずに即座に出現する場合は、アニメーションを用いていない。要素の見た目のサイズ、形状、又は位置の変化が生じない、色、ぼかし、又は不透明度の変化は、モーションアニメーションには含まれない。

あるいは、さらにいろいろと手を加えたB案：
状態間のステップを追加することで、動いているような錯覚を作り出す、又は滑らかな変化の感覚を与えるもの。
例えば、出現する間に特定の位置に移動する、又はサイズが変化する要素は、アニメーションであるとみなされる。遷移せずに即座に出現する要素は、アニメーションが使用されていない。要素の見た目のサイズ、形状、又は位置の変化が生じない、色、ぼかし、又は不透明度の変化は、モーションアニメーションには含まれない。

**Comment by bakera** [comment]
ありがとうございます。個人的にはA案の方がしっくりきます。

「状態間にステップを追加するもの」という部分ですが、原文の意味としてはモーションアニメーションは "addition" であるという定義で、「モーションアニメーションとは追加である」というニュアンスになります (それ自体に違和感があるというのもありそうですが、ともあれ原文の意味としてはそう)。
先のコメントでは「追加すること」と書きましたが、ここではどちらかというと「追加された部分」というニュアンスのように思えます。忠実にやるなら、

動いているような錯覚を作り出す、又は滑らかに遷移しているような感覚を与えるための、状態間へのステップの追加。

という感じかと思います。違和感があるなら、単に「追加するもの」→「追加したもの」として以下のようにしても良いと思いました。

動いているような錯覚を作り出す、又は滑らかに遷移しているような感覚を与えるために、状態間にステップを追加したもの。

いかがでしょうか。

**Comment by momdo** [comment]
前者がよさそうですね。プルリクを作ります。
