### ISSUE TITLE
用語集：プログラムによる解釈が可能なリンクのコンテキストの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1764]
related https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-programmatically-determined-link-context
> プログラムによる解釈が可能なリンクのコンテキスト (programmatically determined link context)
HTML では、英語で記述されたリンクからプログラムによる解釈が可能な情報には、そのリンクと同じ段落、リスト、又はテーブルのセルにあるテキスト、あるいはリンクのあるテーブルのセルと関連付けられたテーブルの見出しセルにあるテキストなどがある。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-programmatically-determined-link-context
> In HTML, information that is programmatically determinable from a link in English includes text that is in the same paragraph, list, or table cell as the link or in a table header cell that is associated with the table cell that contains the link.

案：
HTML では、英語のリンクからプログラムによる解釈が可能な情報には、そのリンクと同じ段落、リスト、又はテーブルのセル内のテキスト、もしくはリンクを含むテーブルのセルに関連付けられたテーブルのヘッダーセル内のテキストが含まれる。

**Comment by bakera** [comment]
「英語のリンク」とは? なぜ英語?

**Comment by bakera** [comment]
あー、これ例なのにそう明記されていないせいでわかりにくくなっているやつですね。
例であることがわかりやすいような訳し方ができるといいのかもしれません。

**Comment by bakera** [comment]
「リンクを含むテーブルのセルに関連付けられたテーブルのヘッダーセル内のテキスト」も修飾関係がわかりにくい感じがします。というかこの原文自体、that が 3回、or が2回出現していてやばいですね……。文章を分割した方が間違いなくわかりやすくなるとは思うんですが、悩ましい。
あと、includes を「挙げられる」と訳したらわかりやすいかも? と思いつつ、たとえばこんな感じでどうでしょうか。

HTML において、英語で書かれたリンクからプログラムによる解釈が可能な情報には、そのリンクと同じ段落、リスト、又はテーブルのセル内にあるテキスト、又はテーブル内のリンクを含むセルに関連付けられたヘッダーセル内のテキストが挙げられる。

**Comment by momdo** [comment]
いただいた案で基本行こうと思いますが

(そのリンクと同じ段落、リスト、もしくはテーブルのセル内にあるテキスト)、又は(テーブル内のリンクを含むセルに関連付けられたヘッダーセル内のテキスト)

となる…？

**Comment by bakera** [comment]
そうです。原文を分析するとこんな感じで、

- text that is
  - (in the
      - (same paragraph, list, or table cell)
  - as the link)
- or
  - (in a table header cell (that is associated with the table cell that contains the link.))

textが1つしかないのを補ってしまっているので、そこをきちんと原文に揃えるならこう?

HTML において、英語で書かれたリンクからプログラムによる解釈が可能な情報には、そのリンクと同じ段落、リスト、又はテーブルのセル内にあるか、又はテーブル内のリンクを含むセルに関連付けられたヘッダーセル内のテキストが挙げられる。

いずれにせよわかりにくいですが……
