### ISSUE TITLE
用語集：手話通訳の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1765]
related: #98

https://waic.jp/translations/WCAG21/#dfn-sign-language-interpretation
> 手話通訳 (sign language interpretation)
ある言語、通常は発話された言葉を、手話に訳すこと。
注記
手話は、本来、同じ国や地域で話されている言葉とは関係がない独立したものである。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-sign-language-interpretation
> translation of one language, generally a spoken language, into a sign language
NOTE
True sign languages are independent languages that are unrelated to the spoken language(s) of the same country or region.

案：

ある言語、通常は話し言葉を、手話に訳すこと。
注記
純粋な手話は、同じ国又は地域の話し言葉とは関係がない独立したものである。

**Comment by bakera** [comment]
日本語で「話し言葉」というと「書き言葉」の対義語、会話でしか使わない言葉というようなニュアンスで受けとられることが多いように思います。ここでは「話された言葉」くらいでもいいのかもしれませんがどうでしょうか。

あとlanguageが言語/言葉で揺れているのは少し気になりますが、無理に揃える必要もないですかね?

**Comment by momdo** [comment]
> 無理に揃える必要もないですかね?

どちらでもいいと思いますが、揃えるとなるとこうでしょうか？

ある言語、通常は話されている言語を、手話に訳すこと。
注記
純粋な手話は、同じ国又は地域の話されている言語とは関係がない独立したものである。

**Comment by bakera** [comment]
良いと思います!
