### ISSUE TITLE
用語集：状態の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1766]
related: #98

https://waic.jp/translations/WCAG21/#dfn-states
> 状態 (state)
利用者のアクション又は自動プロセスに応答して変化し得るユーザインタフェースコンポーネントの特性を表現する動的特性。
状態はコンポーネントの性質に影響を与えないが、コンポーネントやインタラクションの可能性に関連付けられているデータを表す。例えば、フォーカス、ホバー、選択、プレス、チェック、訪問済・未訪問、展開・折りたたみなどがある。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-states
> dynamic property expressing characteristics of a user interface component that may change in response to user action or automated processes
States do not affect the nature of the component, but represent data associated with the component or user interaction possibilities. Examples include focus, hover, select, press, check, visited/unvisited, and expand/collapse.

案：
利用者のアクション又は自動プロセスに応答して変化し得るユーザインタフェースコンポーネントの特性を表現する動的プロパティ。
状態はコンポーネントの性質に影響を与えないが、コンポーネント又はインタラクションの可能性に関連付けられているデータを表す。例えば、フォーカス、ホバー、選択、プレス、チェック、訪問済・未訪問、展開・折りたたみなどがある。

**Comment by bakera** [comment]
>States do not affect the nature of the component
>状態はコンポーネントの性質に影響を与えない

ステートによってコンポーネントの性質が一時的に変化することもあろうかと思います。ここのnatureは「本来の性質」「生来の性質」「本質」という類のニュアンスのように思いますがどうでしょうか。


>the component or user interaction possibilities.
>コンポーネント又はインタラクションの可能性

この「可能性」にはちょっと違和感はありますが、かといって良い訳が思いつかず……

**Comment by momdo** [comment]
> ここのnatureは「本来の性質」「生来の性質」「本質」という類のニュアンスのように思いますがどうでしょうか。

とすると、「状態はコンポーネントの本質に影響を与えない」ですかね。。

**Comment by bakera** [comment]
「可能な選択肢」はニュアンス的には近いと思います。
ここでは前の段落の component that may change を受けて possibilities と言っているので、言葉を補って良いなら「変化の可能性」とするのもありですかね……?

状態はコンポーネントの性質に影響を与えないが、コンポーネント又はインタラクションの変化の可能性に関連付けられているデータを表す。

**Comment by momdo** [comment]
https://github.com/waic/wcag21/issues/1764#issuecomment-1609146730 でincludeを「挙げられる」としたので、「変化の候補」とあわせて適用するとこうなりますか。（これでいきます）

利用者のアクション又は自動プロセスに応答して変化し得るユーザインタフェースコンポーネントの特性を表現する動的プロパティ。
状態はコンポーネントの本質に影響を与えないが、コンポーネント又はインタラクションの変化の候補に関連付けられているデータを表す。例えば、フォーカス、ホバー、選択、プレス、チェック、訪問済・未訪問、展開・折りたたみが挙げられる。
