### ISSUE TITLE
用語集：ターゲットの見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1768]
related: #98

https://waic.jp/translations/WCAG21/#dfn-target
> ターゲット (target)
二つ以上のタッチターゲットが重なっている場合、重なっているターゲットが同じアクションを実行するか、同じページを開く場合を除いて、重なっているエリアを含めてターゲットのサイズを測定するべきでない。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-target
> If two or more touch targets are overlapping, the overlapping area should not be included in the measurement of the target size, except when the overlapping targets perform the same action or open the same page.

案：
二つ以上のタッチターゲットが重なっている場合、重なっているターゲットが同じアクションを実行する、又は同じページを開く場合を除いて、重なっている領域をターゲットのサイズに含めるべきでない。

**Comment by bakera** [comment]
the measurement of the target size を単に「ターゲットのサイズ」としていて、これでも通じるとは思いますが、厳密にいうと「ターゲットサイズの測定」ですかね?

二つ以上のタッチターゲットが重なっている場合、重なっているターゲットが同じアクションを実行する、又は同じページを開く場合を除いて、重なっている領域をターゲットサイズの測定に含めるべきではない。

しかし単に「ターゲットのサイズ」とするほうがむしろわかりやすいような気もして悩ましいです。

**Comment by momdo** [comment]
あるいは「ターゲットサイズの大きさ」とかでしょうか？

**Comment by bakera** [comment]
サイズと大きさがかぶっている感はありますが、それはそれでいいような気もしつつ……
逆に「ターゲットサイズの大きさの計算に含めるべきではない」くらい補うのもありですかね?

**Comment by momdo** [comment]
サイズの大きな (テキスト) (large scale (text))
https://waic.jp/translations/WCAG21/#dfn-large-scale
という（ちょっと言葉は違いますが）前例もあるので、この前例が許されるなら、これはこれでありかと。
（逆に「サイズの大きな (テキスト)」を見直す必要がありそう、となると話は変わってきますが…）

あるいは日本語を入れ替えて稿でしょうか？

> the overlapping area should not be included in the measurement of the target size

ターゲットサイズの大きさは、重なっている領域を含めるべきでない。

**Comment by bakera** [comment]
measurement をわりとちゃんと訳したいの気持ちがあるですよね。
(大きさ自体の話ではなく、大きさの測定方法の話だということをわかりやすくしたい) 
「ターゲットサイズの計算」でいいような気もしてきました。

二つ以上のタッチターゲットが重なっている場合、重なっているターゲットが同じアクションを実行する、又は同じページを開く場合を除いて、重なっている領域をターゲットサイズの計算に含めるべきではない。

これでどうですかね?

**Comment by momdo** [comment]
計算が測定から少し離れるのは気になりますが、結局は計算していることになるので語感としてはよさそうです。

**Comment by momdo** [comment]
達成基準 2.5.5は、ターゲット「の」サイズとなっていますが、まあ無理にあわせる必要もないでしょう、たぶん。
https://waic.jp/translations/WCAG21/#target-size
