### ISSUE TITLE
用語集：映像の見直し

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1769]
related: https://github.com/waic/wcag21/issues/98

https://waic.jp/translations/WCAG21/#dfn-video
> 映像 (video)
写真や画像を動かしたり、連続して表示したりする技術。
注記
映像はアニメーション、実写、もしくはその両方で構成され得る。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-video
> the technology of moving or sequenced pictures or images
NOTE
Video can be made up of animated or photographic images, or both.

案：
写真又は画像を動かす又は順番に並べる技術
注記
映像は、アニメーション画像もしく実写画像、又はその両方で構成され得る。

**Comment by bakera** [comment]
sequenceどう訳すか問題がここにも……
#1724 では「シーケンス」にしようという話になっていましたが、ここでは sequenced ですから単に「シーケンス」とはできないですね。強引にやるなら「シーケンス表示」としてしまうとか?

写真又は画像を動かす、又はシーケンス表示する技術

**Comment by momdo** [comment]
あるいはシーケンス化するとかでしょうか（それはどうなのよという感じですが…）

**Comment by bakera** [comment]
シーケンス化はありのように思います!
