### ISSUE TITLE
用語集 : コンテキストの変化 (changes of context)

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#1788]
「重要な用語」の「コンテキストの変化 (changes of context)」で、定義文の変更があります。[WCAG 2.2 (まだ勧告前) の用語定義](https://www.w3.org/TR/WCAG22/#dfn-change-of-context)が適用されている形です。

旧)
> major changes **in the content of the Web page** that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously

新) 上記 (旧) の太字部分がトルツメされている。
> major changes that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously

これに伴い、訳を

> ウェブページのコンテンツにおける大きな変化で、利用者が気づかないと、ウェブページ全体を一度に見ることのできない利用者を混乱させる恐れのあるもの。

から

> 大きな変化で、利用者が気づくことなく生じた場合、ウェブページ全体を一度に見ることのできない利用者を混乱させる恐れのあるもの。

に変更するのはいかがでしょうか？

WCAG 2.1 解説書における影響範囲は、以下の4つの達成基準です。

- [達成基準 3.2.5: 要求による変化](https://www.w3.org/WAI/WCAG21/Understanding/change-on-request)
- [達成基準 3.2.1: フォーカス時](https://www.w3.org/WAI/WCAG21/Understanding/on-focus)
- [達成基準 3.2.2: 入力時](https://www.w3.org/WAI/WCAG21/Understanding/on-input)
- [達成基準 4.1.3: ステータスメッセージ](https://www.w3.org/WAI/WCAG21/Understanding/status-messages)

**Comment by caztcha** [comment]
@bakera @momdo 訳の変更について、ご意見いただけますと幸いです。
（ここで訳を決めたうえで、プルリクエストを出そうと思います。）

**Comment by bakera** [comment]
the entire page を「ウェブページ全体」としていますが、原文から of the Web page がなくなったのでウェブとは言い切れなくなったかと思います。「ウェブページ全体」→「ページ全体」でしょうか。

あとは語順をどうするかというところで、仮に「大きな変化」を後ろに持っていくとこうなります。

利用者が気づくことなく生じた場合、ページ全体を一度に見ることのできない利用者を混乱させる恐れのある大きな変化。

語順を変えた方がわかりやすいか、そうでない方が良いか、悩ましいところではありますね。

**Comment by momdo** [comment]
- awarenessを「気づき」としていいのか
- [simultaneously](https://eow.alc.co.jp/search?q=simultaneously)を「一度に」としていいのか（「同時に」というのが優勢？）

というあたりも気になりました。

**Comment by bakera** [comment]
たとえば view ... simultaneously を「一覧」としてまとめてしまうのはどうですかね?

利用者が意識しないうちに生じた場合、ページ全体を一覧できない利用者を混乱させるおそれのある大きな変化。

**Comment by caztcha** [comment]
@bakera @momdo コメントありがとうございます。

@bakera さんのおっしゃるとおり、語順を変えて「大きな変化」を後ろに持っていく、というのは僕も考えていました。
また、@momdo さんご指摘の awareness および simulnatenously の訳出も、おっしゃるとおりかなと。

いただいたコメントから、以下のような訳になるかと思いますが :

- 利用者が意識しないうちに生じた場合、ページ全体を同時に見ることのできない利用者を混乱させる恐れのある大きな変化。
- 利用者が意識しないうちに生じた場合、ページ全体を一覧できない利用者を混乱させるおそれのある大きな変化。

なんとなく「同時に見る」というと、複数のものを同じタイミングで見るような感覚がして、であれば、view simultaneously を「一覧する」とするのは、良さそうな気がします。

あるいは、simultaneously の「同時に」という訳を生かすのであれば、

- 利用者が意識しないうちに生じた場合、ページ全体を同時に見渡すことのできない利用者を混乱させる恐れのある大きな変化。

 ...でしょうか。view を「見渡す」にすると、やや意訳がすぎる感じもしないではありませんが。

**Comment by momdo** [comment]
> view simultaneously を「一覧する」とするのは、良さそうな気がします。

賛成です。案として「意識することなく」とするのはどうでしょうか

利用者が意識することなく生じた場合に、ページ全体を一覧できない利用者を混乱させる恐れのある大きな変化。

**Comment by caztcha** [comment]
@bakera @momdo ありがとうございます。おかげさまで、熟れた訳になったと思います。

> major changes that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously

を

> 利用者が意識することなく生じた場合に、ページ全体を一覧できない利用者を混乱させる恐れのある大きな変化。

と訳す形で、プルリクエスト出します。

**Comment by caztcha** [comment]
PR #1803 で対応中です。
