### ISSUE TITLE
WCAG 2.1 (2023)：2. Operableの更新

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1814]
原文：WCAG 2.1 2023-09-21 2. Operable
https://www.w3.org/TR/2023/REC-WCAG21-20230921/#operable

## 対象範囲

2. Operableの翻訳issueです。
主な更新箇所は、2.1.4 Character Key Shortcutsです。
CSSセレクター`section#operable`の範囲になります。

## 参考

- [前のRecommendationからの差分](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-WCAG21-20180605%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FREC-WCAG21-20230921%2F)

**Comment by momdo** [comment]
2.1.4 Character Key Shortcutsの更新箇所を比較します

2018
<https://www.w3.org/TR/2018/REC-WCAG21-20180605/#character-key-shortcuts>
> Remap: A mechanism is available to remap the shortcut to use one or more non-printable keyboard characters (e.g. Ctrl, Alt, etc);

2018訳 
<https://waic.jp/translations/WCAG21/#character-key-shortcuts>

> 再割り当て
> 一つ以上の非印字文字 (例えば Ctrl や Alt など) を使用するようにショートカットを再割り当てするメカニズムが利用できる

2023
<https://www.w3.org/TR/2023/REC-WCAG21-20230921/#character-key-shortcuts>

> Remap
> A mechanism is available to remap the shortcut to include one or more non-printable keyboard keys (e.g., Ctrl, Alt); 

なんかよく見たらスタイルも変更されてますね…

更新案：
一つ以上のキーボードの非印字キー (例えば Ctrl、Alt) を含めるようにショートカットを再割り当てするメカニズムが利用できる

**Comment by momdo** [comment]
を含めるように→を含むような　か

https://webdesk.jsa.or.jp/pdf/dev/md_1249.pdf#page=24
公用文に従うと、「割り当て」→「割当て」ですね

**Comment by bakera** [comment]
メモ: 「割り当て」は用語「ユーザインタフェース コンポーネント (user interface component)」にも登場している

>アプレットには、コンテンツ内を行単位、ページ単位、又はランダムアクセスで移動するために用いられる「コントロール」がある。これらには、いずれも名前 (name) を割り当て、個別に設定できるようにする必要があるため、それぞれが「ユーザインタフェース コンポーネント」となる。

**Comment by momdo** [comment]
「再割当てする」は「再割当て」＋「する」で、活用がない語ですが、
「を割り当て」は活用のある語なので、「を割り当て」になるはず。

法令における漢字使用等について
<https://www.clb.go.jp/files/topics/3485_ext_29_0.pdf>
> (2) 複合の語
> ア イに該当する語を除き，原則として，「送り仮名の付け方」の本文の通則６の「本則」の送り仮名の付け方による。ただし，**活用のない語で**読み間違えるおそれのない語については，「送り仮名の付け方」の本文の通則６の「許容」の送り仮名の付け方により，次の例に示すように送り仮名を省く。


送り仮名の付け方　複合の語　通則6
<https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/okurikana/honbun06.html>
> 本則
> 複合の語（通則7を適用する語を除く。）の送り仮名は,その複合の語を書き表す漢字の,それぞれの音訓を用いた単独の語の送り仮名の付け方による。
