### ISSUE TITLE
WCAG 2.1 (2023)：Glossary general flash and red flash thresholdsの更新

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1818]
原文：WCAG 2.1 2023-09-21 general flash and red flash thresholds
https://www.w3.org/TR/2023/REC-WCAG21-20230921/#dfn-general-flash-and-red-flash-thresholds

## 対象範囲

Glossary general flash and red flash thresholdsの翻訳issueです。
担当箇所は、ID `#dfn-general-flash-and-red-flash-thresholds`から`#dfn-media-alternative-for-text`まで（つまり、general flash and red flash thresholdsからmedia alternative for textまで）を範囲とします。

## 参考

- [前のRecommendationからの差分](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-WCAG21-20180605%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FREC-WCAG21-20230921%2F)

**Comment by caztcha** [comment]
PR #1843 で対応中です。
