### ISSUE TITLE
WCAG 2.1 (2023)：Glossary relative luminanceの更新

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1821]
原文：WCAG 2.1 2023-09-21 relative luminance
https://www.w3.org/TR/2023/REC-WCAG21-20230921/#dfn-relative-luminance

## 対象範囲

Glossary relative luminanceの翻訳issueです。
担当箇所は、ID `#dfn-relative-luminance`から`#dfn-section`まで（つまり、relative luminanceからsectionまで）を範囲とします。

## 参考

- [前のRecommendationからの差分](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-WCAG21-20180605%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FREC-WCAG21-20230921%2F)

**Comment by momdo** [comment]
relative luminanceの更新内容は以下にあります。
https://github.com/waic/wcag21/pull/1694

**Comment by caztcha** [comment]
PR #1847 にて対応中です。
