### ISSUE TITLE
WCAG 2.1 (2023)：A. Change Logの更新（追加）

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1826]
原文：WCAG 2.1 2023-09-21 A. Change Log
https://www.w3.org/TR/2023/REC-WCAG21-20230921/#changelog

## 対象範囲

A\. Change Logsの翻訳issueです。
CSSセレクター`section#changelog`の範囲を追加して翻訳します。

## 参考

- [前のRecommendationからの差分](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FREC-WCAG21-20180605%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2023%2FREC-WCAG21-20230921%2F)

**Comment by caztcha** [comment]
このセクション、日本語訳するか、迷いますね。
一度勧告された後に、今回どう変更が加えられたか、という一覧なので、その意味では日本語にする意義はあると思いますが、たとえば下記のように、英語表記の誤記訂正も結構あったりして、どうしたものか、と思います。

> In the [0.5.2 Numbering in WCAG 2.1](https://www.w3.org/TR/WCAG21/#numbering-in-wcag-2-1), the words "critera" and "ccriteria" have been changed to "criteria".
> In [1.4.13 Content on Hover or Focus](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus), the word "dismissable" has been changed to "dismissible".
> In [4. Robust](https://www.w3.org/TR/WCAG21/#robust), repetition of the word "by" has been removed.

**Comment by momdo** [comment]
個人的には英語ママでよいと思いますがいかがでしょうか？ @bakera

**Comment by bakera** [comment]
英文のまま、で良いと思います。
状況を改めて整理すると、付属書にあたる部分が当初の勧告では

A. Acknowledgments
B. References 

となっていたのが、今回の更新で ChangeLog が追加されて、対応する見出しも挿入されて

A. ChangeLog
B. Acknowledgments
C. References 

に変わったということですね。
ChangeLogを訳す必要性はあまり感じない一方で、見出しが原文と対応していないのは混乱を招きそうなので、見出しだけは揃えておきたいです。見出しは原文にあわせつつ、A. ChangeLogの中身は翻訳せずに英文をそのまま掲載しておく、という方針で良いように思います。

**Comment by caztcha** [comment]
ありがとうございます。
`<h2>` 見出しの「A. Change Log」のところだけは日本語に訳す、という感じですね。

改めて原文を読んでいますが、ログの箇条書きの前後にある段落（下記に引用）は、日本語にしてもよいかな（箇条書きだけは英語のままで残す）、というのもありな気もしてきました。

> This section shows changes for WCAG 2.1 since its publication as a W3C Recommendation. These changes are also recorded as [errata](https://www.w3.org/WAI/WCAG21/errata/).
> 
> Changes since the [W3C Recommendation of 05 June 2018](https://www.w3.org/TR/2018/REC-WCAG21-20180605/):

> The full [commit history to WCAG 2.1](https://github.com/w3c/wcag/commits/WCAG-2.1/guidelines/index.html) is available.

**Comment by momdo** [comment]
@caztcha 
こちら作業のほういかがでしょうか…？

**Comment by caztcha** [comment]
@momdo リマインドありがとうございます。手つかずのままでした。11/6 (月) 中に、遅くとも11/7 (火) には、修正作業のうえプルリクエストを出します。

**Comment by caztcha** [comment]
大変お待たせしました！ PR #1857 で対応中です。
