### ISSUE TITLE
WCAG 2.1 (2023)：JSの更新

### ISSUE THREAD

**Issue by tsmd** [waic/wcag21#1837]
やること
- 用語参照機能を移植する
- 依存しているJSのアップデート

仕様書の使い勝手を高めるためにJSによるエンハンスメントが行われている。2018->2023の変更点のひとつに用語参照機能の新規追加やJSのアップデートが行われている。このissueではそれに追随する。

## 用語参照機能を移植する

- 文中の用語にマウスオーバーするとツールチップで説明が表示される
- 用語の定義をクリックすると参照元の一覧が表示される

![ツールチップが表示されているところのスクリーンキャプチャ](https://github.com/waic/wcag21/assets/490085/c5115ca4-3eb0-4ad0-9b03-6bbdae6badd3)

![参照元の一覧が表示されているところのスクリーンキャプチャ](https://github.com/waic/wcag21/assets/490085/ce420a03-623c-454a-89ec-c35dca9ce341)

HTML末尾あたりに、参照元を一覧するダイアログの要素（role=dialog を持つ要素）がずらずら並んでいるので、それを移植する。

## 依存しているJSのアップデート

原稿の翻訳にはHTML末尾あたりに

```html
<script src="https://www.w3.org/scripts/TR/2016/fixup.js"></script>
```

というスクリプトの参照がある。本家はこれがアップデートされているので

```html
<script src="https://www.w3.org/scripts/TR/2021/fixup.js"></script>
```

に置き換える。

**Comment by momdo** [comment]
やってもよいとは思いますが、
翻訳を全部した上で、2023の原文のHTMLに訳文を流し込んだほうが確実な気がするんですよね…

**Comment by tsmd** [comment]
そうですね。同感です。
自動化する妙案があるといいなと思いつつ。

**Comment by bakera** [comment]
若干それますが、w3.orgから直接読んでいるJS/CSSはWAICのサーバーに持ってくるべきかもという話もありますね。

**Comment by tsmd** [comment]
> w3.orgから直接読んでいるJS/CSSはWAICのサーバーに持ってくるべきかも

たしかにです。持ってきたほうがいいように思います。

**Comment by tsmd** [comment]
WCAG21ではコンテンツ以外の部分はそのままにしておくことにしました。
「対応しない」としてissueを閉じます。
