### ISSUE TITLE
WCAG 2.1 用語定義の修正を、WCAG 2.1 解説書にも適用する

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#1856]
https://github.com/waic/wcag21/pull/1843
https://github.com/waic/wcag21/pull/1846
https://github.com/waic/wcag21/pull/1847
https://github.com/waic/wcag21/pull/1848

上記プルリクエストで、用語集の

- 「一般閃光閾値及び赤色閃光閾値 (general flash and red flash thresholds)」
- 「ポインタ入力 (pointer input)」
- 「相対輝度 (relative luminance)」
- 「ウェブページ一式 (set of Web pages)」

で翻訳が修正されているため、同様の修正を、WCAG 2.1 解説書の「重要な用語」の該当箇所にも反映させる必要があります。

**Comment by caztcha** [comment]
他にも、該当箇所があるかもしれないので、WCAG 2.1 本体 (2023年9月23日更新版) の日本語訳が正式にフィックスしたところで、全体確認したいと思います。

**Comment by bakera** [comment]
WCAG 2.1 本体のほうはひととおりマージ済みですので、進めていただければと思います!

**Comment by momdo** [comment]
@caztcha ping

**Comment by caztcha** [comment]
確認したところ、以下の用語で、アップデートがありました。
いずれも、変更内容は既にクリアで、単純作業なので、数日でプルリクエスト出せると思います。

- 略語 (abbreviation)
- アクセシビリティ サポーテッド (accessibility supported)
- コンテキストの変化 (changes of context)
- 一般閃光閾値及び赤色閃光閾値 (general flash and red flash thresholds)
- 法律行為 (legal commitments)
- モーションアニメーション (motion animation)
- ポインタ入力 (pointer input)
- プロセス (process)
- 相対輝度 (relative luminance)
- ウェブページ一式 (set of Web pages)
- ユーザインタフェース コンポーネント (user interface component)

**Comment by caztcha** [comment]
具体的な diff

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwaic.jp%2Ftranslations%2FWCAG21%2F&doc2=https%3A%2F%2Fwaic.github.io%2Fwcag21%2Fguidelines%2F#glossary

**Comment by caztcha** [comment]
ひととおり、プルリクエストを出し終えました。

**Comment by momdo** [comment]
@caztcha @bakera 
確認してマージしたので、closeします。
