### ISSUE TITLE
翻訳文書の `<title>` に "日本語訳" を含められないか

### ISSUE THREAD

**Issue by SaekiTominaga** [waic/wcag21#1878]
WAIC で公開されている翻訳文書のうちいくつかは本家（原文）と `<title>` が同一であり、検索結果の一覧画面などで並ぶとどちらが日本語訳なのか分かりにくい状況です。
とくに WAIC や W3C の組織を知らない人にとっては、Favicon などを見てもなお、どうして同じものが2つあるのか理解できないかもしれません。（リンク先に飛んだうえで注意深く冒頭の文章を読めばもちろん理解できるでしょうが）

↓ Google で「WCAG 2.1」と検索した様子
![検索結果の1番目に WAIC の日本語訳、2番目に W3C のページが表示、リンクタイトルはどちらも「[Web Content Accessibility Guidelines (WCAG) 2.1](https://waic.jp/translations/WCAG21/)」](https://github.com/waic/wcag21/assets/4138486/0d06100d-bb33-460c-b9ff-f55294ee8fed)

もう一つの問題として、日本語の検索結果に出にくいのではという疑念もあります。
WCAG 2.1 を例に取ると、[DDG で「WCAG 2.1」で検索](https://duckduckgo.com/?q=WCAG+2.1&kl=jp-jp&t=ffsb&ia=web&atb=v326-1)すると解説書などが上位に来てしまい、ガイドラインページそのものはまったくヒットしませんでした。

興味深いのは「WCAG 2.1 site:waic.jp」で絞り込んだ場合、[全言語設定](https://duckduckgo.com/?q=WCAG+2.1+site%3Awaic.jp&kl=wt-wt&t=ffsb&atb=v326-1)では1番目に表示されるのに対し、[日本語でフィルター掛ける](https://duckduckgo.com/?q=WCAG+2.1+site%3Awaic.jp&kl=jp-jp&t=ffsb&atb=v326-1)と4番目に低下します。
DDG のアルゴリズムなど詳しいことは分かりませんし、SEO 方面の専門知識も持たないうえでの発言ですが、`<title>` が英語のみになっていることが悪影響を及ぼしている可能性は考えられないでしょうか。

改善案としては以下が考えられます。

- `<title>Web Content Accessibility Guidelines (WCAG) 2.1 日本語訳</title>` のように「日本語訳」を含める
- `<title>ウェブコンテンツアクセシビリティガイドライン (WCAG) 2.1</title>` のように日本語表記にする（[WCAG 2.1 達成方法集](https://waic.jp/translations/WCAG21/Techniques/)などは現状ママ）

ご検討お願い致します。

**Comment by bakera** [comment]
単純に末尾に (日本語訳) のように入れますかね?
