### ISSUE TITLE
解説書：目次の達成基準が「意味のある順序」のままになっている

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1883]
https://waic.jp/translations/WCAG21/Understanding/

![image](https://github.com/waic/wcag21/assets/8347177/7188789c-759b-4f79-a08b-b704fb127658)

（しれっと）修正するのかどうかはさておき、「意味のあるシーケンス」への置換忘れが発生しています…

**Comment by bakera** [comment]
調べてみると techs H40 にも「意味のある順序」が登場していました。

>意味のある順序が確保されていれば、複数の用語を単一の説明に、単一の用語を複数の説明に関連付けることもできる。
>Multiple terms can be associated with a single description, as can a single term with multiple descriptions, provided that semantic sequence is maintained.

ただこちらの原文は "meaningful sequence" ではなく "semantic sequence" ですね。

**Comment by momdo** [comment]
Googleフォームでのコメントあり。

> 左カラムの目次の部分、1.3.2 が「意味のある順序 」となっていますが、「意味のあるシーケンス」が正しいでしょうか？

**Comment by bakera** [comment]
2.1は放置でいいという気持ちもありつつ、とはいえさすがにこれは直した方がいいですね。
