### ISSUE TITLE
SCR39の文書途切れ

### ISSUE THREAD

**Issue by kentarou-fukuda** [waic/wcag21#1885]
https://waic.jp/translations/WCAG21/Techniques/client-side-script/SCR39

について、事例の後のTestsなどが切れてしまっている様に思います。ご確認をお願いいたします。

**Comment by bakera** [comment]
https://github.com/waic/wcag21/issues/1623 で報告されているものと同じですね。
これどうすることにしたんでしたっけ?

**Comment by bakera** [comment]
翻訳当時は原文がそうなっていたのでママとする、という判断をしたようですが、明らかに問題のある状態ではあるのでなんとかしたい気持ちはあります。
(最悪、Techs for WCAG 2.2 の日本語訳では直るはずですが、いつになるやら……)

**Comment by kentarou-fukuda** [comment]
なるほど、翻訳時にそもそも千切れていたんですね。。。
単発で直すだけならお手伝いできるかもですが、全部の足並み揃えるのは難しいですね。。。

**Comment by momdo** [comment]
Duplicate: https://github.com/waic/wcag21/issues/1375
