### ISSUE TITLE
解説書  1.4.1 メリットの項目数が日英で異なる

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#1895]
日本語訳で6項目あるが、原文では5項目しかない

- https://waic.jp/translations/WCAG21/Understanding/use-of-color.html#benefits
- https://rawcdn.githack.com/waic/w3c-wcag/2fdc7417d1af84baec69b999179c5069d1c969b0/wcag21/understanding/use-of-color.html#benefits

また、日本語訳で6つ目（原文では5つ目が対応か）の翻訳が不正確

日本語訳

> 点字ディスプレイ又は他の触覚インタフェースの人が、タッチすることでテキストキューを検出できる。

原文

> Users who have problems distinguishing between colors can look or listen for text cues.

訳の案としてはこうか：
色の区別に問題がある利用者は、テキストの手がかりを見たり聞いたりできる。

**Comment by bakera** [comment]
日本語の5番目と6番目の項目がこうで、

- 色の識別に問題を抱える利用者が、テキストの手がかりを見たり、聞いたりすることができる。
- 点字ディスプレイ又は他の触覚インタフェースの人が、タッチすることでテキストキューを検出できる。

英語の5番目がこうで、

- Users who have problems distinguishing between colors can look or listen for text cues.

日本語の最後の項目が余計ということですね。
