### ISSUE TITLE
サイドナビの1.3.2の名称アップデート

### ISSUE THREAD

**Issue by Junko-Koide** [waic/wcag21#1927]
https://waic.jp/translations/WCAG21/Understanding/
サイドナビの1.3.2の名称が「意味のある順序」のままでしたので、「意味のあるシーケンス」へ変更お願いします。
（リンク先は問題ありません）

`<li class="tocline"><a href="meaningful-sequence.html" class="tocxref"><span class="secno">1.3.2</span> 意味のある順序</a></li>`

**Comment by momdo** [comment]
@Junko-Koide 

- https://github.com/waic/wcag21/issues/1883 と重複
- https://github.com/waic/wcag21/pull/1892 で修正済み

なのでCloseします。

**Comment by Junko-Koide** [comment]
ありゃ。検索して出てこなかったので起票したのですが、ミスったようでお手数おかけしました。
