### ISSUE TITLE
【解説書】1.4.11 非テキストのコントラスト 翻訳作業

### ISSUE THREAD

**Issue by k-octopus** [waic/wcag21#203]
1.4.11 非テキストのコントラスト
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast
https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/non-text-contrast.html

**Comment by Koide-Junko** [comment]
社内で調整し、畠山さんに担当向けました。よろしくお願いします。

**Comment by momdo** [comment]
マージ済みなので閉じます。
