### ISSUE TITLE
【解説書】1.4.13 ホバー又はフォーカスで表示されるコンテンツ 翻訳作業

### ISSUE THREAD

**Issue by k-octopus** [waic/wcag21#205]
Understanding WCAG 2.1
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus

WCAG 2.1 解説書
https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/content-on-hover-or-focus.html

**Comment by Koide-Junko** [comment]
社内で調整し、畠山さんに担当向けました。よろしくお願いします。

**Comment by honoka-h** [comment]
close per #257
