### ISSUE TITLE
【解説書】 1.3.5 入力目的の特定 の翻訳作業

### ISSUE THREAD

**Issue by tokimari** [waic/wcag21#207]
refs:
- https://www.w3.org/TR/WCAG21/#identify-input-purpose
- https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html
- https://waic.github.io/wcag21/guidelines/#identify-input-purpose

現状の英語verの解説書: https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/identify-input-purpose.html

**Comment by momdo** [comment]
マージ済みなのでcloseします。
