### ISSUE TITLE
【解説書】4.1.3 ステータスメッセージ の【事例】以外の翻訳作業

### ISSUE THREAD

**Issue by tokimari** [waic/wcag21#209]
refs:
- https://www.w3.org/TR/WCAG21/#status-messages
- https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html
- https://waic.github.io/wcag21/guidelines/#status-messages

**Comment by caztcha** [comment]
## 翻訳対象

- GItHub リポジトリ : https://github.com/waic/wcag21/tree/Understanding-20190306-ED
- 翻訳対象ページ : https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/status-messages.html


## 作業手順
 
1. ブランチ`Understanding-20190306-ED`に翻訳するファイルを設置しますので、ブランチを新たに作成してください。
2. 各自が翻訳する範囲は基本的に、見出し「意図」から見出し「達成方法」までのセクションです（言い換えると、見出し「重要な用語」の直前まで）。
   - 用字などは翻訳ガイドラインを見ながら進めてください。
   - WCAG 2.1の達成基準や重要な用語の翻訳に疑問点があれば、あわせてissueを立てるとよいでしょう。
3. 翻訳が済んだら、ブランチ`Understanding-20190306-ED`へPull Requestを出してください。
   - レビューはもんどさんが行います。必要に応じて追加のレビューを太田さんがします。
4. レビューコメントがあれば、コメントを参考に修正してください。
5. レビューコメントが一通り片付いて、マージOKの状態になったら、太田さんがマージします。

**Comment by tokimari** [comment]
事例セクションが長いため別作業としたいと思います。
事例はこちらで： https://github.com/waic/wcag21/issues/285

**Comment by momdo** [comment]
未訳の箇所がちょっと残っていますね…

https://github.com/waic/wcag21/blob/f1d6afde5558f1acadbc62b1d3189164399aa03c/understanding/status-messages.html#L64
https://github.com/waic/wcag21/blob/f1d6afde5558f1acadbc62b1d3189164399aa03c/understanding/status-messages.html#L204
https://github.com/waic/wcag21/blob/f1d6afde5558f1acadbc62b1d3189164399aa03c/understanding/status-messages.html#L223
https://github.com/waic/wcag21/blob/f1d6afde5558f1acadbc62b1d3189164399aa03c/understanding/status-messages.html#L248-L250
https://github.com/waic/wcag21/blob/f1d6afde5558f1acadbc62b1d3189164399aa03c/understanding/status-messages.html#L257

**Comment by momdo** [comment]
ざっくりと翻訳作業は終わったと思いますので、Closeしておきますね。
