### ISSUE TITLE
2.2.6 タイムアウト・2.2.7 インタラクションからのアニメーション・2.4.11 文字キーのショートカット・2.4.12 名前（name）のラベル 翻訳作業

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#21]
植木さん訳由来の翻訳文あり。日本語訳のレビューを行うこと。

**Comment by tokimari** [comment]
- [ ] 2.2.6 タイムアウト: https://github.com/waic/wcag21/pull/33
- [ ] 2.2.7 インタラクションからのアニメーション: https://github.com/waic/wcag21/pull/34
- [ ] 2.4.11 文字キーのショートカット: PRなし
- [ ] 2.4.12 名前（name）のラベル: PRなし

**Comment by momdo** [comment]
- 2.2.7 #34
- 2.4.11 #40 
- 2.4.12 #41 
7月ミーティングによりマージ済み。
