### ISSUE TITLE
【解説書】達成基準 3.3.2 ラベル又は説明

### ISSUE THREAD

**Issue by MasaoYOMODA** [waic/wcag21#217]
refs:
- https://www.w3.org/TR/WCAG21/#labels-or-instructions
- https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions
- https://waic.github.io/wcag21/guidelines/#labels-or-instructions

**Comment by caztcha** [comment]
## 翻訳対象

- GItHub リポジトリ : https://github.com/waic/wcag21/tree/Understanding-20190306-ED
- 翻訳対象ページ : https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/labels-or-instructions.html


## 作業手順
 
1. ブランチ`Understanding-20190306-ED`に翻訳するファイルを設置しますので、ブランチを新たに作成してください。
2. 各自が翻訳する範囲は基本的に、見出し「意図」から見出し「達成方法」までのセクションです（言い換えると、見出し「重要な用語」の直前まで）。
   - 用字などは翻訳ガイドラインを見ながら進めてください。
   - WCAG 2.1の達成基準や重要な用語の翻訳に疑問点があれば、あわせてissueを立てるとよいでしょう。
3. 翻訳が済んだら、ブランチ`Understanding-20190306-ED`へPull Requestを出してください。
   - レビューはもんどさんが行います。必要に応じて追加のレビューを太田さんがします。
4. レビューコメントがあれば、コメントを参考に修正してください。
5. レビューコメントが一通り片付いて、マージOKの状態になったら、太田さんがマージします。

**Comment by MasahikoNegishi** [comment]
今月が本業の山場と重なってしまい、作業自体は何もできておりません…
他のPR拝見したり、ドキュメント系は粛々と拝見しているので、可能であればこのまま本issueをアサインいただけると嬉しいです！

**Comment by bakera** [comment]
こちら状況いかがでしょうか。
もし作業が途中まで進んでいるようでしたら、作業途中のプルリクエストを (タイトルに[WIP]とつけて) 作成していただけると助かります!

**Comment by MasahikoNegishi** [comment]
@bakera
結論から申し上げると、作業が進んでおりません…。もしボトルネックになっているようでしたら、直近は立て込んでいますので、恐縮ですが他の方にアサインいただけると幸いです。
11月半ばは少し時間がとれるかもしれませんので、もし問題なければ本issueに着手いたします。
よろしくお願いいたします。

**Comment by bakera** [comment]
いったん今井さんにお願いすることにしました。

**Comment by DaichiImai** [comment]
担当させていただきます。

**Comment by momdo** [comment]
#342 にてPRあり

**Comment by momdo** [comment]
マージ済みなのでCloseします。
