### ISSUE TITLE
【解説書】見出し「Benefits」の訳

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#218]
すべてのガイドラインおよび達成基準の解説ページにある見出し「Benefits」ですが、一律的に「メリット」と訳す形でよいでしょうか？

**Comment by momdo** [comment]
https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/non-text-content.html

今、そういえば2.0解説書ってどんなんだったっけ？と思って見返してみたんですが、
> Specific Benefits of Success Criterion 1.1.1:

となっていた箇所を

>達成基準 1.1.1 の具体的なメリット:

としてたんですね…（作業中に気づきませんでした……💧）

https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/text-equiv-all.html#text-equiv-all-10-head
https://waic.jp/docs/UNDERSTANDING-WCAG20/text-equiv-all.html#text-equiv-all-10-head

私は「メリット」に賛成しますが他の方はどうでしょうか。2.1解説書で見直すというのも理屈としてはありだと思います。

**Comment by bakera** [comment]
メリットで良いかと思います。

**Comment by caztcha** [comment]
@bakera ありがとうございます。
一旦私の方で、(WCAG 2.0 からの既存の達成基準の解説書ページも含めて)「Benefits」を一律的に「メリット」と訳して、Pull Request 出してしまってよいですかね。
// みなさん、解説書の翻訳に仕掛中だと、コンフリクトが起きてしまう？であれば、全体の翻訳が出揃った（ひととおりマージされた）ところで、一括置換作業をするほうがよいですかね...

**Comment by momdo** [comment]
> コンフリクトが起きてしまう？

たとえ起きたとしても、容易に日本語が正だとわかるので、土屋さんがそれほど苦にされないならば、一括で置換いただけると助かります🙏

**Comment by caztcha** [comment]
ですよね。承知しました。
では土屋にて、一括置換作業します。

機械的な作業なので、マージまでやってしまおうかと思っていますが、差し支えありましたらおっしゃってください。> @momdo @bakera

**Comment by caztcha** [comment]
PR #236 で対応。

**Comment by caztcha** [comment]
マージ完了したのでクローズします。
