### ISSUE TITLE
landscape modeの訳語の再検討

### ISSUE THREAD

**Issue by tokimari** [waic/wcag21#234]
`解説書 1.3.4 表示の向き` の翻訳PRにて下記議論が起きました。
ひとまず `ランドスケープモード` としておき、用語統一の観点で再検討を、ということになりましたのでissueを立てました。

### TODO
- [x] landscape mode の訳語を検討
- [ ] 修正する

### 議論

> momdo
> landscape modeをランドスケープモードにしているのは意図的に訳し分けている、ということでしょうか（例えば49行目ではlandscapeを横長、57行目のようにlandscape orientationであれば横向きとしているので、ここだけカナにしているんだなと。カナの方がわかりやすいかもしれないので、難しいところですが💧）

> tokimari
> ここはどうしようか迷ったのですが、「横向きモード」とすると余計に違和感があるなと思いここだけカタカナにしまして・・ 😅
内容的には「横向きにする」とかでも通じるのですが、 mode の訳語がなくなってしまうなぁと・・

> tokimari
> 4/25のmtgにて、ひとまず ランドスケープモード としておき、用語の統一の観点で再検討しましょうとのことになりました。
issueを切っておきます！

https://github.com/waic/wcag21/pull/225#discussion_r276168784

**Comment by bakera** [comment]
名前(name) のような表記を採用して、

「縦向き (portrait)」
「横向き (landscape)」

とする方向でいったん検討したいと思います。

**Comment by tokimari** [comment]
2つともマージされたのでclose
