### ISSUE TITLE
「ジェスチャ」or「ジェスチャー」表記ゆれの解消

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#240]
WCAG 2.1 本体において、「ジェスチャ」と「ジェスチャー」（長音のなし/あり）が混在しているので、どちらかに統一する必要があります。

WCAG 2.1 本体だけでなく、解説書の日本語訳においても対応が必要です。

**Comment by momdo** [comment]
検討の過程で上がった参考文献
- https://www.jtca.org/standardization/katakana_guide_3_20171222.pdf
- https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline
- http://www.ny.ics.keio.ac.jp/ipsjts1/3rd-ver/htm/jx76e0fa.htm

**Comment by bakera** [comment]
どちらに統一しても良いと思うのですが、JIS X 9302「情報技術－ペンベースインタフェース－ペンベースシステムにおけるテキスト編集のための共通ジェスチャ」が伸ばさないほうを採用しているので、JIS的には伸ばさないのではという説が有力になりました。
JISに合わせないといけないわけでもないのですが、合わせてはいけない理由もないので、ひとまず伸ばさないほうに統一することにします。

**Comment by caztcha** [comment]
ご検討ありがとうございます。承知いたしました。
長音なしで統一ということで、別途、プルリクエスト出します。（WCAG 2.1 本体および  WCAG 2.1 解説書）

**Comment by caztcha** [comment]
WCAG 2.1 本体に対しては、PR #256 で対応しました。

Understanding WCAG 2.1 については、日本語訳がひととおり出揃ったところで置換しようと思います。

**Comment by caztcha** [comment]
WCAG 2.1 解説書に対しては、ひととおり日本語訳が揃ったところで一括置換します。

**Comment by caztcha** [comment]
WCAG 2.1 解説書に対しては、PR #268 で対応しました。
