### ISSUE TITLE
6. 用語集 CSS ピクセル (CSS pixel)・ダウンイベント (down-event)・キーボードショートカット (keyboard shortcut)・motion animation 翻訳作業

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#25]

**Comment by MasaoYOMODA** [comment]
@cocktailz さん、6/28 WG4議事に基づき、Assigneesに 四方田を追加しました。進捗確認させてください。１週間後、7/5(木)までで確認が難しいようなら、恐縮ですが四方田で翻訳作業引き取ろうかとも考えてます。ご確認をお願いします。

**Comment by cocktailz** [comment]
CSSピクセル、ダウンイベント、キーボードショートカットの翻訳を修正しました。
motion animationはこのあと作業します。
https://github.com/waic/wcag21/blob/ishiki-edit/index.html

**Comment by tokimari** [comment]
@cocktailz さん、私が担当割りを把握しておらず、こちらのPRでmotion animationの用語集にまで手をつけてしまいました。そのため、motion animationについては、cocktailzさんがよければこちらのPRで翻訳できればと思います。いかがでしょうか。
不都合ありましたら私の方の修正を取り下げるので、お教えください。

**Comment by cocktailz** [comment]
ありがとうございます。
こちらはまだほとんど手が付いていませんので、土岐さんに引き取っていただけたら助かります。

四方田さん、問題ないでしょうか。

-----
Cocktailz
伊敷 政英(いしき まさひで)

〒173-0036 東京都板橋区向原3-5-2
クレストイシダi 102号室

mail: info@cocktailz.jp
web: http://cocktailz.jp/


2018/07/03 11:10、tokimari <notifications@github.com>のメール:

**Comment by MasaoYOMODA** [comment]
@cocktailz 伊敷さん、 @tokimari 土岐さん、７日も連絡滞り失礼しました。
伊敷さん、四方田はもちろん問題ありません。土岐さん、恐縮ですがmotion animationの翻訳お願いします。
では伊敷さん、土岐さん、次回WG4まで現時点で四方田はNoActionと認識しました。やっぱりこの部分は作業依頼したい、ということあればお声がけください。よろしくお願いします。

**Comment by momdo** [comment]
7月ミーティングでマージ済みにつきclose
