### ISSUE TITLE
WCAG 2.1 用語の「CSS ピクセル」にゴミ？

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#265]
WCAG 2.1 > 6. 用語集 > CSS ピクセル (CSS pixel)
https://waic.jp/docs/WCAG21/#dfn-css-pixels

最初のパラグラフとして、

> 約 0.0213 度の視野角。

...という記述があるが、これは不要かも。（原文側に「visual angle of about 0.0213 degrees」という記述があるので、翻訳の誤りではなく、原文側の間違いと思われる。）

以下の WCAG 2.1 解説書ページ (重要な用語) も、要修正。
- SC 1.4.4 リフロー (https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/reflow.html)
- SC 2.5.5 ターゲットサイズ (https://raw.githack.com/waic/wcag21/Understanding-20190306-ED/understanding/target-size.html)

**Comment by momdo** [comment]
（わかりにくいですが）CSS Values L3由来の文なので、難解さはありますが、誤りとは言い切れないのでは。
https://www.w3.org/TR/css-values-3/#reference-pixel

> The reference pixel is the visual angle of one pixel on a device with a pixel density of 96dpi and a distance from the reader of an arm’s length. For a nominal arm’s length of 28 inches, the visual angle is therefore about 0.0213 degrees. For reading at arm’s length, 1px thus corresponds to about 0.26 mm (1/96 inch).

参考訳
https://momdo.github.io/css3-values/#reference-pixel
> 基準画素とは、腕の長さのデバイスからの距離と96dpiのピクセル密度におけるデバイス上の1ピクセルとの視角である。名目の腕の長さが28インチの場合、視角は約0.0213度である。距離をおいて読むために、1pxは約0.26mm（1/96インチ）に対応する。

**Comment by caztcha** [comment]
@momdo さん、ご教示ありがとうございます。なるほど、そういうつながりなのですね。本件、対応不要としてクローズします。
