### ISSUE TITLE
「dexterity」の訳 (「巧緻性」でよいか？)

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#275]
以下の Understanding (解説書) で、「dexterity」という用語が出てきますが、その訳語の統一を検討したいと思います。

### 達成基準 1.3.4 表示の向き

**dexterity** impairments を「**巧緻性**障害」としています。

### 達成基準 2.1.4 文字キーのショートカット

dexterity challenges を「**巧緻性**に課題がある（こと）」としています。

> キーボードのみの利用者で**巧緻性**に課題がある場合、誤ってキーを押す可能性もある。

### 達成基準 2.2.1 タイミング調整可能

**dexterity** impairments を「**巧緻性**障害」としています。

### 達成基準 2.2.5 ターゲットのサイズ

limited **dexterity** を「**身体運動の細かさ**に制約が (ある)」としています。

> この達成基準の意図は、たとえ利用者が小型の携帯用タッチスクリーンデバイスでコンテンツにアクセスしていたり、**身体運動の細かさ**に制約があったり、その他の理由で小さなターゲットをうまく動作させることができなかったりしても、ターゲットのサイズが利用者にとって容易に動作可能な十分な大きさであることを担保することである。

→ これを「**巧緻性**に制約があったり...」とするか。

### 達成基準 2.5.6 入力メカニズム非依存

limited **dexterity** を「**身体運動の細かさ**の制限」としています。

> 精度の低いタッチ対応ノートパソコンでは、手の震えや**身体運動の細かさ**の制限などの理由で小さなターゲットを動作させるのが困難な場合でも、キーボード及びトラックパッドを使用してコンテンツとやりとりすることができる。

→ これを「**巧緻性**の制限などの理由で...」とするか。

### 用語集

見解がまとまったら、用語集も要メンテ。(現状では「巧緻性」となっている。)

https://docs.google.com/spreadsheets/d/1V8wX-pxAO-zuYwTSvTSuZ_FtnV47su6Tyy2vM5GEOLw/edit#gid=0&range=8:8 

### 参考 (アルク英辞郎で「dexterity」を調べると...)

https://eow.alc.co.jp/search?q=dexterity&ref=sa

**Comment by bakera** [comment]
いったん「巧緻性」でよい、という方向で。
何か異論があればまた検討しましょう。

**Comment by caztcha** [comment]
PR #1399 で対応中です。
