### ISSUE TITLE
【解説書】4.1.3 ステータスメッセージ の【事例】セクションの翻訳作業

### ISSUE THREAD

**Issue by tokimari** [waic/wcag21#285]
https://github.com/waic/wcag21/issues/209 の項目のうち、事例が非常に長いため分割して作業したいです。
こちらは事例部分の翻訳作業issueです。詳細は #209 を参照してください。

**Comment by tokimari** [comment]
事例１つずつが大きいので、1つずつ分けてプルリクエストする
- [ ] Status Message Examples
- [ ] Examples of Status Messages that Do Not Add New Text to the Screen
- [ ] Examples of Changes That Are Not Status Messages
- [ ] Other uses of live regions or alerts

**Comment by momdo** [comment]
分割に関しては @tokimari さん1人で担当するのでなく、Slack yowane等でできる人を募集するイメージで。

**Comment by momdo** [comment]
@ishimasar 

Slackで手を挙げていただいたので、3番目と4番目のものを分担いただけますか？

- Examples of Changes That Are Not Status Messages
- Other uses of live regions or alerts

よろしくお願いいたします。

**Comment by ishimasar** [comment]
@tokimari 
翻訳作業に明後日12/8あたりから取りかかれる予定です。
作業に先立ち、対応する2つの個別ブランチを立てておきたいと思います。

起点ブランチ：`Understanding-20190306-ED`

- [ ] Examples of Changes That Are Not Status Messages　分のブランチ
- [ ] Other uses of live regions or alerts　分のブランチ

よろしくお願いいたします。

**Comment by ishimasar** [comment]
2019/12/09 進捗：
`Examples of Changes That Are Not Status Messages`、`Other uses of live regions` 両方の全文に訳をつけた。まだ、推敲や精査が必要なのでpushしません。

**Comment by momdo** [comment]
事例のセクション、マージしましたのでこのissueを閉じますね。

@tokimari さん、 @ishimasar さん、翻訳作業ありがとうございました。

**Comment by ishimasar** [comment]
@momdo @tokimari 
お疲れ様でした！

**Comment by tokimari** [comment]
おつかれさまでした！ @ishimasar さん、協力いただきありがとうございました！膨大だったので助かりました ☺️
