### ISSUE TITLE
enhanceの訳語検討

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#371]
関連: #368 

enhanceという言葉をいったん「強化」としたが、日本では「プログレッシブ・エンハンスメント」という言葉がカタカナ表記で通っており、これらが同じenhanceであると伝わった方がわかりやすいかもしれない。

ちなみにForm Design Patterns日本語訳の p.107では「エンハンス(強化)されたマークアップ」となっている。「エンハンス(強化)」はわかりやすいように思うがどうだろうか。

名前(name) などのルールに従うなら「強化(enhance)」というのもありなのかも。

**Comment by momdo** [comment]
> enhanceという言葉をいったん「強化」としたが、日本では「プログレッシブ・エンハンスメント」という言葉がカタカナ表記で通っており、これらが同じenhanceであると伝わった方がわかりやすいかもしれない。

そこまであわせる必要があるのかというと、若干疑問かなというのが個人的な感覚ですね。

元の箇所：
https://www.w3.org/WAI/WCAG21/Understanding/conformance#conformance-claims

> Here is a claim which has been enhanced with schema.org metadata:

翻訳箇所：
https://waic.jp/docs/WCAG21/Understanding/conformance.html#conformance-claims

> schema.org メタデータで強化された宣言は次のとおり:

「拡張」とするのはどうか？

schema.org メタデータで拡張された宣言は次のとおり:

**Comment by bakera** [comment]
あまり良い訳語もなく、エンハンスという言葉も廃れてきている気がするので、いったん強化のママとします。
