### ISSUE TITLE
リンク文字列がわかりづらい

### ISSUE THREAD

**Issue by jidaikobo-shibata** [waic/wcag21#373]
https://waic.jp/docs/WCAG21/Understanding/
のインデクスにあたるUnderstanding Pagesのリンクの下線がないので、リンク文字列だとわかりづらいとおもいます。下線を付与した方が良いと考えます。

**Comment by momdo** [comment]
@jidaikobo-shibata 
WCAG 2.1解説書の翻訳は、原文そのもののスタイルシートを用いているわけですが、
WAIの文書だけでなく、W3Cの技術文書テンプレートがそのようになっています。

ですので、

- 根本的な変更をしたいのであれば、日本語訳ではなくW3Cに提案すべき
- それはそれとして翻訳のスタイルシートを変更したいというのであれば、「わかりづらい」という主観的なものではなく、客観的なものが欲しい

といったところでしょうか。

**Comment by bakera** [comment]
こちらはすみません、本家と同様のスタイルということで、このままとさせていただければと思います。
