### ISSUE TITLE
G58: collated documentの訳語について

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#375]
https://github.com/waic/wcag21/pull/346#discussion_r382963109 より。

https://www.w3.org/TR/WCAG20-TECHS/G58.html
https://waic.jp/docs/WCAG-TECHS/G58.html

https://waic.jp/docs/WCAG21/Techniques/general/G58

collated document を「対応したドキュメント」と一旦改めていただいたが、もう少しよい訳がないかを検討したい。

**Comment by momdo** [comment]
https://www.oxfordlearnersdictionaries.com/definition/english/collate?q=collate

> to collect information together from different sources in order to examine and compare it

というのを取ると、「照合」というのも語感はさておき誤りとまでは言えないのかもしれません。

**Comment by bakera** [comment]
collateは照らし合わせるというような意味で、サマリーではなくメディアの内容を過不足なく書き起こしているというニュアンスを含むように思われる。
「対照したドキュメント」などか?

**Comment by momdo** [comment]
> 「対照したドキュメント」などか?

「対照」、難解な単語でもないのでよさそうです。
