### ISSUE TITLE
勧告 A.3 Enabling funders の本文翻訳見直し（特に組織名）

### ISSUE THREAD

**Issue by MasaoYOMODA** [waic/wcag21#56]
@yaytom-ba さん、 (特に組織名に着目して)A.3 Enabling funders の本文翻訳を見直す必要があると思います。 四方田の案は以下のとおりです。ご検討ください。特に @momdo さん、 @bakera さん、8/23 WG4議論に基づきissueを立てましたが四方田の案に不都合・懸念あればご指摘ください。

（現在）
この出版物は、初期は契約番号 ED-OSE-10-C-0067、現在は契約番号 HHSP23301500054C のもとで保健福祉サービス、国立障害研究所、独立生活、リハビリテーション研究所 (NIDILRR) の米国連邦資金によって一部賄われている。この出版物の内容は、必ずしも米国保健福祉省又は米国教育省の見解や政策を反映するものではなく、また商品名、商用製品、組織の言及は米国政府による支持を意味するものではない。

⇒
（四方田案）
この出版物は、当初は契約番号 ED-OSE-10-C-0067 のもとで、現在は契約番号 HHSP23301500054C のもとで米国保健福祉省・障害者自立生活リハビリテーション研究所（NIDILRR）の政府資金によって一部賄われている。この出版物の内容は、必ずしも米国保健福祉省又は米国教育省の見解や政策を反映するものではなく、また商品名、商用製品、組織の言及は米国政府による支持を意味するものではない。

**Comment by yaytom-ba** [comment]
@MasaoYOMODA さんissue立てありがとうございました。
内容確認させていただきました。四方田さんの案に賛成です。



〜以下に対象英文箇所抜き出してまとめておきました〜
■WCAG2.0
the U.S. Department of Education, National Institute on Disability and Rehabilitation Research (NIDRR)
↓
米国教育省、米国障害者リハビリテーション研究所 (NIDRR)

■WAI-ARIA1.1
the Department of Education, National Institute on Disability, Independent Living, and Rehabilitation Research (NIDILRR)
↓
米国教育省・障害者リハビリテーション研究所（NIDILRR）

■WCAG2.1
the Health and Human Services, National Institute on Disability, Independent Living, and Rehabilitation Research (NIDILRR)
↓
米国保健福祉省・障害者自立生活リハビリテーション研究所（NIDILRR）
