### ISSUE TITLE
達成基準 1.4.13 ホバー又はフォーカスで表示されるコンテンツ

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#570]
https://waic.jp/docs/WCAG21/#content-on-hover-or-focus

> 非表示にすることができる    ポインタホバーやキーボードフォーカスを動かさずに追加コンテンツを非表示にするメカニズムが存在する。

ポインタホバー又はキーボードフォーカス

**Comment by bakera** [comment]
「ポインタホバーを動かす」は違和感があるような気がしましたが、原文が "moving pointer hover" なのでOKですね。

>A mechanism is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an input error or does not obscure or replace other content;

**Comment by caztcha** [comment]
- WCAG 2.1 本文 ( https://waic.jp/docs/WCAG21/#content-on-hover-or-focus )
- 解説書 ( https://waic.jp/docs/WCAG21/Understanding/content-on-hover-or-focus.html )
の両方で要修正ですね。

**Comment by caztcha** [comment]
PR #1320 で対応中です。
