### ISSUE TITLE
解説書の用語集へのリンクが機能しないものがある

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#571]
達成基準 1.3.1: 情報及び関係性を理解する
https://waic.jp/docs/WCAG21/Understanding/info-and-relationships.html
「プログラムによる解釈」
達成基準 2.4.6: 見出し及びラベルを理解する		
https://waic.jp/docs/WCAG21/Understanding/headings-and-labels.html
「ラベル」
達成基準 3.2.2: 入力時を理解する
https://waic.jp/docs/WCAG21/Understanding/on-input.html
「ユーザインタフェース コンポーネント」「コンテキストの変化」

といった、用語集のリンクの機能しない（href属性値のハッシュがおかしい）

**Comment by bakera** [comment]
これ本体の用語集に飛ぼうとしてフラグメントがマッチしないという結果になってますけど、そもそも本家ではページ内リンクなんですね。
https://w3c.github.io/wcag/understanding/info-and-relationships

ページ内のIDとは一致しているのでページ内リンクにする (href属性から `https://waic.jp/docs/WCAG21/` を削除する) と良さそうに思います。

https://waic.jp/docs/WCAG21/Understanding/info-and-relationships.html#dfn-programmatically-determined
