### ISSUE TITLE
administrative level の揺れ

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/wcag21#574]
https://waic.github.io/wcag21/guidelines/#input-purposes

「7. ユーザインタフェース コンポーネントの入力目的」において「administrative level」が、
「address-level3」では「行政レベル」と訳されていますが、
「address-level2」では「管理レベル」と訳されています。
「行政レベル」に統一して良いのではないでしょうか？

**Comment by momdo** [comment]
関連：
>address-level4 - 四つの行政レベルでのアドレスの中で、最もきめ細かい行政レベル。

アドレス→住所

**Comment by caztcha** [comment]
PR #1319 で対応中です。
