### ISSUE TITLE
解説書：2.5.1 ポインタのジェスチャの更新

### ISSUE THREAD

**Issue by masuP9** [waic/wcag21#577]
図表が理解の大きな助けになるので、日本語訳にも図表を掲載したいです。

- https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html#figure-path-based-gesture-1
- https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html#figure-path-based-gesture-2

**Comment by bakera** [comment]
解説書の日本語訳を始めた後で追加された画像ですね。

https://github.com/w3c/wcag/blob/master/understanding/21/img/path-based-gesture-1.png
https://github.com/w3c/wcag/blob/master/understanding/21/img/path-based-gesture-2.png

「本家側のアップデートに追いつけていない」という問題なので、個別に対応するというより全体的な対応方針を検討しつつ取り組みたいところです。

**Comment by momdo** [comment]
直接diffのURLを貼ることができないのでスクショで代用しますが、[最新版のUnderstanding](https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures)はかなり手が入っていて、
今から作業すると図だけでなく、本格的な訳の更新になりそうです。

![diffのスクリーンショット](https://user-images.githubusercontent.com/8347177/94503290-19911380-0241-11eb-969e-d0befb60623d.png)
