### ISSUE TITLE
"style property"の訳語

### ISSUE THREAD

**Issue by motchie** [waic/wcag21#59]
[達成基準1.4.12](https://waic.github.io/wcag21/guidelines/#text-spacing) では "style property" を「スタイルプロパティ」としていますが、 [用語集](https://waic.github.io/wcag21/guidelines/#dfn-style-properties) では "スタイル属性" としています。用語集の方には もんどさんの [mark] が付いています。

1.4.12 の例外に関する記載の訳出にあたり、"style property"の訳語方針を確認したいです。

**Comment by bakera** [comment]
ここの説明は完全にCSSのプロパティの説明であるように思いますし、CSSのプロパティはそのまま「プロパティ」とすることが一般的だと思いますので、「スタイルプロパティ」で良いと思います。

**Comment by bakera** [comment]
プルリクエスト #79 にて対応済みですのでクローズします。
