### ISSUE TITLE
1.3.3の事例2の文章に重複がある

### ISSUE THREAD

**Issue by kuma0520** [waic/wcag21#622]
## 要件
1.3.3の事例2の文章に重複があるように思えました。
同じ文章が2回繰り返されるので消していただきたいです！

現在は下記のようになっています。

> 事例 2: 複数のページによるオンライン調査
> 複数のページによるオンライン調査では、あるページから次のページへ遷移するためのリンクに緑色の矢印のアイコンを使っていて、それをコンテンツの右下に置いている。複数のページによるオンライン調査では、あるページから次のページへ遷移するためのリンクに緑色の矢印のアイコンを使っていて、それをコンテンツの右下に置いている。矢印には「次へ」というラベルがはっきりと記述されていて、「次の調査へ進むには、最後の質問の右下にある『次へ』というラベルの付いた緑色の矢印のアイコンを選択してください。」という説明文が書かれている。この例では、アイコンを特定できるように、配置、色及びラベルを用いている。

閲覧したページは下記になります。
https://waic.jp/docs/WCAG21/Understanding/sensory-characteristics.html

### 期待する状態

複数のページによるオンライン調査では、あるページから次のページへ遷移するためのリンクに緑色の矢印のアイコンを使っていて、それをコンテンツの右下に置いている。矢印には「次へ」というラベルがはっきりと記述されていて、「次の調査へ進むには、最後の質問の右下にある『次へ』というラベルの付いた緑色の矢印のアイコンを選択してください。」という説明文が書かれている。この例では、アイコンを特定できるように、配置、色及びラベルを用いている。

**Comment by momdo** [comment]
@kuma0520 プルリクエストをお待ちしております！
