### ISSUE TITLE
Working exampleの訳語について

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#628]
https://github.com/waic/wcag21/pull/324#issuecomment-590699429 より

> Working example → 実施例、って他でもそうしていましたっけ?
> ここでは動く例 (= 実際に動作するHTMLサンプル) のことなので、個人的にはちょっと違和感があり、「動作例」とかのほうがいいようにも思いました。

[working example](https://eow.alc.co.jp/search?q=working+example)
《特許》実施例　に引っ張られたんですかね。いずれにせよ、特許の話なので、例えば「動作例」とした方がよさそうではあります。

**Comment by caztcha** [comment]
個人的には、@momdo さんの意見に賛成です。訳語としては、私も「動作例」が簡潔でよいかなと思います。
よろしければ、私の方でマルチファイル検索をかけて一括修正します。

**Comment by momdo** [comment]
@caztcha 
よいと思います…！

**Comment by caztcha** [comment]
了解です！別途、プルリクエスト出しますね。

**Comment by caztcha** [comment]
PR #1333 で対応中です。
