### ISSUE TITLE
3.2.2のコンテキストの変化へのリンクミス

### ISSUE THREAD

**Issue by kuma0520** [waic/wcag21#631]
[達成基準 3.2.2](https://waic.jp/docs/WCAG21/Understanding/on-input.html)を読んでいて、ところどころに[コンテキストの変化](https://waic.jp/docs/WCAG21/#dfn-changes-of-context)のリンクが機能していないように思えました。

調べてみたところリンク先のURLのスペルにsが入っていることが原因かと思われます。

また、他の達成基準でもコンテキストの変化への
リンクが間違っていたように思えましたが、どこだったか覚えていません...

正しいと思われるリンク
https://waic.jp/docs/WCAG21/#dfn-change-of-context

該当ページで機能していないリンク
https://waic.jp/docs/WCAG21/#dfn-changes-of-context

**Comment by momdo** [comment]
@kuma0520 

コメントありがとうございます。

> 達成基準 3.2.2を読んでいて、ところどころにコンテキストの変化のリンクが機能していないように思えました。

解説書内の「コンテキストの変化」のリンクがどうやらおかしいということですね。

「達成基準 3.2.2を理解する」などの、個別の解説書のページ冒頭には達成基準がありますが、そこでのリンクは原文ではなく、解説書末尾の「重要な用語」へのリンクに変更しています。

まだWAIC本番ページには反映されていませんが、
https://waic.github.io/wcag21/understanding/on-input.html
ではリンクが正常に動作していると思われます。いかがでしょうか？

**Comment by momdo** [comment]
それはそうと、

```html
<a href="#dfn-changes-of-context" target="terms" style="">コンテキストの変化</a>
```

と、不要な属性がありますね…

**Comment by kuma0520** [comment]
>まだWAIC本番ページには反映されていませんが、
https://waic.github.io/wcag21/understanding/on-input.html
ではリンクが正常に動作していると思われます。いかがでしょうか？

ご回答ありがとうございます！解説書末尾の重要な用語へのリンクがされていました！

素人ながら率直な疑問なのですが、[G200](https://waic.jp/docs/WCAG-TECHS/G200.html)の内容的に問題ないんですかね？
target属性の問題だとは思いますが...
こちらを元に解消されるんですかね！https://github.com/waic/wcag21/issues/632

それと、解説書内の下記のリンクも今後解消されるといった認識でよろしいですかね？
既に作業されていたらすみません！
https://waic.github.io/wcag21/understanding/on-input.html#dfn-web-page
https://waic.github.io/wcag21/understanding/on-input.html#dfn-user-agent
https://waic.github.io/wcag21/understanding/on-input.html#dfn-viewport

【蛇足】
target属性に対象のフレームなどのname属性値を指定できるの知らなかったです...。
なので全く分からずスルーしてました...

**Comment by momdo** [comment]
>それと、解説書内の下記のリンクも今後解消されるといった認識でよろしいですかね？
既に作業されていたらすみません！
https://waic.github.io/wcag21/understanding/on-input.html#dfn-web-page
https://waic.github.io/wcag21/understanding/on-input.html#dfn-user-agent
https://waic.github.io/wcag21/understanding/on-input.html#dfn-viewport

今度は用語からWCAG 2.1へのリンクが切れてしまっているわけですね……。
一括置換するとこういう罠があるわけですか。修正しておきます。

**Comment by momdo** [comment]
@kuma0520 

サイト更新を行いましたが、このissueに関しては解消されていると思います。
こちら問題ないでしょうか？

**Comment by kuma0520** [comment]
@momdo 
ご連絡遅れました！mm
確認しましたところ本件に関する範囲は問題なかったのでこちらのissueをcloseします！
ご対応ありがとうございました！

下記のissueに関しては修正箇所が全域に渡り修正が多いと思われますが、引き続きよろしくお願いします！
https://github.com/waic/wcag21/issues/632
