### ISSUE TITLE
解説書内のリンクに不要な属性がある

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#632]
https://github.com/waic/wcag21/issues/631#issuecomment-671889961 より、たとえば
https://waic.github.io/wcag21/understanding/on-input.html で、

```html
<a href="#dfn-changes-of-context" target="terms" style="">コンテキストの変化</a>
```

のように、不要な`target`属性、空の`style`属性があるのでこれらを削除する。

**Comment by bakera** [comment]
本家の方にはこの属性がないので削除ですね。

https://w3c.github.io/wcag/understanding/on-input
