### ISSUE TITLE
解説書 新フローの訳注を考える

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#638]
was #627

- 文言そのものを考える
- ファイルのどこに挿入するかを考える

**Comment by bakera** [comment]
本家側で解説書が更新された部分について、issue等で指摘がある。
全体を一気にアップデートするのは厳しいが、特定箇所のみ翻訳にも反映しても良いのではないか、という話がある。

とはいえ翻訳全体は特定の版を参照している形になっているので、特定箇所だけ最新になっているのは変といえば変。
そこで、他の部分とは版が異なるものを反映している旨を訳注でフォローする必要がある。
