### ISSUE TITLE
modalitiesの訳語について

### ISSUE THREAD

**Issue by tokimari** [waic/wcag21#65]
関連: https://github.com/waic/wcag21/pull/63#pullrequestreview-156754688

---

`2.5 Input Modalities`の訳語として「入力モダリティ」という表記がありますが、「モダリティ」という訳語はなかなか理解しづらいように思います。
他に該当する用語もないことと、他の箇所にもモダリティという訳語が出てきていたため、2.5では「入力モダリティ」としていますが、他にいい案があれば検討したいです。

（ちなみに社内のガイドライン作成時には、わかりやすさ重視で「様式」「方式」「方法」などの案が出たのですが、意訳気味なので・・）

### 該当箇所

該当箇所は下記の４箇所です。

> #### ガイドライン 2.5 Input _Modalities_§
> Make it easier for users to operate functionality through various inputs beyond keyboard.
https://waic.github.io/wcag21/guidelines/#input-modalities

（https://github.com/waic/wcag21/pull/63 で、ひとまず「入力モダリティ」に揃える予定）

> #### 達成基準 2.5.6 入力メカニズム非依存
> プラットフォームで提供されている入力*モダリティ*の使用を、ウェブコンテンツが制限しない。ただし、その制限が必要不可欠な場合、コンテンツのセキュリティのために必要な場合、又はユーザ設定を尊重するうえで必要な場合は例外とする。
https://waic.github.io/wcag21/guidelines/#concurrent-input-mechanisms

> #### プログラムによる解釈 (プログラムによる解釈が可能) (programmatically determined (programmatically determinable))
> 支援技術を含む様々なユーザエージェントが抽出でき、利用者に様々な感覚*モダリティ*で提示できるような形のデータがコンテンツ制作者によって提供されたとき、そのデータがソフトウェアによって解釈されること。
https://waic.github.io/wcag21/guidelines/#dfn-programmatically-determinable

> #### プログラムによる解釈が可能なリンクのコンテキスト (programmatically determined link context)
> リンクとの関係性からプログラムによる解釈が可能であり、リンクテキストと結びつけることができ、様々な感覚*モダリティ*で利用者に提示することができる付加的情報。
https://waic.github.io/wcag21/guidelines/#dfn-programmatically-determined-link-context

**Comment by bakera** [comment]
四方田さんから、カタカナのままにして訳注でフォローするのもありではないかという意見がありました。

**Comment by bakera** [comment]
訳注を入れても良いがどういう訳注を入れるべきか、言葉の説明自体がなかなか難しいという意見がありました。
いったん訳注ナシで公開してみて、わかりにくいという意見が多いよううであれば検討してみる方向にしたいと思います。

**Comment by momdo** [comment]
あるいは、解説書で出現するようであれば、訳注として追記するなど（将来の課題。ただし、ぱっと見で解説書に出てこないような、というコメントもあり）。

**Comment by momdo** [comment]
訳注候補（ミーティングSlackログより）：
https://ja.wikipedia.org/wiki/%E3%83%A6%E3%83%BC%E3%82%B6%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9#%E3%83%A2%E3%83%80%E3%83%AA%E3%83%86%E3%82%A3%E3%81%A8%E3%83%A2%E3%83%BC%E3%83%89
