### ISSUE TITLE
WCAG 2.1 解説書「達成基準 2.1.4: 文字キーのショートカットを理解する」の翻訳改善について

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#667]
メールにてご指摘をいただきました。以下転載となります。

========

WCAG 2.1 解説書「達成基準 2.1.4: 文字キーのショートカットを理解する」では

"A speech user filling in a text input form may find that a phrase that is accidentally picked up by the speech microphone results in stray text being entered into the field, but that is easily seen and undone."

に相当する部分の訳文が

「テキスト入力フォームを記入している音声入力の利用者は音声マイクに偶然拾われたフレーズが、フィールドに入力されているテキストをもたらすが、これは簡単に確認及び元に戻すことに気づくかもしれない。」

となっていますが、"may find"の対象は"that a phrase...stray text being entered into the field"までで、またここで言及されている「フィールドに入力されているテキスト」は音声マイクが"accidentally"に拾った音声から変換された（本来意図された入力内容ではない）"stray text"なので、例えば

「音声入力でテキスト入力フォームに記入している利用者は、音声マイクに偶然拾われたフレーズが余計なテキストとしてフィールドに入力されていることに気づくかもしれないが、これは簡単に見つけて取り消すことができる。」

のような形の方が原文の意味に近くなるかもしれません。
参考になれば幸いです。

**Comment by bakera** [comment]
ひとまずURLを貼っておきます。

翻訳:
https://waic.jp/docs/WCAG21/Understanding/character-key-shortcuts.html

原文:
https://w3c.github.io/wcag/understanding/character-key-shortcuts

**Comment by bakera** [comment]
ご指摘箇所のすぐ上のあたりで、

> Inadvertent strings of characters from the speech application are not interpreted as shortcuts if a modifier key is required. 

が日本語訳から抜けているようにも見えますね。

**Comment by momdo** [comment]
お問い合わせフォームが活躍している…！

（原文pushするといってまだできてないですが）さておき、

>>Inadvertent strings of characters from the speech application are not interpreted as shortcuts if a modifier key is required.
>
>が日本語訳から抜けているようにも見えますね。

こちらについては、あとになって増えたようです。
https://github.com/w3c/wcag/blob/dfad867083e7137d27e472e3b85aaac8cd2c2c77/understanding/character-key-shortcuts.html
