### ISSUE TITLE
7章での ”semantic purpose”の訳語・訳注について

### ISSUE THREAD

**Issue by MasaoYOMODA** [waic/wcag21#69]
7. Input Purposes for User Interface Components で 

”semantic purpose”を「セマンティックな用途」と訳し、
「訳注：この節での「セマンティックな」という記載の趣旨は、ウェブを構成するシステムが意味的に正確に解釈できるような、というものである。」を追記している。

文脈的に、より適切な訳語・訳注があれば修正したい。
尚 議論が収束しない場合は、上記の訳語・訳注を維持する。

**Comment by motchie** [comment]
今、注記の中に訳注が入っているので、注記の上の段落に、訳注のマークアップをして、そこに移す。

**Comment by motchie** [comment]
[できれば、セマンティックな目的を示す] → [できれば、セマンティック上の目的を示す]
[この節での「セマンティックな」という記載の趣旨は、]→[この節での「セマンティック上の」という記載の趣旨は、]

**Comment by bakera** [comment]
プルリクエスト #78 にて対応済みですのでクローズします。
