### ISSUE TITLE
/index.html へのコミットを /guidelines/index.html に移植する

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#71]
/index.html はいったん凍結して /guidelines/index.html を作業する想定だったが、前者にコミットされたものがいくつかある。8/12以降のコミットを確認して移植する。
その後、/index.htmlは削除する。

**Comment by tokimari** [comment]
https://github.com/waic/wcag21/commits/master/index.html から察するに

- [ ] https://github.com/waic/wcag21/pull/67
- [ ] https://github.com/waic/wcag21/pull/70
- [ ] https://github.com/waic/wcag21/pull/64

の３PRの内容を反映すればよさそうです

**Comment by momdo** [comment]
マージしたので閉じます。
