### ISSUE TITLE
日本語訳リソースへのリンク方法

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#8]
WCAG 2.0では、Understanding/Techniques/Quick ReferenceへのリンクはJavaScriptで挿入されている。
WCAG 2.1もこれに倣うのか、あるいはHTMLソースで挿入するのか決めておく。
See also #6

**Comment by bakera** [comment]
同様にJavaScriptで後から挿入する方針としたいと思います。

**Comment by bakera** [comment]
ちなみにJSはこちら。
https://waic.jp/docs/WCAG20/waic_link.js

**Comment by bakera** [comment]
jQueryのコードですね。直前で以下を呼んでいる模様。
```
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
```

**Comment by bakera** [comment]
コード中で参照されている `p.sctxt` は以下のようなもの。

```
<p class="sctxt"><strong class="sc-handle">1.1.1 非テキストコンテンツ:</strong>  利用者に提示されるすべての<a title="definition: 非テキストコンテンツ (non-text content)" href="#non-text-contentdef" class="termref">非テキストコンテンツ</a>には、同等の目的を果たす<a title="definition: テキストによる代替 (text alternative)" href="#text-altdef" class="termref">テキストによる代替</a>が提供されている。ただし、次の場合は除く:
 (レベル A)
</p>
```

2.1では該当箇所のマークアップが大幅に変更されて、見出し、リンク、説明テキストの順になっている。2.1ではリンク箇所はフロートして本文が回り込むようになっているので、たぶんこのケア自体必要ないはず。

**Comment by momdo** [comment]
このissue自体は解決できていると思いますのでCloseします。
