### ISSUE TITLE
達成基準 1.3.5 入力目的の特定

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#84]
箇条書きの2つめ

> コンテンツが、入力フィールドに入力された値に期待される意味の特定をサポートしたテクノロジーで実装されている。

「入力フィールドに入力された値に期待される意味の特定」という表現が若干わかりにくい印象を受けました。
また、主語「コンテンツが」と述語「実装されている」が離れているので、近づけてもよいかなと思いました。

(改善案)
「入力フィールドに入力される値として想定される意味の特定をサポートするテクノロジーによって、コンテンツが実装されている。」

**Comment by momdo** [comment]
指摘箇所の原文は、
>The content is implemented using technologies with support for identifying the expected meaning for form input data.

ですが、現在の訳の「入力フィールド」というのはどこからでできたのでしょうか…？

あと、technologyは用語集にある語ですね。
https://waic.github.io/wcag21/guidelines/#dfn-technologies

「コンテンツが」を後ろに持ってくる場合、箇条書きの1つめのほうも「入力フィールドが」というのもこの位置でいいのかどうか、検討したいですね。

**Comment by caztcha** [comment]
@momdo コメントありがとうございます。なるほど、そうですね。

2つめの箇条書きの「入力フィールドに入力される値」という訳出は、原文の「form input data」から来ているものと思われます。原文に素直に、「フォーム入力データ」としてもよいかもしれませんね。

technology は用語集にある語なので、用語集と合わせて「技術」と訳すのがよいと思います。

> 「コンテンツが」を後ろに持ってくる場合、箇条書きの1つめのほうも「入力フィールドが」というのもこの位置でいいのかどうか、検討したいですね。

...については、箇条書きの1つめで「入力フィールドが」の位置を検討したのですが、これについては文頭に置くのがよいかと思います。

以上を勘案して、ふたつの箇条書きを、以下のようにしてはと思いますが、いかがでしょうか。

---

(改善案)

- 入力フィールドが、「ユーザインタフェース コンポーネントの入力目的」セクションで示される目的を提供している、 かつ
- フォーム入力データとして想定される意味の識別をサポートする技術を用いて、コンテンツが実装されている。

---

**Comment by momdo** [comment]
見出しでIdentifyを特定としているので、改善案の2つ目も

意味の識別を→意味の特定を

とするのが良さそうです（ほかはこれで大丈夫かと）。

>もしこの改善案でよければ、「7. ユーザインタフェース コンポーネントにおける入力目的」の見出しも「7. ユーザインタフェース コンポーネントの入力目的」とする必要がありますね。

この案に賛成します。

**Comment by caztcha** [comment]
[PR #166](https://github.com/waic/wcag21/pull/166) にて対応しました。identify の訳は、もんどさんのご指摘の通り、「識別」ではなく「特定」で統一しています。

**Comment by momdo** [comment]
マージ済みなので閉じます。
