### ISSUE TITLE
達成基準 1.4.10 リフロー

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#85]
> 次の 2 次元において、スクロールを必要とせずに情報や機能を失うことなくコンテンツを提示することができる:

(改善案)
**以下において、2次元のスクロールを必要とせずに**、情報や機能を失うことなくコンテンツを提示することができる:

**Comment by momdo** [comment]
「次の」や「以下において」、という文言は本当に必要なのでしょうか…？また、

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#reflow
>Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions for:

without loss of... と without requiring... がandで結ばれているのがニュアンスとして出ていないのが違和感を覚えます。

**Comment by caztcha** [comment]
@momdo 

> without loss of... と without requiring... がandで結ばれているのがニュアンスとして出ていないのが違和感を覚えます。

なるほど、そうですね。
以下のように改善案を考えてみました。この文末の「for」と、そのあとに2つの箇条書きが続いていることを考えると、「以下において」という表現は要るのかな、と思いました。

(改善案)
コンテンツは、情報や機能を損なうことなく、かつ、以下において2次元スクロールを必要とせずに表示することができる。

**Comment by momdo** [comment]
> この文末の「for」と、そのあとに2つの箇条書きが続いていることを考えると、「以下において」という表現は要るのかな、と思いました。

了解です。

orを「又は」とするので、
情報や機能を損なうことなく→情報又は機能を損なうことなく
とすればよいと思います。

can be presented は 「表示することができる」で誤りではないですが、どうしましょうか。
- 用語集に「提示 (presentation)」とあるので、動詞形も「提示する」としたほうがよいのか
- can を「することができる」とするのは辞書的に正しいですが、JIS Z 8301 附属書 Hには「できる」とあって、これにあわせた方がよいのか

**Comment by caztcha** [comment]
@momdo なるほどなるほど、ありがとうございます。以下のようにしたほうが、文もすっきりするのでよい気がします！

(改善案)
コンテンツは、情報又は機能を損なうことなく、かつ、以下において2次元スクロールを必要とせずに提示できる。

**Comment by caztcha** [comment]
[PR #83](https://github.com/waic/wcag21/pull/183) にて対応しました。

**Comment by momdo** [comment]
マージされたので閉じます。
