### ISSUE TITLE
達成基準 1.4.12 テキストの間隔

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#86]
> 以下のテキストスタイルプロパティをサポートするマークアップ言語を用いて実装されているコンテンツにおいては、以下のとおりすべて設定し、かつ他のスタイルプロパティを変更しない場合、コンテンツ又は機能が損なわれない:

原文「by setting all of the following」を「以下のとおりすべて設定し」と訳していますが、原文が「by setting all as follows」ではないので、「以下をすべて設定し」でよいのではないでしょうか。

(改善案)
以下のテキストスタイルプロパティをサポートするマークアップ言語を用いて実装されているコンテンツにおいては、**以下をすべて設定し**、かつ他のスタイルプロパティを変更しない場合、コンテンツ又は機能が損なわれない:

また、「例外」が以下のとおり訳されていますが :

> 例外: 文章でこれらのテキストスタイルプロパティを1つ以上使用しない自然言語およびスクリプトは、その言語やスクリプトの組み合わせに存在するプロパティだけを使うことを確認することができる。

ここで言う「script」は、自然言語の記述を示していると思われるので、「スクリプト」と訳すのはわかりにくいかもしれません。また「確認することができる」は、conform を confirm と誤解しているものと思われます。

(改善案)
例外: これらのテキストスタイルプロパティを1つ以上使用しない**自然言語および記述においては**、その**言語や記述**の組み合わせに存在するプロパティ**だけを用いて、この達成基準への適合とみなす**ことができる。

**Comment by momdo** [comment]
前半パートの指摘ですが、土屋さんの指摘はそれでいいとして、原文は
> no loss of content or functionality occurs by setting all of the following and by changing no other style property:

ifもwhenもないが「場合」としていいのかどうか…？
by setting ... および by changing ～ によって、no loss of content or functionality occurs [コンテンツ又は機能の損失(or喪失?)が起きない(or生じない?)] ぐらいでどうか？

後半の例外に関する指摘ですが、「スクリプト」がわかりにくいというのには同意します。しかし、Wikipediaの[スクリプト](https://ja.wikipedia.org/wiki/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88)をパッと見る感じでは、「記述」というのは「コンピュータ、IT」の上から2つめのもの、あるいは最後のもの、と言うことなんでしょうか…。（すみません、理解が追いついていません。）

また、改善案ですが、"in written text"は意図的に飛ばしている？のと、conform を「適合」とするのは妥当として、「適合とみなす」とするのはどういう根拠でしょうか？

**Comment by caztcha** [comment]
@momdo コメントありがとうございます。

前半パートについては、御意です。
後半の例外についてですが、この達成基準で言うところの scripts は、Wikipedia の[スクリプト](https://ja.wikipedia.org/wiki/スクリプト)においては、「コンピュータ、IT」ではなく「一般概念の基本」のほうかなと。(「手書き」風かどうかは別として、「書体」に近いニュアンスかなと思いました。)
"in written text" の訳出、たしかに抜けていますね。
「適合とみなすことができる」は「適合とすることができる」のほうがよさげですね。

以上を勘案して、改善案を検討しました。

(改善案)
以下のテキストスタイルプロパティをサポートするマークアップ言語を用いて実装されているコンテンツにおいては、以下をすべて設定し、かつ他のスタイルプロパティを変更しないことによって、コンテンツ又は機能の損失が生じない:

例外: テキスト表記においてこれらのテキストスタイルプロパティを1つ以上使用しない自然言語および記述では、その言語や記述の組み合わせに存在するプロパティだけを用いて、この達成基準への適合とすることができる。

**Comment by momdo** [comment]
> 後半の例外についてですが、この達成基準で言うところの scripts は、Wikipedia のスクリプトにおいては、「コンピュータ、IT」ではなく「一般概念の基本」のほうかなと。(「手書き」風かどうかは別として、「書体」に近いニュアンスかなと思いました。)

改めて考えてみると、原文でHuman languages and scriptsとあるので、同じ粒度のものがこないと不自然かなと。件のWikipediaでいうなら「コンピュータ、IT」の1番目を指していると思います。（HTMLでいうなら、lang属性値がわかりやすいでしょうか）

例を挙げるなら、日本語の文字体系（つまりひらがな・カタカナ・漢字）を使うと、この達成基準にある「単語の間隔をフォントサイズの少なくとも 0.16 倍に設定する」というのが適用されない（日本語は通常分かち書きをしない）ことになる（と私は解釈しています）わけですから、そのことがわかるscriptに対する訳語を当てたいところです。

なので、順番が前後しますが、

例外: テキスト表記においてこれらのテキストスタイルプロパティの一つ以上を使用しない自然言語及び文字体系では、その言語と文字体系の組み合わせに存在するプロパティだけを用いて、この達成基準に適合することができる。

といった感じでしょうか…（とりあえずscriptを文字体系としましたが、より適当な訳語があればそれで）

---
前半の
> 他のスタイルプロパティを変更しないことによって

について、原文では
> by changing no other style property

ですが、なんかこう腑に落ちないものが（漠然としていますが）

**Comment by caztcha** [comment]
> 例を挙げるなら、日本語の文字体系（つまりひらがな・カタカナ・漢字）を使うと、この達成基準にある「単語の間隔をフォントサイズの少なくとも 0.16 倍に設定する」というのが適用されない（日本語は通常分かち書きをしない）ことになる（と私は解釈しています）わけですから、そのことがわかるscriptに対する訳語を当てたいところです。

そうそう、まさにそうですね。
原文でHuman languages and scriptsとあるので、human language と scripts は同じ粒度のものがこないと不自然、というのも納得です。「文字体系」なるほど、よいと思います。(僕自身は腹落ちしました。)

---

前半の原文「by changing no other style property」が腑に落ちない、というのは、僕も一瞬思いましたが、「changing no other style properties」を「not changing other style properties」と解釈すれば（ネイティブの英語表現としては前者のほうが多分自然なんですかね）いいのかな、とは思いました。


(改善案)
以下のテキストスタイルプロパティをサポートするマークアップ言語を用いて実装されているコンテンツにおいては、以下をすべて設定し、かつ他のスタイルプロパティを変更しないことによって、コンテンツ又は機能の損失が生じない:

(箇条書き省略)

例外: テキスト表記においてこれらのテキストスタイルプロパティの一つ以上を使用しない自然言語及び文字体系では、その言語と文字体系の組み合わせに存在するプロパティだけを用いて、この達成基準に適合することができる。

**Comment by caztcha** [comment]
[PR #184](https://github.com/waic/wcag21/pull/184) にて対応しました。

**Comment by momdo** [comment]
マージされたので閉じます。
