### ISSUE TITLE
達成基準 1.4.13 ホバー又はフォーカスで表示されるコンテンツ

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#87]
> ポインタホバーやキーボードフォーカスを受け取ったり外したりすることで、追加コンテンツの表示及び非表示をさせる場合は、以下の要件を満たす:

「ポインタホバーやキーボードフォーカスを受け取ること」は「追加コンテンツを表示させること」と対になっていて、「ポインタホバーやキーボードフォーカスを外すこと」は「追加コンテンツを非表示させること」と対になっていると思いますので、そのニュアンス（対の関係）がもう少し明確に伝わるとよいかな、と思います。

(改善案)
ポインタホバーやキーボードフォーカスを受け取ったり外したりすることで、**追加コンテンツを表示させたり非表示させたりする**場合は、以下の要件を満たす:

**Comment by momdo** [comment]
pointer hover or keyboard focus は、「又は」とした方が良いのでは。
> 受け取ったり外したりする

というのはand thenのニュアンスが出ていないのでは（並列ではないような）。
https://eowf.alc.co.jp/search?q=and+then
https://ejje.weblio.jp/content/and+then

（まあそうすると、"become visible and then hidden"をどう取ればいいのか…という問題も出てきそうですが）

**Comment by caztcha** [comment]
@momdo たしかに、and then のニュアンスが出ていないですね。改めて改善案を考えてみました。(案1だと「そして」がくどいかな...という気もしたので、案2も考えました。)

(改善案1)
ポインタホバー又はキーボードフォーカスを受け取り、そして外すことで、追加コンテンツを表示させ、そして非表示させる場合は、以下の要件を満たす:

(改善案2)
ポインタホバー又はキーボードフォーカスを受け取り、外すことで、追加コンテンツを表示させ、非表示させる場合は、以下の要件を満たす:

**Comment by caztcha** [comment]
@momdo なるほど、むしろそのほうがよさそうですね。

(改善案)
ポインタホバー又はキーボードフォーカスを受け取ってから外すことで、追加コンテンツを表示させてから非表示させる場合は、以下の要件を満たす:

**Comment by momdo** [comment]
非表示**に**させる
のほうが日本語として自然でしょうか？（他は大丈夫だと思います）

**Comment by caztcha** [comment]
[PR #186](https://github.com/waic/wcag21/pull/186) にて対応しました。

**Comment by momdo** [comment]
マージされたので閉じます。
