### ISSUE TITLE
達成基準 2.1.4 文字キーのショートカット

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#88]
> コンテンツに文字 (大文字と小文字を含む)、句読点、数字、又は記号のみを使用したキーボードショートカットが実装されている場合、少なくとも次のいずれかを満たしている:

(改善案 : 「コンテンツに」の位置を変更)
文字 (大文字と小文字を含む)、句読点、数字、又は記号のみを使用したキーボードショートカットが**コンテンツに**実装されている場合、少なくとも次のいずれかを満たしている:

また、箇条書きの「再割り当て」の項で、「non-printable keyboard characters」を「非表示文字」と訳していますが、若干わかりにくいかなと思いました。

(改善案)
再割り当て: 1 つ以上の**非文字入力キー** (例えば Ctrl や Alt など) にショートカットを再割り当てするメカニズムが利用できる

**Comment by momdo** [comment]
前半の改善案（「コンテンツに」の位置の変更）はこれでよいと思います。
ただ、日本語で句読点というと「、。」しか思い浮かばなくなってしまう（おそらく、コロンやセミコロンも入っているような…）のですが、記号もあるので、まあこれはこれでいいか…と言う気もしています。

後半は…どう訳すのがいいのでしょうね。

**Comment by caztcha** [comment]
@momdo 後半の「non-printable keyboard characters」の訳は、悩ましいですね。

この達成基準は、文字キーのみで構成されるショートカットキー機能がある場合、ユーザーの音声入力 (発話) がそ
のショートカットキー機能のトリガーとなり、ユーザーの意図しない挙動を引き起こしてしまう恐れがあることを問題視しているので、
https://knowbility.org/blog/2018/WCAG21-214CharacterKeyShortcuts/
それを回避するために、単体で文字入力しないキーを併用しましょうね、と言っているのかなと理解しました。というわけで「非文字入力キー」と訳してみたのですが...。

**Comment by bakera** [comment]
言いたいのは「修飾キー」ということなのでしょうけれど。
そうすると、原文が modifier key じゃないじゃん、という話になり、なかなか難しいですね。
非表示文字、あるいは非印字文字とした上で訳注とか?

**Comment by caztcha** [comment]
@bakera なるほど、「non-printable keyboard characters」を「非印字文字」と訳すのは、よいかもしれませんね。

(改善案)
再割り当て: 一つ以上の非印字文字 (例えば Ctrl や Alt など) を使用するようにショートカットを再割り当てするメカニズムが利用できる

**Comment by caztcha** [comment]
[PR #194](https://github.com/waic/wcag21/pull/194) にて対応しました。

**Comment by momdo** [comment]
マージされたので閉じます。
