### ISSUE TITLE
達成基準 2.2.6 タイムアウト

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#89]
> 20 時間以上利用者が何も操作をしないときにデータが保存されない限り、データの損失を引き起こすユーザーの無操作の時間が警告される。

この訳ですと、「ユーザーの無操作」が20 時間に満たない場合、警告なしにデータの損失が引き起こされてもよいように解釈されてしまいそうです。

また、「ユーザーの無操作」は用語統一の観点から、「**利用者**の無操作」とするのがよいかと思います。

(改善案)
データ損失を引き起こす恐れのある[利用者の無操作](https://waic.github.io/wcag21/guidelines/#dfn-user-inactivity)の残り時間が、利用者に警告される。ただし、利用者が20時間以上何もしなくてもデータが保持される場合は、この限りではない。

---

併せて、用語解説の「ユーザーの無操作」も、「ユーザー」を「利用者」に置換が必要かと思います。
https://waic.github.io/wcag21/guidelines/#dfn-user-inactivity

**Comment by momdo** [comment]
@tokimari 
今のところはこれですね…（こんなの絶対分かるわけないよ！）
https://github.com/waic/wcag20/wiki/%E7%94%A8%E8%AA%9E%E3%83%BB%E7%94%A8%E5%AD%97%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6#user

**Comment by caztcha** [comment]
[PR #161](https://github.com/waic/wcag21/pull/161) にて対応しました。
