### ISSUE TITLE
5.1 Interpreting Normative Requirements 訳出案

### ISSUE THREAD

**Issue by motchie** [waic/wcag21#9]
Slackでお話していた、 `git diff` で修正箇所が適切に出ない件の対策案として。

# 原文
https://www.w3.org/TR/WCAG21/#interpreting-normative-requirements

<h3 id="x5-1-interpreting-normative-requirements"
resource="#x5-1-interpreting-normative-requirements">
<span property="xhv:role" resource="xhv:heading">
<span class="secno">5.1 </span>
Interpreting Normative Requirements<span class="permalink" typeof="bookmark">
<a href="#interpreting-normative-requirements"
aria-label="Permalink for 5.1 Interpreting Normative Requirements"
title="Permalink for 5.1 Interpreting Normative Requirements" property="url">
<span property="title"
content="5.1 Interpreting Normative Requirements">§</span></a>
</span></span></h3>

<p>The main content of WCAG 2.1 is <a href="#dfn-normative" class="internalDFN"
data-link-type="dfn">normative</a> and defines requirements that impact conformance claims. 
Introductory material, appendices, sections marked as "non-normative", diagrams, examples,
and notes are <a href="#dfn-informative" class="internalDFN"
data-link-type="dfn">informative</a> (non-normative).
Non-normative material provides advisory information to help interpret
the guidelines but does not create requirements that impact a conformance claim.</p>
<p>The key words <em class="rfc2119" title="MAY">MAY</em>,
<em class="rfc2119" title="MUST">MUST</em>, 
<em class="rfc2119" title="MUST NOT">MUST NOT</em>,
<em class="rfc2119" title="NOT RECOMMENDED">NOT RECOMMENDED</em>,
<em class="rfc2119" title="RECOMMENDED">RECOMMENDED</em>,
<em class="rfc2119" title="SHOULD">SHOULD</em>,
 and <em class="rfc2119" title="SHOULD NOT">SHOULD NOT</em>
are to be interpreted as described in
[<cite><a class="bibref" href="#bib-RFC2119">RFC2119</a></cite>].</p>

# 訳出案
<h3 id="x5-1-interpreting-normative-requirements" resource="#x5-1-interpreting-normative-requirements">
<span property="xhv:role" resource="xhv:heading">
<span class="secno">5.1 </span>規定実装要件<span class="permalink" typeof="bookmark">
<a href="#interpreting-normative-requirements" aria-label="Permalink for 5.1 Interpreting Normative Requirements" title="Permalink for 5.1 Interpreting Normative Requirements" property="url">
<span property="title" content="5.1 Interpreting Normative Requirements">§</span></a></span></span></h3>

<p>WCAG 2.1の主要な内容は<a href="#dfn-normative" class="internalDFN" data-link-type="dfn">規定</a>であり適合表明を満たす要件を定義する。
入門用資料、附録、「規定ではない」と示された節、図、事例と注記は<a href="#dfn-informative" class="internalDFN" data-link-type="dfn">参考情報</a> (規定ではない)である。
規定ではない資料はガイドラインの解釈を手助けする参考情報を提供するが適合表明を満たす要件は提示しない。</p>
<p>キーワード<em class="rfc2119" title="MAY">「してもよい(MAY)」</em>, <em class="rfc2119" title="MUST">「しなければならない(MUST)」</em>,
<em class="rfc2119" title="MUST NOT">「してはならない(MUST NOT)」</em>, <em class="rfc2119" title="NOT RECOMMENDED">「推奨されない(NOT RECOMENDED)」</em>,
 <em class="rfc2119" title="RECOMMENDED">「推奨される(RECOMMENDED)」</em>, <em class="rfc2119" title="SHOULD">「する必要がある(SHOULD)」</em>,
 および <em class="rfc2119" title="SHOULD NOT">「しないほうがよい(SHOULD NOT)」</em>は、[<cite><a class="bibref" href="#bib-RFC2119">RFC2119</a></cite>]に述べられているように解釈される。</p>

**Comment by momdo** [comment]
訳出自体は問題ないです。が、JIS X 8341-3:2016に沿った訳出をする場合（すなわち、JIS原案を視野に入れて、JISの表現規則に限りなく沿った訳出を心掛ける場合）、RFC 2119キーワードは、JISZ8301の付属書H（規定を表す言葉の表現形式）にある訳出にあわせる必要があると考えています。（内容はJISCのJIS検索から当たってください。手前味噌ですが、拙ブログの<a href="http://momdo.hatenablog.jp/entry/20160619/1466314471">JISにおける規定を表す言葉の表現形式</a>にもそれっぽいものがあります。）

**Comment by motchie** [comment]
@momdo 確認遅くなりました。RFC部分のキーワードのご指摘ありがとうございます。

**Comment by momdo** [comment]
@motchie 
あるいは、GitHub上ですべて操作するのもありかもしれませんね（面倒ですけども）。
