### ISSUE TITLE
達成基準 2.5.2 ポインタのキャンセル

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#90]
箇条書きの2つめ 

> 中止または元に戻すことができる: 機能の完了にはアップイベントを使用し、かつ機能の完了前にを中止する、又は機能の完了後に元に戻すためのメカニズムが利用できる。

「機能の完了前**にを**中止する」は「機能の完了前**に**中止する」の TYPO かと思われます。

**Comment by momdo** [comment]
中止または元に戻すことができる→中止又は元に戻すことができる

**Comment by caztcha** [comment]
「または」→「又は」も含め、プルリクエストまとめます。

**Comment by caztcha** [comment]
[PR #162](https://github.com/waic/wcag21/pull/162) にて対応しました。

**Comment by bakera** [comment]
原文の見出し "Abort or Undo" には「できる」というニュアンスはないように思いましたが、説明文中では available と言っていますし、まあいいかなぁと。
