### ISSUE TITLE
達成基準 2.5.4 動作による起動

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#91]
> デバイスの動作やユーザの動作で操作できる機能が、ユーザインタフェース コンポーネントでも操作でき、かつ予期しない起動を防ぐために動作への反応を無効化することができる。ただし、以下の場合は例外とする。

「ユーザ」は「利用者」に置換、また冒頭の「デバイスの動作やユーザの動作で操作できる機能が」は、「が」を「は」にしてはいかがでしょうか。
また、motion を「動作」と訳していますが、この達成基準の箇条書き2つめ (必要不可欠) の原文にある「activity」という語が、WCAG 2.0 で「動作」と訳されているので、競合しそうです。ここでは motion を「動き」とするのはいかがでしょうか。

(改善案)
達成基準 2.5.4 動きによる起動

デバイスの動きや利用者の動きで操作できる機能は、ユーザインタフェース コンポーネントでも操作でき、かつ予期しない起動を防ぐために動きへの反応を無効化することができる。ただし、以下の場合は例外とする。

---

箇条書き1つめ :
	
> サポートされたインタフェース: 動作は機能を操作するためにアクセシビリティ サポーテッドなインタフェースを通じて用いられる。

(改善案)
サポートされたインタフェース: アクセシビリティ サポーテッドなインタフェースを通じて機能を操作するのに動きが用いられる。

---

箇条書き2つめ :

> 必要不可欠: その動作が機能にとって必要不可欠であり、これを無効化すればアクティビティを無効化してしまう。

doing so は「動きへの反応を無効化する」だけとは限らず、「この達成基準（箇条書きの手前の規定）を守ると」という意味になると思います。ここでは「上記に従うと」としてみましたがいかがでしょうか。

(改善案)
必要不可欠: その機能にとって動きが必要不可欠であり、上記に従うと、動作を無効化してしまう。

**Comment by momdo** [comment]
デバイスの動きや利用者の動き→デバイスの動き又は利用者の動き
<hr>
> 操作するのに動きが

操作するために動きが、でよかったのでは…？
<hr>
「上記」だと、1つめの項目とも、冒頭の段落とも取れてしまうのでは。

**Comment by momdo** [comment]
マージされたので閉じます。
