### ISSUE TITLE
用語集：need to の翻訳

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#918]
mustと同義になっている箇所が2箇所ある（WCAG 2.0訳も同様）。

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-accessibility-supported

> However, all ways of using technologies in the documentation would need to meet the definition of accessibility-supported Web content technologies above. 

https://waic.jp/docs/WCAG21/#dfn-accessibility-supported

> しかし、文書中の技術の使用方法すべては、前述のアクセシビリティ サポーテッドなウェブコンテンツ技術の定義を満たしていなければならない。

---

https://www.w3.org/TR/2018/REC-WCAG21-20180605/#dfn-mechanism

> The mechanism needs to meet all success criteria for the conformance level claimed.

https://waic.jp/docs/WCAG21/#dfn-mechanism

> メカニズムは、宣言する適合レベルのすべての達成基準を満たさなければならない。

**Comment by bakera** [comment]
ちなみにJIS X 8341-3:2016の規格票では、前者は「満たしている必要がある」、後者は「満たさなければならない」となっている模様。

**Comment by caztcha** [comment]
どちらも、「満たしている必要がある」に修正します。
PR #1309 で対応しました。
