### ISSUE TITLE
5.3.1 適合表明の必須要素 でインラインの注記が未訳

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#919]
https://waic.jp/docs/WCAG21/#conformance-required

> In WCAG 2.0 this was a dated URI, which may need to be adjusted when this becomes a Rec.

原文のママになっている。

**Comment by bakera** [comment]
この注記自体、WCAG 2.1 ドラフト時点での作業メモに見える。
日本語訳では削除でも良いのではないか。

**Comment by caztcha** [comment]
私も原文と見比べてみて、 @bakera さんと同じ印象を持ちました。
この部分を削除した形でプルリクエスト出しますね。

**Comment by caztcha** [comment]
PR #1307 で対応しました。
