### ISSUE TITLE
READMEから「策定中」を削除する

### ISSUE THREAD

**Issue by bakera** [waic/wcag21#93]
READMEに以下のように書かれていますが、

>WCAG 2.1 自体、W3C AGWG によって策定中の文書であることに注意してください。

すでに勧告になっていますので、この文は削除で良いのかなと。

**Comment by momdo** [comment]
WCAG 2.1 の策定は完了していますが、関連文書である Understanding WCAG 2.1及び Techniques for WCAG 2.1 は、W3C AGWG によって策定中の文書であることに注意してください。

ぐらいですかね？
