### ISSUE TITLE
達成基準 2.5.5 ターゲットのサイズ

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#95]
箇条書き2つめ:

> インラインである: そのターゲットが文章又はテキストブロック内に存在する。

原文の sentence が「文章」と訳されていますが、原文に忠実であろうとすると「文」でしょうか。
(達成基準が言わんとしていることには変わりはない気がしますが...。下記に改善案を書いてみましたが、「文又は」より「文章又は」のほうが視認性がよい気がするので、ここは敢えて意訳する、という判断もありかもしれないですね。)

(改善案)
インラインである: そのターゲットが文又はテキストブロック内に存在する。

**Comment by momdo** [comment]
原文が
>The target is in a sentence or block of text;

なので、やや強引ですが、「1つの文」とするのはありかもしれません。

**Comment by bakera** [comment]
>Inline:
>The target is in a sentence or block of text;

これは単に文中リンクは対象外と言っているだけで、a は数を限定する意図でもないように思えますがどうでしょうか。「一つの」と背極的に訳してしまうと、テキストリンクが折り返したら対象になるのかとか、変な疑問が出てきそうな感じがします。

>インライン:
>そのターゲットが文中、又はテキストブロック中にある

**Comment by caztcha** [comment]
@bakera なるほど、「文中、又はテキストブロックの中」いいですね。ありがとうございます。

追加コミットで対応しました。
https://github.com/waic/wcag21/pull/163/commits/1864fbb37f1558bd9065375a36c40e67b4547645

**Comment by momdo** [comment]
マージされたので閉じます。
