### ISSUE TITLE
達成基準 2.5.6 入力メカニズム非依存

### ISSUE THREAD

**Issue by caztcha** [waic/wcag21#96]
> ただし、その制限が必要不可欠な場合、コンテンツのセキュリティのために必要な場合、又はユーザ設定を尊重するうえで必要な場合は例外とする。

user settings の user を、WCAG 内の用語統一に合わせて「利用者」と訳すとすると、ここは「利用者による設定」でしょうか。

(改善案)
ただし、その制限が必要不可欠な場合、コンテンツのセキュリティのために必要な場合、又は**利用者による設定**を尊重するうえで必要な場合は例外とする。

**Comment by caztcha** [comment]
[PR #164](https://github.com/waic/wcag21/pull/164) にて対応しました。

**Comment by momdo** [comment]
マージされたので閉じます
