### ISSUE TITLE
解説書 2.4.6 失敗例へのリンクがないのに見出しと冒頭の一文がある

### ISSUE THREAD

**Issue by momdo** [waic/wcag21#994]
WAIC内Slackでのコメントより。

https://waic.jp/docs/WCAG21/Understanding/headings-and-labels.html#failure

**Comment by momdo** [comment]
「参考達成方法」のリンクがないのも同様。他の解説書にも同様の記述がないかを要チェック？

**Comment by bakera** [comment]
2.0だと「(今のところ、文書化された失敗例はない)」という本文が入ってたんですね。

https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-descriptive.html

まあ本家に合わせて見出しごと削除ですね。

**Comment by momdo** [comment]
リンク変更を除くと、変更点は当該箇所の削除のみであることを確認。
https://github.com/waic/w3c-wcag/commit/1a05939b6da3c9605b93d99df7249867e1a50082#diff-8fd24d02e412945a68c3bcb2fb5b4c3ac076ef62f2b4c6d5e518bff8d9f6d37b
